### PR TITLE
GenerateMultihistory

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Implements `GenerateMultihistory` function.
* Also implements related introspection functions, i.e., `$SetReplaceSystems`, `EventSelectionParameters`, `EventOrderingFunctions` and `StoppingConditionParameters`.
* Also implements package-scope `declareMultihistoryGenerator` used to specify the kinds of event selections, orderings, and stopping conditions a system supports. `GenerateMultihistory` then does most of the arguments checking itself (although it is possible to throw and generate messages from the specific implementations).

## Comments

* I did not write documentation yet, because it seems silly to write descriptions of things like event selection and token deduplication without having any examples to show. I will write documentation for both generators and `MultisetSubstitutionSystem` once both are merged.

## Examples

* Declare a generator. Here, `Infinity` and `0` are the defaults, and `"NonNegativeIntegerOrInfinity"` enables automatic checking and is, in addition to `None`, is the only one supported at the moment (it is, by far, the most common).

```wl
SetReplace`PackageScope`declareMultihistoryGenerator[
  generateMultisetMultihistory,
  MultisetSubstitutionSystem,
  <|"MaxGeneration" -> {Infinity, "NonNegativeIntegerOrInfinity"},
    "MinEventInputs" -> {0, "NonNegativeIntegerOrInfinity"}|>,
  {"InputCount", "RuleOrdering"},
  <|"MaxEvents" -> {Infinity, "NonNegativeIntegerOrInfinity"}|>];
Unprotect[$SetReplaceSystems];
SetReplace`PackageScope`initializeGenerators[];
```

* Now, try to use the generator. Note that `GenerateMultihistory` automatically inserted the missing parameters. The first argument is passed unchanged:

```wl
In[] := GenerateMultihistory[
  MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> 3|>, All, {"InputCount"}, {}][0]
Out[] = generateMultisetMultihistory[MultisetSubstitutionSystem[1, 2],
                                     <|"MaxGeneration" -> 3, "MinEventInputs" -> 0|>,
                                     All,
                                     {"InputCount"},
                                     <|"MaxEvents" -> \[Infinity]|>,
                                     0]
```

* Try to pass invalid or non-existing parameters will throw an error before ever reaching `generateMultisetMultihistory`:

```wl
In[] := GenerateMultihistory[
  MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> -1|>, All, {"InputCount"}, {}][0]
```

image

```wl
Out[] = GenerateMultihistory[
  MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> -1|>, All, {"InputCount"}, {}][0]
```

* Query the list of all systems available:

```wl
In[] := $SetReplaceSystems
Out[] = {MultisetSubstitutionSystem}
```

* Query the available parameters for a particular system:

```wl
In[] := Through[
  {EventSelectionParameters, EventOrderingFunctions, StoppingConditionParameters} @
    MultisetSubstitutionSystem]
Out[] = {{"MaxGeneration", "MinEventInputs"}, {"InputCount", "RuleOrdering"}, {"MaxEvents"}}
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626)

### CODE REVIEW

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Kernel/A1$GenerateMultihistory.m, line 15 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qP85-w9DpbssMV7R:-MW6qP85-w9DpbssMV7S:b-14tvv5) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L15)):*
> ```objc
> 
> SetUsage @ "
> GenerateMultihistory[system$, eventSelectionSpec$, tokenDeduplicationSpec$, eventOrderingSpec$, \
> ```

Perhaps this usage can use bullets for describing each parameter similar to:

___
*[Kernel/A1$GenerateMultihistory.m, line 46 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qsJW3StFeNv8if6l:-MW6qsJW3StFeNv8if6m:bh4htio) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L46)):*
> ```objc
>    The metadata about selection, ordering and stopping conditions will be used to automatically check the arguments.
>    The implementation function can expect event selection and stopping conditions to be passed as associations with
>    all specified keys present and valid according to the constraint (substituted with defaults if missing).
> ```

They should be substituted with defaults if missing or Automatic.
___
*[Kernel/A1$GenerateMultihistory.m, line 165 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6taLI26ROhwLb_pr8:-MW6taLI26ROhwLb_pr9:bwcuow) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L165)):*
> ```objc
> (* Introspection functions *)
> 
> PackageExport["StoppingConditionParameters"]
> ```

Duplicate export.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Kernel/A1$GenerateMultihistory.m, line 15 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qP85-w9DpbssMV7R:-MW7FbAx99iReET5KAPC:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L15)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Perhaps this usage can use bullets for describing each parameter similar to:


</blockquote></details>

Done.
___
*[Kernel/A1$GenerateMultihistory.m, line 46 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qsJW3StFeNv8if6l:-MW7Fc5U6s12MhVSExOm:be2t4ke) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L46)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

They should be substituted with defaults if missing or Automatic.
</blockquote></details>

The default in this case means they are disabled. Does it really make sense to say something like `"MaxEvents" -> Automatic` and expect `Automatic` to be `Infinity`? Why would someone want to do that?
___
*[Kernel/A1$GenerateMultihistory.m, line 165 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6taLI26ROhwLb_pr8:-MW7Fz-I56arSm5TnFrX:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L165)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Duplicate export.
</blockquote></details>

Done.

**Comment by maxitg** [comment]
@daneelsan, @taliesinb?

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[Kernel/A1$GenerateMultihistory.m, line 46 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qsJW3StFeNv8if6l:-MWVIgST3RRafu2iwILM:b-a0wisa) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L46)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The default in this case means they are disabled. Does it really make sense to say something like `"MaxEvents" -> Automatic` and expect `Automatic` to be `Infinity`? Why would someone want to do that?
</blockquote></details>

Isn't that how `Automatic` works? That:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> Automatic, "MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```
should behave exactly as:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```
which behave as:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> Infinity, "MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```

This isn't that important, I agree.

**Review by daneelsan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626#-:-MWVJR8ED0UpseF4anD_:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/626)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @daneelsan and @taliesinb)

___
*[Kernel/A1$GenerateMultihistory.m, line 46 at r1](https://reviewable.io/reviews/maxitg/setreplace/626#-MW6qsJW3StFeNv8if6l:-MWVK-9F7ewj3EhtLegS:buun9rk) ([raw file](https://github.com/maxitg/setreplace/blob/9b0b0539108387882bf8035ab8432f7d8645141d/Kernel/A1$GenerateMultihistory.m#L46)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Isn't that how `Automatic` works? That:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> Automatic, "MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```
should behave exactly as:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```
which behave as:
```wl
GenerateMultihistory[MultisetSubstitutionSystem[1, 2], <|"MaxGeneration" -> Infinity, "MaxEvents" -> 3|>, All, {"InputCount"}, {}][0]
```

This isn't that important, I agree.
</blockquote></details>

I think it might lead to confusing code because it's not very clear what `"MaxGeneration" -> Automatic` is, and it's not hard to use `Infinity` instead. I actually think it would make more sense to use `"Disabled"` instead of `Automatic`. In any case, we can add it later if there is a demand.

**Pull request merged**
