### PR TITLE
Custom files and formatting only in lint.sh

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Allows formatting only when using `./lint.sh`. This will skip linting, and thus is guaranteed to succeed if called with `-i`. Useful for the pre-commit hook.
* Allows specifying files to lint in `./lint.sh`.
* Fixes line-length checking which would miss errors if the error was in the last file checked.
* Fixes usage message for `./lint.sh`.

## Comments

* Fixing trailing spaces is quite useful in a pre-commit hook.

## Examples

* Introduce both linting and formatting errors to `lint.sh`:

```console
$ ./lint.sh lint.sh
lint.sh
--- lint.sh.orig
+++ lint.sh
@@ -91,7 +91,7 @@
   formatWithCommand clang-format "$file"
 done
 
-for file in "${bashFiles[@]}"; do 
+for file in "${bashFiles[@]}"; do
   if [ $formatInPlace -eq 1 ]; then
     shfmt -w -i 2 "$file"
   else

Found formatting errors. Run ./lint.sh -i to automatically fix by applying the printed patch.

In lint.sh line 102:
for file in ${remainingFiles[@]}; do
            ^------------------^ SC2068: Double quote array expansions to avoid re-splitting elements.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
```

* Commit and check that the formatting error is fixed:

```console
$ git add . && git commit -m "Test commit."
[feature/formatOnly 62a2b931] Test commit.
 1 file changed, 1 insertion(+), 1 deletion(-)
$ ./lint.sh lint.sh

In lint.sh line 102:
for file in ${remainingFiles[@]}; do
            ^------------------^ SC2068: Double quote array expansions to avoid re-splitting elements.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
```

* Go back to the previous commit:

```console
$ git reset --hard @~1
HEAD is now at 28e1d5ae Format all files in pre-commit hook.
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/634)

### CODE REVIEW

**Comment by maxitg** [comment]
Hi, @aokellermann, could you take a look at this with your bash wisdom when you have a chance? Not urgent, though.

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/634)* status: all files reviewed, 5 unresolved discussions (waiting on @maxitg)

___
*[lint.sh, line 32 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYb7IUb84ddhzvDR5in:-MYb7IUb84ddhzvDR5io:bt1moh2) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L32)):*
> ```Shell
>       echo "Argument $arg is not recognized."
>       echo
>       echo "Usage: ./lint.sh [-i] [-f] [file1] [file2] ..."
> ```

Usually in man pages file varargs are represented as `[FILE]...`.
___
*[lint.sh, line 38 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYb8XtfBtjdl0Wb72LU:-MYb8XtfBtjdl0Wb72LV:bu6ig8o) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L38)):*
> ```Shell
>       echo "Options:"
>       echo "  -i  Edit files in place if possible."
>       echo "  -f  Only perform formatting and skip linting. Always succeeds if used with -i."
> ```

The definition of success is not obvious here. I know what you mean but perhaps it could be reworded.
___
*[lint.sh, line 39 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbA76PA26Eyw87MQ33:-MYbA76PA26Eyw87MQ34:b-22ftzp) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L39)):*
> ```Shell
>       echo "  -i  Edit files in place if possible."
>       echo "  -f  Only perform formatting and skip linting. Always succeeds if used with -i."
>       exit 1
> ```

Exit code of 2 is often used for argument errors.
___
*[lint.sh, line 136 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbDHny2titk4Ljhull:-MYbDHny2titk4Ljhulm:b-j174qb) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L136)):*
> ```Shell
>   for file in "${remainingFiles[@]}" "${bashFiles[@]}"; do
>     ./scripts/checkLineWidth.sh "$file" "$widthLimit"
>   done || true
> ```

You used `:` above, but `true` here. They are synonyms, so stick to one (preferably `:`).
___
*[scripts/git_hooks/pre-commit, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbDzQD1Sp66UJe12tD:-MYbDzQD1Sp66UJe12tE:b-z5mfr4) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/scripts/git_hooks/pre-commit#L3)):*
> ```
> #!/usr/bin/env bash
> 
> stagedFiles=$(git diff --name-only --cached | sort)
> ```

Sorting is no longer necessary here.

**Comment by aokellermann** [comment]
Something interesting I learned is that you can create an empty git commit (without specifying `--allow-empty`) if you only have illegal formatting changes staged.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/634)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @aokellermann)

___
*[lint.sh, line 32 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYb7IUb84ddhzvDR5in:-MYeZd5HCmbB4eitlQBD:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L32)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Usually in man pages file varargs are represented as `[FILE]...`.
</blockquote></details>

Done.
___
*[lint.sh, line 38 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYb8XtfBtjdl0Wb72LU:-MYeZwAY7kBglmPrWRkh:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L38)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

The definition of success is not obvious here. I know what you mean but perhaps it could be reworded.
</blockquote></details>

Done.
___
*[lint.sh, line 39 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbA76PA26Eyw87MQ33:-MYeZxkpC1GhcGlJl6rL:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L39)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Exit code of 2 is often used for argument errors.
</blockquote></details>

Done.
___
*[lint.sh, line 136 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbDHny2titk4Ljhull:-MYe_7OgCs5QvRPtwUv1:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/lint.sh#L136)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

You used `:` above, but `true` here. They are synonyms, so stick to one (preferably `:`).
</blockquote></details>

Done.
___
*[scripts/git_hooks/pre-commit, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/634#-MYbDzQD1Sp66UJe12tD:-MYe_J2_BZZAF29Mk1f0:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4d8c2fb9c7b2a42d74f11b9921bfcade9999adfe/scripts/git_hooks/pre-commit#L3)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Sorting is no longer necessary here.
</blockquote></details>

Done.

**Review by aokellermann — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maxitg)

**Pull request merged**
