### PR TITLE
Renaming VertexCoordinateRules to VertexCoordinates.

### LINKED ISSUE #251: Rename VertexCoordinateRules -> VertexCoordinates
`VertexCoordinateRules` was a temporary name used in `GraphPlot` which was never even released in any WL version.

We should not be using it in `SetReplace` and should change it back to `VertexCoordinates` to be consistent with the released version of `GraphPlot`.

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes

* Closes #251.
* Renames all instances of `VertexCoordinateRules` to `VertexCoordinates`.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan and @maxitg)

*[a discussion](https://reviewable.io/reviews/maxitg/setreplace/594#-MQrmC_V5Xl0ymKbkw1T:-MQrmC_V5Xl0ymKbkw1U:bd729sv) (no related file):*
Still some to rename:
```bash
$ grep -rnwi . -e "coordinaterules"
./Kernel/HypergraphPlot.m:242:  If[!MatchQ[coordinateRules,
./Kernel/HypergraphPlot.m:245:    Message[head::invalidCoordinates, coordinateRules];
./Kernel/HypergraphPlot.m:337:  hypergraphEmbedding[edgeType, edgeType, hyperedgeRendering, coordinateRules];
./Kernel/HypergraphPlot.m:356:      coordinateRules]]
./Kernel/HypergraphPlot.m:366:  relevantCoordinateRules = Normal[Merge[Select[MemberQ[vertices, #[[1]]] &][coordinateRules], Last]];
./Kernel/HypergraphPlot.m:379:  graphEmbedding[vertices, edges, layout, coordinateRules][[1]];
./Kernel/HypergraphPlot.m:395:      VertexCoordinates -> coordinateRules,
```

---

**Review by maxitg — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

*[a discussion](https://reviewable.io/reviews/maxitg/setreplace/594#-MQrmC_V5Xl0ymKbkw1T:-MQrpxvk9K66GXbiFTQK:b-vazq7b) (no related file):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Still some to rename:
```bash
$ grep -rnwi . -e "coordinaterules"
./Kernel/HypergraphPlot.m:242:  If[!MatchQ[coordinateRules,
./Kernel/HypergraphPlot.m:245:    Message[head::invalidCoordinates, coordinateRules];
./Kernel/HypergraphPlot.m:337:  hypergraphEmbedding[edgeType, edgeType, hyperedgeRendering, coordinateRules];
./Kernel/HypergraphPlot.m:356:      coordinateRules]]
./Kernel/HypergraphPlot.m:366:  relevantCoordinateRules = Normal[Merge[Select[MemberQ[vertices, #[[1]]] &][coordinateRules], Last]];
./Kernel/HypergraphPlot.m:379:  graphEmbedding[vertices, edges, layout, coordinateRules][[1]];
./Kernel/HypergraphPlot.m:395:      VertexCoordinates -> coordinateRules,
```
</blockquote></details>

The issue is about renaming the option `VertexCoordinateRules` to `VertexCoordinates` to be consistent with Wolfram Language conventions. I don't see a problem with local variables being called coordinate rules, because they are in fact rules.

---

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @maxitg)

*[a discussion](https://reviewable.io/reviews/maxitg/setreplace/594#-MQrmC_V5Xl0ymKbkw1T:-MQwiQl32rFvk4H5UjcS:b4f7nlz) (no related file):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The issue is about renaming the option `VertexCoordinateRules` to `VertexCoordinates` to be consistent with Wolfram Language conventions. I don't see a problem with local variables being called coordinate rules, because they are in fact rules.
</blockquote></details>

I renamed them any ways for consistency.

---

**Review by maxitg — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

**Review by aokellermann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/594)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
