### PR TITLE
Use a temporary build directory

### PR DESCRIPTION
**Pull request by taliesinb**
Use a temporary build directory, rather than the /Build subdir of the root dir. This is friendlier to IDEs, find-in-files, etc. This will have to be rebased if #518 lands to update the temporary directory used *there* as well.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/519)

### CODE REVIEW

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/519#-:-ML_ttPN1d4ZVo97Lo6l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by taliesinb** [comment]
@maxitg : I have actually implemented the more ambitious goal we discussed, about doing inline builds on developer machines so that there is no separate Build directory. I'll open a PR for that, but let's keep this PR around in case we reject that PR.

**Comment by maxitg** [comment]
Why don't we merge it now while we work on that other PR? It does not make things worse, and it's done already. I don't see any reason to hold it.

**Review by taliesinb — COMMENTED** [review]
Ok!

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/519#-:-MLgaZKY90GUJ9vbzLyI:b2nhlkw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @taliesinb)

**Pull request merged**
