### PR TITLE
Add pattern names in SyntaxInformation and missing usage, syntax information and syntax autocompletion

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* In the Mathematica options inspector, there is an option called `"HighlightMissingArgumentsWithTemplate"`.
* If you turn it on, in case of missing arguments, instead of displaying a single red arrow, you will get a helpful hint with argument names which can serve as a super fast lightweight documentation (like you would get in, e.g., Xcode after autocompleting a function):

HighlightMissingArgumentsWithTemplate

* The names of the arguments are taken from pattern names in `SyntaxInformation`.
* This PR adds names to all `SyntaxInformation` except for the built-in `RulePlot` thus enabling this feature for all *SetReplace* symbols.

* This also adds missing usage messages, syntax information, and syntax autocompletion.
* Expands argument names in usage messages to be descriptive so that using autocompleted templates are more informative.

## Comments

* `Null` is due to `OptionsPattern[]`. It can be changed to, say, `opts` if that pattern is named as `opts : OptionsPattern[]`. However, if one does that, some optional arguments will always be displayed in the template, which is, of course, unacceptable. I think we'll have to wait until this weed is fixed upstream:

image

* Autocompletion is generally disabled for option names. The problem is that I'm not aware of a way to enable autocompletion for multiple arguments at a time. In order to solve this, we need to use symbols instead of strings for options (#604), and we need to figure out how to autocomplete the values for enum-like options (#605).

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)

### CODE REVIEW

**Comment by maxitg** [comment]
@daneelsan, is there any reason not to merge this now while we try to figure out how to do autocompletion for options?

**Comment by daneelsan** [comment]
@maxitg I missed the last changes you made. I'll review it now.

**Review by daneelsan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 31 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)* status: 5 of 32 files reviewed, 8 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Kernel/GeneralizedGridGraph.m, line 32 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy1gosDIilY1GzhWT0:-MSy1gosDIilY1GzhWT1:b-upn8n6) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/GeneralizedGridGraph.m#L32)):*
> ```objc
> (* Implementation *)
> 
> GeneralizedGridGraph[args___] := ModuleScope[
> ```

To change `args_` -> `dimensionSpecs_, opts : OptionsPattern[]` the `CheckArgumentCount` check should probably done in `GeneralizedGridGraph`:

```wl
GeneralizedGridGraph[args___] :=
  Null /; CheckArguments[GeneralizedGridGraph[args], {1, 1}] && False;
```
then
```wl
GeneralizedGridGraph[dimensionSpecs_, opts : OptionsPattern[]] := ModuleScope[...]
```

We might want to standardize how we do argument check for all our exposed functions.
___
*[Kernel/HypergraphToGraph.m, line 43 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0YPF0IVnalw8F61E:-MSy0YPF0IVnalw8F61F:b-vnz90q) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/HypergraphToGraph.m#L43)):*
> ```objc
> (* main *)
> expr : HypergraphToGraph[
>       hgraph_,
> ```

`hypergraph_,`
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0m6w2JDjKjWPEJmi:-MSy0m6w2JDjKjWPEJmj:blvzzam) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/IndexHypergraph.m#L22)):*
> ```objc
> 
> (* main *)
> expr : IndexHypergraph[hgraph_, start : _ : 1] := ModuleScope[
> ```

`IndexHypergraph[hypergraph_, startIndex_ : 1]`
___
*[Kernel/IsomorphicHypergraphQ.m, line 23 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0zd333d7bNQQ_q6P:-MSy0zd333d7bNQQ_q6Q:b-472jza) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/IsomorphicHypergraphQ.m#L23)):*
> ```objc
> 
> (* main *)
> expr : IsomorphicHypergraphQ[hgraph1_, hgraph2_] := ModuleScope[
> ```

`IsomorphicHypergraphQ[hypergraph1_, hypergraph2_]`
___
*[Kernel/RandomHypergraph.m, line 25 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy1EW_7NeHNq-YoBOE:-MSy1EW_7NeHNq-YoBOF:bsay4xy) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/RandomHypergraph.m#L25)):*
> ```objc
> 
> (* Main entry *)
> expr : RandomHypergraph[sig_, max_ : Automatic] := ModuleScope[
> ```

`RandomHypergraph[sizeSpec_, maxVertices_ : Automatic]`
___
*[Kernel/Subhypergraph.m, line 39 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy2f42AzhCHC0KnWdm:-MSy2f42AzhCHC0KnWdn:b7z6l4t) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/Subhypergraph.m#L39)):*
> ```objc
> 
> (* main *)
> expr : Subhypergraph[arg1_, arg2_] := With[{res = Catch[subhypergraph[HoldForm @ expr, arg1, arg2]]},
> ```

`arg1_, arg2_` -> `hypergraph_, vertexList_`
___
*[Kernel/ToPatternRules.m, line 70 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy375Z0w0SAJcHVuQP:-MSy375Z0w0SAJcHVuQQ:b-yz63wl) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/ToPatternRules.m#L70)):*
> ```objc
>   toPatternRules[#, caller] & /@ rules;
> 
> ToPatternRules[rules_] := ModuleScope[
> ```

`hypergraphRules_`
___
*[Kernel/WolframModel.m, line 39 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy3Mh1-mPashOKgu2K:-MSy3Mh1-mPashOKgu2L:b-gpzg0p) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/WolframModel.m#L39)):*
> ```objc
> With[{properties = $newParameterlessProperties,
>       stepSpecKeys = Values[$stepSpecKeys]},
>   FE`Evaluate[FEPrivate`AddSpecialArgCompletion["WolframModel" -> {{"PatternRules"}, 0, stepSpecKeys, properties}]]];
> ```

Interesting. So the list of strings autocompletes not only at level 1...

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)* status: 5 of 32 files reviewed, 8 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Kernel/GeneralizedGridGraph.m, line 32 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy1gosDIilY1GzhWT0:-MSy4CgLDqGuIQej2Ohz:bhs6z6x) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/GeneralizedGridGraph.m#L32)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

To change `args_` -> `dimensionSpecs_, opts : OptionsPattern[]` the `CheckArgumentCount` check should probably done in `GeneralizedGridGraph`:

```wl
GeneralizedGridGraph[args___] :=
  Null /; CheckArguments[GeneralizedGridGraph[args], {1, 1}] && False;
```
then
```wl
GeneralizedGridGraph[dimensionSpecs_, opts : OptionsPattern[]] := ModuleScope[...]
```

We might want to standardize how we do argument check for all our exposed functions.
</blockquote></details>

Why would we want to check in `GeneralizedGridGraph`? I think it would be better to do it consistently with `throw[Failure[...]]`. I agree wrt consistency, and I think we should use the new messages system for it.
___
*[Kernel/HypergraphToGraph.m, line 43 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0YPF0IVnalw8F61E:-MSy4hQaCUnDRyahuKaG:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/HypergraphToGraph.m#L43)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`hypergraph_,`
</blockquote></details>

Done.
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0m6w2JDjKjWPEJmi:-MSy4slH5I9cQN7fuCsJ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/IndexHypergraph.m#L22)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`IndexHypergraph[hypergraph_, startIndex_ : 1]`
</blockquote></details>

Done.
___
*[Kernel/IsomorphicHypergraphQ.m, line 23 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy0zd333d7bNQQ_q6P:-MSy4wT087STnrUGSF_A:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/IsomorphicHypergraphQ.m#L23)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`IsomorphicHypergraphQ[hypergraph1_, hypergraph2_]`
</blockquote></details>

Done.
___
*[Kernel/RandomHypergraph.m, line 25 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy1EW_7NeHNq-YoBOE:-MSy5NHC2j3JOuzPVYyV:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/RandomHypergraph.m#L25)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`RandomHypergraph[sizeSpec_, maxVertices_ : Automatic]`
</blockquote></details>

Done.
___
*[Kernel/Subhypergraph.m, line 39 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy2f42AzhCHC0KnWdm:-MSy5YJJDCn0GXq3VjLf:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/Subhypergraph.m#L39)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`arg1_, arg2_` -> `hypergraph_, vertexList_`
</blockquote></details>

Done.
___
*[Kernel/ToPatternRules.m, line 70 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy375Z0w0SAJcHVuQP:-MSy5mkt0tylN8Y6FB1l:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/ToPatternRules.m#L70)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`hypergraphRules_`
</blockquote></details>

Done.
___
*[Kernel/WolframModel.m, line 39 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy3Mh1-mPashOKgu2K:-MSy5oFb-s_-7vJg0F15:b-fp73re) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/WolframModel.m#L39)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Interesting. So the list of strings autocompletes not only at level 1...
</blockquote></details>

Yes, it does.

**Review by daneelsan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)* status: 5 of 32 files reviewed, 9 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/GeneralizedGridGraph.m, line 32 at r5](https://reviewable.io/reviews/maxitg/setreplace/603#-MSy1gosDIilY1GzhWT0:-MSyU0ibEg8BlVW6E0Dr:bv2cdg2) ([raw file](https://github.com/maxitg/setreplace/blob/187b0bfd3c1cabf7d7378c1f800f9f144887a3f2/Kernel/GeneralizedGridGraph.m#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Why would we want to check in `GeneralizedGridGraph`? I think it would be better to do it consistently with `throw[Failure[...]]`. I agree wrt consistency, and I think we should use the new messages system for it.
</blockquote></details>

Right, also
```
func[args___] /; !CheckArgumentCount[...] := throw[...]
```

makes more sense than
```
Func[args___] := Null /; CheckArgumentCount[...] && False
```
___
*[Kernel/RandomHypergraph.m, line 31 at r6](https://reviewable.io/reviews/maxitg/setreplace/603#-MSyTpvp3_nEvyp64Oga:-MSyTpvp3_nEvyp64Ogb:bf9k2a9) ([raw file](https://github.com/maxitg/setreplace/blob/40c1032733e1f14ca75172d0d18e28b4005f2454/Kernel/RandomHypergraph.m#L31)):*
> ```objc
> 
> (* Error messages *)
> RandomHypergraph::invalidSizeSpec = "\
> ```

This message needs to be also updated also in Tests/.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)* status: 5 of 32 files reviewed, 9 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/RandomHypergraph.m, line 31 at r6](https://reviewable.io/reviews/maxitg/setreplace/603#-MSyTpvp3_nEvyp64Oga:-MSyWH_D2SXY1gwMaUIi:b-h9rirb) ([raw file](https://github.com/maxitg/setreplace/blob/40c1032733e1f14ca75172d0d18e28b4005f2454/Kernel/RandomHypergraph.m#L31)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

This message needs to be also updated also in Tests/.
</blockquote></details>

I reverted it back to not break backwards compatibility unnecessarily.

**Review by daneelsan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/603)* status: 5 of 32 files reviewed, 9 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

**Pull request merged**
