### PR TITLE
Replacing all uses of usageString with GeneralUtilities`SetUsage

### LINKED ISSUE #532: Replace usageString with SetUsage from GeneralUtilities
### The problem
Replace the user-defined `usageString` function (`Kernel/usageString.m`) with `SetUsage` function from `GeneralUtilities`.

```
?GeneralUtilities`SetUsage
```
image

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes
* Closes #532.
* Replaces all instances of `usageString` with `SetUsage` (from `GeneralUtilities`).

## Comments
* List of symbols updated:
```
{
  "GeneralizedGridGraph", "HypergraphAutomorphismGroup", "HypergraphToGraph", "HypergraphUnifications",
  "HypergraphUnificationsPlot", "IndexHypergraph", "IsomorphicHypergraphQ", "SetReplace", "SetReplaceAll",
  "SetReplaceFixedPoint", "SetReplaceFixedPointList", "SetReplaceList", "Subhypergraph", "ToPatternRules", 
  "WeakSubhypergraph", "WolframModel", "WolframModelEvolutionObject", "WolframModelPlot", 
  "WolframModelRuleValue", "WolframPhysicsProjectStyleData", "$SetReplaceBuildTime", "$SetReplaceGitSHA", 
  "$SetReplaceMethods", "$WolframModelProperties", "$WolframModelRuleProperties", 
  "$WolframPhysicsProjectPlotThemes"
}
```

## Examples
```
In[] := ?WolframModelEvolutionObject
```
image

```
In[] := ?GeneralizedGridGraph
```
image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/533)

### CODE REVIEW

**Comment by daneelsan** [comment]
Now that `usageString.m` is no more I wonder what should `init.m` call first (perhaps there is no need to that anymore).

**Review by taliesinb — COMMENTED** [review]
This is very nice btw... Much cleaner now!

As for what the entry point should be. Maybe we should make a file called `entryPoint.m` that just contains nothing more than the first `Package["SetReplace`"]`, and a comment that says it is loaded first? That will make it clear at least where to put code that needs to run first, if such code arises in future! That comment could also maybe mention that the other files are loaded in alphabetical order.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/533#-:-MMwet2Q9N6xuTNCWz2D:b-ui9l83)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @maxitg and @taliesinb)

**Review by taliesinb — APPROVED** [review]
> Reviewed 24 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/533)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/buildData.m.template, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/533#-MMwfMe76UNP88Uib_eJ:-MMwfMe76UNP88Uib_eK:bh2g2wj) ([raw file](https://github.com/maxitg/setreplace/blob/30d98a9d5ab3110fb895118690cd351a9c4e1bfc/Kernel/buildData.m.template#L9)):*
> ```
> PackageExport["$SetReplaceBuildTime"]
> 
> SetUsage[$SetReplaceGitSHA, "$SetReplaceGitSHA gives the Git SHA of the repository from which SetReplace was built."]
> ```

This change will be overwritten by the DevUtils PR anyway, but just FYI you can use the compact form for variables too:

```
SetUsage @ "
$SetReplaceGitSHA gives the ...
"
```

**Comment by daneelsan** [comment]
I like the idea of having a `entryPoint.m` file and I totally forgot to change those `SetUsage`'s in `build.m`.

**Pull request merged**
