### PR TITLE
Improve libSetReplace loading

### PR DESCRIPTION
**Pull request by taliesinb**
Try to find the libSetReplace in the same part of the filesystem that the source was loaded from. If that fails, look for a possible Build directory that contains a staged build to use. If that fails, give up.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518)

### CODE REVIEW

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518)* status: all files reviewed, 4 unresolved discussions (waiting on @taliesinb)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 15 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_r2Iu16YAM3JYhXuo:-ML_r2Iu16YAM3JYhXup:b-59m8e7) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L15)):*
> ```objc
> 
> findLibraryIn[basePath_] := Scope[
> 	libraryResources = FileNameJoin[{basePath, "LibraryResources"}];
> ```

tabs -> 2 spaces.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 16 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_rdo46nPiIisKZTTm:-ML_rdo46nPiIisKZTTn:b5mptbk) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L16)):*
> ```objc
> findLibraryIn[basePath_] := Scope[
> 	libraryResources = FileNameJoin[{basePath, "LibraryResources"}];
> 	libraries = FileNames[$expectedLibName, libraryResources, 2];
> ```

Can we use `$SystemID` to obtain the explicit path? I'm afraid the extension might be the same for multiple platforms. We don't have this problem right now, but it might cause trouble in the future.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 21 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_sN90B7o_DJjj2N5a:-ML_sN90B7o_DJjj2N5b:b1isyl6) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L21)):*
> ```objc
> 
> $parentDirectory = FileNameDrop[$InputFileName, -2];
> $buildDirectory = FileNameJoin[{$parentDirectory, "Build"}];
> ```

Note that it will no longer be here after #519 is merged.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_sYxB8q9R6-OKoiXp:-ML_sYxB8q9R6-OKoiXq:b-30n40z) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L27)):*
> ```objc
> 
> $libraryFile = findLibraryIn[$parentDirectory];
> If[FailureQ[$libraryFile], 
> ```

Remove trailing spaces (I really need to get around to implement the linter at least for trivial spacing issues).

**Review by taliesinb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @maxitg)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 15 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_r2Iu16YAM3JYhXuo:-MLeSfOF8czZ7hRh0VxN:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

tabs -> 2 spaces.
</blockquote></details>

Done.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 16 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_rdo46nPiIisKZTTm:-MLeSj8T7RK3Sju7s4Yj:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Can we use `$SystemID` to obtain the explicit path? I'm afraid the extension might be the same for multiple platforms. We don't have this problem right now, but it might cause trouble in the future.
</blockquote></details>

Done.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 21 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_sN90B7o_DJjj2N5a:-MLeSiLI3TMoSd2v-aW5:b-fw5t53) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L21)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Note that it will no longer be here after #519 is merged.
</blockquote></details>

I know... 
___
*[Kernel/setSubstitutionSystem$cpp.m, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/518#-ML_sYxB8q9R6-OKoiXp:-MLeSl911svprZt9LiS1:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2a5953654e6e4ad72e86a885b6c696cb4b4adac8/Kernel/setSubstitutionSystem$cpp.m#L27)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove trailing spaces (I really need to get around to implement the linter at least for trivial spacing issues).
</blockquote></details>

Done.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518)* status: all files reviewed, 1 unresolved discussion (waiting on @taliesinb)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 27 at r2](https://reviewable.io/reviews/maxitg/setreplace/518#-MLf1MUNCGaNJVsl-crw:-MLf1MUNCGaNJVsl-crx:b-b5pmvz) ([raw file](https://github.com/maxitg/setreplace/blob/4c18cf9792b7dd548ab7c66acb30a2018a16db7a/Kernel/setSubstitutionSystem$cpp.m#L27)):*
> ```objc
> $libraryFile = findLibraryIn[$parentDirectory];
> If[FailureQ[$libraryFile],
> 	$libraryFile = findLibraryIn[$buildDirectory];
> ```

Tabs -> 2 spaces.

**Review by taliesinb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 27 at r2](https://reviewable.io/reviews/maxitg/setreplace/518#-MLf1MUNCGaNJVsl-crw:-MLgX8LCDZsTwaV2WS7j:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c18cf9792b7dd548ab7c66acb30a2018a16db7a/Kernel/setSubstitutionSystem$cpp.m#L27)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Tabs -> 2 spaces.
</blockquote></details>

Done.

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/518#-:-MLgvTc378DAK-zSY2H4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
