### PR TITLE
Googletest: Computable results

### PR DESCRIPTION
**Pull request by maxitg**
## Changes
* Stores results of *libSetReplace* tests in the new `TestResults` directory as JUnit XMLs.
* This allows Circle CI to pick up these results and display them in a nice way.

## Comments
* The same can be done for Wolfram Language as well. We will need to produce the XMLs manually, but we can infer the format from the files generated by Googletest.

## Examples
* This is what it looks like when tests [pass](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1379/workflows/31d17a1c-11c5-4d37-9b85-c165b2482a3e/jobs/1849/tests).
* And this is when they [fail](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1378/workflows/2bb65399-5864-4d71-b73a-2d8fff8f919a/jobs/1847/tests).

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/559)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/559)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[libSetReplaceTest.sh, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/559#-MO4LfWk3xK6ng6AtNcs:-MO4LfWk3xK6ng6AtNct:b-ylc9y5) ([raw file](https://github.com/maxitg/setreplace/blob/bf877cc5c3c173a062dfd4ecfb510754ccc7dfe0/libSetReplaceTest.sh#L27)):*
> ```Shell
> libSetReplaceTestsDir=TestResults/libSetReplace
> 
> if [ ! -d "$libSetReplaceTestsDir" ]
> ```

You can `mkdir -p` so there is no need to check if the dir already exists.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/559)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[libSetReplaceTest.sh, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/559#-MO4LfWk3xK6ng6AtNcs:-MO4RJivCiHr0lV-HuAX:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/bf877cc5c3c173a062dfd4ecfb510754ccc7dfe0/libSetReplaceTest.sh#L27)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

You can `mkdir -p` so there is no need to check if the dir already exists.
</blockquote></details>

Done.

**Review by aokellermann — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/559)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by maxitg** [comment]
There was a conflict in the YAML file because the Windows job and the `store_test_results` step were next to each other.

**Pull request merged**
