### PR TITLE
IsomorphicHypergraphQ

### LINKED ISSUE #480: IsomorphicHypergraphQ
### The problem
Implement the `IsomorphicHypergraphQ` function, which tests isomorphism between two hypergraphs.
See:
   - https://resources.wolframcloud.com/FunctionRepository/resources/IsomorphicHypergraphQ
   - [Uniqueness Trees: A Possible Polynomial Approach to the Graph Isomorphism Problem](https://arxiv.org/pdf/1606.06399.pdf)

### Comment
The resource function works for _undirected_ hypergraphs.

### Possible Solution
```wl
In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 5, 1}, {1, 3}, {3, 2}}]
Out[]= True
```

```wl
In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 3, 1}, {1, 3}, {5, 2}}]
Out[]= False
```

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes
* Closes #480.
* Add `IsomorphicHypergraphQ` utility function which tests isomorphism between directed hypergraphs. Internally the function converts the given hypergraph to structure preserving graphs (`HypergraphToGraph[#, "StructurePreserving"]`) and then calling the `System` function `IsomorphicGraphQ`.

## Comments
* None.

## Examples
```wl
In[]:= IsomorphicHypergraphQ[{}, {}]
Out[]= True

In[]:= IsomorphicHypergraphQ[{{}}, {}]
Out[]= False

In[]:= IsomorphicHypergraphQ[{{}}, {{}}]
Out[]= True

In[]:= IsomorphicHypergraphQ[{{}}, {{}, {}}]
Out[]= False

In[]:= IsomorphicHypergraphQ[{{{{1}}}}, {{x}}]
Out[]= True

In[]:= IsomorphicHypergraphQ[{{1, 2}}, {{x, y}}]
Out[]= True

In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 5, 1}, {1, 3}, {3, 2}}]
Out[]= True

In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 3, 1}, {1, 3}, {5, 2}}]
Out[]= False

In[]:= IsomorphicHypergraphQ[{{1, 2}, {2, 3}, {3, 4}, {4, 5}}, {{1, 2}, {2, 3}, {3, 4}, {1, 5}}]
Out[]= False

In[]:= IsomorphicHypergraphQ[{{a, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 1}, {1, 3}, {3, 2}}]
Out[]= True

In[]:= IsomorphicHypergraphQ[
  {{1, 2}, {1, 2}, {1, 3}, {1, 3}, {2, 4}, {3, 4}, {4, 1}},
  {{1, 2}, {1, 2}, {1, 3}, {2, 3}, {3, 4}, {3, 4}, {4, 1}}]
Out[]= False
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492)

### CODE REVIEW

**Comment by maxitg** [comment]
@taliesinb, note, this is WIP as it does not merge to `master`, and we don't want to merge it into `feature/488/HypergraphToGraph`.

**Review by maxitg — CHANGES_REQUESTED** [review]
Neat! I only have some suggestions for the documentation. Otherwise, it's looking great, nice and simple!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492#-:-MKT77jiBCorulG9DBkx:b-kt0630)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT3a25BfC5Gy8yPB4I:-MKT3a25BfC5Gy8yPB4J:b-uh2skr) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
> ```Markdown
> ### IsomorphicHypergraphQ
> 
> **`IsomorphicHypergraphQ`** yields `True` for isomorphic (directed) hypergraphs, and `False` otherwise:
> ```

We call these hypergraphs "ordered" instead of "directed".
___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT3iTH6Vp0XkmN6zEi:-MKT3iTH6Vp0XkmN6zEj:b-p7c2g9) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
> ```Markdown
> ### IsomorphicHypergraphQ
> 
> **`IsomorphicHypergraphQ`** yields `True` for isomorphic (directed) hypergraphs, and `False` otherwise:
> ```

`True` and `False` should link to WL documentation (as a general rule, all built-in symbols should link to documentation similar to how internal documentation works).
___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT4Gi-5Tpm-X3mTJNB:-MKT4Gi-5Tpm-X3mTJNC:b-jjx836) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
> ```Markdown
> ### IsomorphicHypergraphQ
> 
> **`IsomorphicHypergraphQ`** yields `True` for isomorphic (directed) hypergraphs, and `False` otherwise:
> ```

I'm wondering if it's worth it explaining isomorphism to people. At the very least, we should link the word "isomorphic" either to the WL documentation of `IsomorphicGraphQ` or to the [wiki](https://en.wikipedia.org/wiki/Graph_isomorphism) page on graph isomorphism.
___
*[Tests/IsomorphicHypergraphQ.wlt, line 92 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT5eGP5bG4uD1zkudH:-MKT5eGP5bG4uD1zkudI:bnb6wow) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/Tests/IsomorphicHypergraphQ.wlt#L92)):*
> ```Mathematica
>         True
>       ]
>     }
> ```

I think this kind of function might need random/large tests. We can automatically generate random hypergraphs, randomly rename the vertices and see if it can still find isomorphism. Similarly, we can automatically generate cases where there is no isomorphism, although that would be more difficult.

If this function were more complicated (instead of just using `IsomorphismGraphQ`), we would definitely need this to be reasonably certain it works. However, given how simple it is, it would probably be more strategic to wait until we have `RandomHypergraph` before implementing these tests.

We can also cross-check this function with `CanonicalHypergraph` once we have that one.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT3a25BfC5Gy8yPB4I:-MKWjSX-7iIbl-MYZweT:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We call these hypergraphs "ordered" instead of "directed".
</blockquote></details>

Done.
___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT3iTH6Vp0XkmN6zEi:-MKWjSoc6OOmMPtqdtwZ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`True` and `False` should link to WL documentation (as a general rule, all built-in symbols should link to documentation similar to how internal documentation works).
</blockquote></details>

Done.
___
*[README.md, line 2077 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT4Gi-5Tpm-X3mTJNB:-MKWjTTW73H4yS1RYyyh:bp19u81) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/README.md#L2077)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm wondering if it's worth it explaining isomorphism to people. At the very least, we should link the word "isomorphic" either to the WL documentation of `IsomorphicGraphQ` or to the [wiki](https://en.wikipedia.org/wiki/Graph_isomorphism) page on graph isomorphism.
</blockquote></details>

Linked both Wikipedia an `IsomorphicGraphQ`.
___
*[Tests/IsomorphicHypergraphQ.wlt, line 92 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT5eGP5bG4uD1zkudH:-MKWjXe19ppFkUuqpB0v:b-t37pkj) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/Tests/IsomorphicHypergraphQ.wlt#L92)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think this kind of function might need random/large tests. We can automatically generate random hypergraphs, randomly rename the vertices and see if it can still find isomorphism. Similarly, we can automatically generate cases where there is no isomorphism, although that would be more difficult.

If this function were more complicated (instead of just using `IsomorphismGraphQ`), we would definitely need this to be reasonably certain it works. However, given how simple it is, it would probably be more strategic to wait until we have `RandomHypergraph` before implementing these tests.

We can also cross-check this function with `CanonicalHypergraph` once we have that one.
</blockquote></details>

So you say we should wait for `RandomHypergraph` to improve the tests, right?
I agree with the idea of renaming the vertices to test isomorphism.

**Review by maxitg — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @taliesinb)

___
*[Tests/IsomorphicHypergraphQ.wlt, line 92 at r1](https://reviewable.io/reviews/maxitg/setreplace/492#-MKT5eGP5bG4uD1zkudH:-MKatc018aWzXSQCE7mx:b-wqmwu9) ([raw file](https://github.com/maxitg/setreplace/blob/c538bff941b598efa9ee5911f7080f98b17f2af5/Tests/IsomorphicHypergraphQ.wlt#L92)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

So you say we should wait for `RandomHypergraph` to improve the tests, right?
I agree with the idea of renaming the vertices to test isomorphism.
</blockquote></details>

Yes.

We could do it now, but it will be easier once we have `RandomHypergraph`. We similarly don't yet have random-rule tests for `WolframModel` (#72) because we don't yet have `RandomWolframModelRule`.

**Review by taliesinb — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by taliesinb — COMMENTED** [review]
@maxitg I'm not sure I understand what this PR is for, then, if it is not intended to be merged to any branch? 

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492#-:-MKb1Ywn7XBXDl3STyv2:b-ebgf13)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by maxitg** [comment]
@taliesinb, #490 needs to be merged first, then this PR needs to be rebased and merged to `master`.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/IsomorphicHypergraphQ.md, line 19 at r4](https://reviewable.io/reviews/maxitg/setreplace/492#-MKqhckCEO3aB04tfN0a:-MKqhckCEO3aB04tfN0b:b-p0tqwv) ([raw file](https://github.com/maxitg/setreplace/blob/21a701a33a2e5d1a4526fc7077546cfd62fec0c0/Documentation/SymbolsAndFunctions/UtilityFunctions/IsomorphicHypergraphQ.md#L19)):*
> ```Markdown
>   {{2, 4}, {4, 3, 1}, {1, 3}, {5, 2}}]
> Out[]= False
> ```
> ```

Add an empty line at the end of the file (for consistency).

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/492#-:-MKqivyp3bMrfOskrzv-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
