### PR TITLE
MultisetSubstitutionSystem

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Implements `MultisetSubstitutionSystem`.
* It supports arbitrary rules (e.g., conditions, a variable number of inputs on the left-hand side, and any expression on the right-hand side). Basically, it treats rules as black boxes.
* `"MaxDestroyerEvents"`, `"MaxGeneration"`, `"MaxEventInputs"` and `"MaxEventOutputs"` are supported for event selection.
* Only `"MaxEvents"` is supported as a stopping condition.

## Comments

* It is currently very slow because it keeps trying to match the same sets of expressions over and over again. It will need to be optimized.
* Token deduplication is not implemented.
* Only one event ordering is implemented.
* It will be easy to allow using multihistory objects as inputs, however, it's not currently implemented.
* There is no rule parsing happening at all. This means the system does not even know how many tokens a rule input has (it just enumerates ***all*** subsets).
* @taliesinb, I'm now using "spacelike" -> "compatible", "timelike" -> "past" or "future", "branchlike" -> "inconsistent". So, the separations are now ordered relations. Let me know if there are any objections.
* The engine is procedural. It can probably be implemented in C++ for efficiency provided that we can callback Wolfram Kernel for matching and event instantiation.
* I did not implement self-consistency tests yet because they require time constraint and hypergraph system.

## Examples

* Create a multihistory:

```wl
In[] := multihistory = GenerateMultihistory[
  MultisetSubstitutionSystem[{a_, b_} :> {a + b}],
  <|"MaxDestroyerEvents" -> 2, "MaxEventInputs" -> 2|>,
  None,
  {"InputCount", "SortedInputExpressions", "UnsortedInputExpressions", "RuleIndex"},
  <||>] @ {3, 8, 8, 8, 2, 10, 0, 9, 7}
```

image

* Convert to a `WolframModelEvolutionObject`:

```wl
In[] := wolframModelEvolution = SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}] @ multihistory
```

image

* Produce its token-event graph:

```wl
In[] := wolframModelEvolution["ExpressionsEventsGraph", VertexLabels -> Automatic]
```

image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)

### CODE REVIEW

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 147 at r1](https://reviewable.io/reviews/maxitg/setreplace/624#-MW0mZFt4TODQYU2Rqwz:-MW0mZFt4TODQYU2Rqx-:b-zcoadi) ([raw file](https://github.com/maxitg/setreplace/blob/a2e17325a75b37c221440e1c9dbb3972bdc1317a/Kernel/MultisetSubstitutionSystemGenerator.m#L147)):*
> ```objc
>   ];
>   ScopeVariable[subsetIndex, possibleMatch, ruleIndex];
>   Do[
> ```

Is this the bottleneck?

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 53 at r1](https://reviewable.io/reviews/maxitg/setreplace/624#-MW0gJun-jLMeN0CzC89:-MW0rFWH62ltV0freayb:b-ol9l4l) ([raw file](https://github.com/maxitg/setreplace/blob/2cace8ca406fd8e2884df389cc04774bb1098cff/Kernel/MultisetSubstitutionSystemGenerator.m#L53)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`CreateDataStructure["HashSet", {{}}]`
</blockquote></details>

Nice! Done.
___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 147 at r1](https://reviewable.io/reviews/maxitg/setreplace/624#-MW0mZFt4TODQYU2Rqwz:-MW0oHM3-7qPRqHTtSUm:bb77ufg) ([raw file](https://github.com/maxitg/setreplace/blob/2cace8ca406fd8e2884df389cc04774bb1098cff/Kernel/MultisetSubstitutionSystemGenerator.m#L147)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Is this the bottleneck?
</blockquote></details>

Yes.
___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 243 at r1](https://reviewable.io/reviews/maxitg/setreplace/624#-MW0fZ3M4vOmLUVD8aEN:-MW0rLc54fip6vubAHmd:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2cace8ca406fd8e2884df389cc04774bb1098cff/Kernel/MultisetSubstitutionSystemGenerator.m#L243)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

> ```
> createDynamicArray
> ```
You could just `CreateDataStructure["DynamicArray", contents]`
</blockquote></details>

Done.

**Review by taliesinb — COMMENTED** [review]
Great! Can I suggest "inconsistent" → "incompatible"? Otherwise looking good so far.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624#-:-MWZWVSAAL3f-fDCHH0I:bt2xz6s)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 47 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWk8xAgtiSUYnhSxI:-MWZWk8xAgtiSUYnhSxJ:bjvuhba) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L47)):*
> ```objc
>   expressionDestroyerEventsCount = CreateDataStructure["DynamicArray", ConstantArray[0, Length @ init]];
>   (* destroyerChoices[eventID][expressionID] -> eventID. See libSetReplace/Event.cpp for more information. *)
>   destroyerChoices = CreateDataStructure["DynamicArray", {CreateDataStructure["HashTable"]}];
> ```

In my own experiments I found that HashTable is not actually faster than `UnorderedAssociation`. It's also a bit harder to read because of the more elaborate syntax. Although it might be easier to compile... Just a note.
___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 70 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWylICYSjhcJ5KU4T:-MWZWylICYSjhcJ5KU4U:bw9h3x6) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L70)):*
> ```objc
>     {MultisetSubstitutionSystem, 0},
>     <|"Rules" -> rules,
>       "ConclusionReason" -> conclusionReason,
> ```

Conclusion or Termination? A "conclusion" sounds quite... human?

**Review by taliesinb — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @daneelsan and @maxitg)

**Review by maxitg — COMMENTED** [review]
The problem is that incompatible should be a reverse of compatible. And compatible means spacelike, therefore, incompatible would mean timelike or branchlike.

I'm actually not so sure it's worth replacing spacelike, timelike and branchlike. I think they are good metaphors if nothing else. Any other terms I can come up with seem a lot more confusing.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624#-:-MWgGfoZBSO4b2Lsl_HC:bivq27d)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 47 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWk8xAgtiSUYnhSxI:-MWgH5mX39ncxbDaHdmI:b-8r2ruv) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L47)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

In my own experiments I found that HashTable is not actually faster than `UnorderedAssociation`. It's also a bit harder to read because of the more elaborate syntax. Although it might be easier to compile... Just a note.
</blockquote></details>

I'm going to reimplement all of this in C++ anyway (or compile with Wolfram compiler if that does not work). Is it really a good idea to use ``Data`UnorderedAssociation`` given that it's undocumented and internal whereas `"HashTable"` is both (even if the API is more elaborate)?
___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 70 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWylICYSjhcJ5KU4T:-MWgHd-H2_gxbtBUKf0b:b-2pv4vc) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L70)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Conclusion or Termination? A "conclusion" sounds quite... human?
</blockquote></details>

The problem is that `"FixedPoint"` is not a particularly good name, as it suggests that the next event evaluates the system to the same global state. It makes more sense to say the system "terminates" if there are no more matches available. But then, there is a naming conflict because "Terminated" would be only one of multiple "TerminationReason"s.

Do you have a suggestion for better naming here?

**Comment by maxitg** [comment]
I did not quite finish the tests yet. I have half of the separation matching file remaining. Also, there is no documentation yet. I will make another PR with documentation for both `GenerateMultihistory` and `MultisetSubstitutionSystem`. Otherwise, this PR is going to exceed 1000 lines.

**Comment by maxitg** [comment]
@taliesinb, could you give me an estimate of when will you need this PR for the sequence system so that I know what my deadline is to finish this?

**Comment by maxitg** [comment]
@taliesinb, tests are done. The only thing remaining is figuring out the naming for spacelike/timelike/branchlike. I think the names I came up with, compatible/past/future/inconsistent are too confusing.

**Comment by maxitg** [comment]
Well, tests are almost done. Just need to fix a few things.

**Comment by maxitg** [comment]
I have finished everything here except for documentation (which will be in a separate PR together with `GenerateMultihistory`). Also, I went back to using spacelike/timelike/branchlike for now until/unless we come up with a better name. Since these are not public, they will be easy to change at any point.

**Review by taliesinb — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 10 files at r3, 2 of 5 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 70 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWylICYSjhcJ5KU4T:-MX3BGYt0bPKSWmena0Z:b-jcz2f5) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L70)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The problem is that `"FixedPoint"` is not a particularly good name, as it suggests that the next event evaluates the system to the same global state. It makes more sense to say the system "terminates" if there are no more matches available. But then, there is a naming conflict because "Terminated" would be only one of multiple "TerminationReason"s.

Do you have a suggestion for better naming here?
</blockquote></details>

I would suggest that we use "TerminationReason", and then use the word "Complete" for there being no more matches available. But won't block if you disagree.

**Review by taliesinb — COMMENTED** [review]
I have one naming suggestion but no blockers. LGTM!

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624#-:-MX3BvE_D2GGq3gDJJAL:bkle4zg)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystemGenerator.m, line 70 at r2](https://reviewable.io/reviews/maxitg/setreplace/624#-MWZWylICYSjhcJ5KU4T:-MX3ncvFESXajTsuM9EC:bb1l8pe) ([raw file](https://github.com/maxitg/setreplace/blob/5faff82841c0797cf2e543ed7cb868c5384240a2/Kernel/MultisetSubstitutionSystemGenerator.m#L70)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

I would suggest that we use "TerminationReason", and then use the word "Complete" for there being no more matches available. But won't block if you disagree.
</blockquote></details>

I agree; that's better. Done.

**Review by taliesinb — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/624)* status: all files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

**Pull request merged**
