### PR TITLE
Multiset system: auto rule input counting

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* `MultisetSubstitutionSystem` will automatically figure out the number of inputs in some classes of rules and adjust `"MinEventInputs"` and `"MaxEventInputs"` accordingly.
* This was one of the bottlenecks in `MultisetSubstitutionSystem` performance.

## Comments

* It cannot recognize all cases (in particular there is a condition in which `Length` is used). However, it does go inside conditions in simple cases, so something like `{a_, b_} /; a < b` is recognized.
* This will be disabled in the new WL versions in case new pattern symbols appear.
* @taliesinb, can you think of a better way to do this?

## Examples

* This now works without a `"MaxEventInputs"` spec:
```wl
In[] := #["ExpressionsEventsGraph", VertexLabels -> Placed[Automatic, After]] &@
 SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}]@
  GenerateMultihistory[MultisetSubstitutionSystem[{a_, b_} /; a < b :> {a + b}], {"MaxDestroyerEvents" -> 1}, None, 
    EventOrderingFunctions[MultisetSubstitutionSystem], {}]@Range[10]
```
image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)

### CODE REVIEW

**Review by daneelsan — DISMISSED** [review]
This is cool.

```wl
In[] := Range[10] //
   GenerateMultihistory[
    MultisetSubstitutionSystem[{a_, b_, c_} /; a < b < c :> {a + b, 
       c}],
    {"MaxDestroyerEvents" -> 1},
    None,
    EventOrderingFunctions[MultisetSubstitutionSystem],
    {}] //
  
  SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}] //
 #[
   "ExpressionsEventsGraph", 
   VertexLabels -> Placed[Automatic, After]] &
```


A few comments/questions:

1) Why support `x_`, but not `x_Head`? Isn't `Verbatim[Blank[]]` more general?

2) There exists ```Internal`PatternPresentQ``` and ```Internal`PatternFreeQ```, which might remove the need of doing `Except[(banned patterns)[___]`

3) Perhaps we could support other patterns. An idea that could work is to go through each element in the list and count the min and max arguments they consume. Something like:

```wl
count[_ ? PatternFreeQ] = {1, 1};
count[Verbatim[Blank[]]] = {1, 1};
count[Verbatim[BlankSequence[]]] = {1, Infinity};
count[Verbatim[BlankNullSequence[]]] = {0, Infinity};

count[Verbatim[Pattern][_, Verbatim[Blank[]]]] = {1, 1};
count[Verbatim[Pattern][_, Verbatim[BlankSequence[]]]] = {1, Infinity};
count[Verbatim[Pattern][_, Verbatim[BlankNullSequence[]]]] = {0, 
   Infinity};

count[Verbatim[Repeated][_]] := {1, Infinity};
count[Verbatim[Repeated][_, max_Integer]] := {1, max};
count[Verbatim[Repeated][_, {min_Integer, max_Integer}]] := {min, max};
count[Verbatim[Repeated][_, {n_Integer}]] := {n, n};

count[Verbatim[RepeatedNull][_]] := {0, Infinity};
count[Verbatim[RepeatedNull][_, max_Integer]] := {0, max};
count[Verbatim[RepeatedNull][_, {min_Integer, max_Integer}]] := {min, 
   max};
count[Verbatim[RepeatedNull][_, {n_Integer}]] := {n, n};

count[Verbatim[PatternSequence][x___]] := {0, Length@{x}};

count[_] = {0, Infinity};
```
Then just add all these `{min$1, max$1} + {min$2, max$2}, $$` to get the min/max inputs.


I'm approving as this already works, and the things I commented might be addressed in a future PR.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656#-:-McNGIWaD0AKoRRxs6zc:b-ihm7ur)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @maxitg)

**Review by daneelsan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @maxitg)

**Review by maxitg — COMMENTED** [review]
`inputCountRange` now handles all pattern symbols. I also added a check to disable this optimization altogether in future WL versions (in case new pattern symbols are introduced).

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656#-:-MdTRDdZ1inY_oNPqndT:b-1mpg8o)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @maxitg)

**Review by daneelsan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystem.m, line 276 at r2](https://reviewable.io/reviews/maxitg/setreplace/656#-MeDWkBu33VGDnWBiDqm:-MeDWkBu33VGDnWBiDqn:bburxb6) ([raw file](https://github.com/maxitg/setreplace/blob/e656dd40ce1a36293765645f701c8df8f5361384/Kernel/MultisetSubstitutionSystem.m#L276)):*
> ```
> {sequencePatternLengthRange[p], Infinity}
> ```
Not sure if this is a bug or intended. Other values of `sequencePatternLengthRange` return a pair of the form `{min_Integer, max_Integer}`. This first definition actually returns `{{min1_, max1_}, Infinity}.` Can't come up with bug examples:
```wl
In[]:= inputCountRange[a : {_Integer ..} :> {Total[a]}]
Out[]= {{1, 1}, \[Infinity]}
```

**Review by daneelsan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystem.m, line 276 at r2](https://reviewable.io/reviews/maxitg/setreplace/656#-MeDWkBu33VGDnWBiDqm:-MeDXnRID0kz197zbXuQ:b6eyzz) ([raw file](https://github.com/maxitg/setreplace/blob/e656dd40ce1a36293765645f701c8df8f5361384/Kernel/MultisetSubstitutionSystem.m#L276)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

> ```
> {sequencePatternLengthRange[p], Infinity}
> ```
Not sure if this is a bug or intended. Other values of `sequencePatternLengthRange` return a pair of the form `{min_Integer, max_Integer}`. This first definition actually returns `{{min1_, max1_}, Infinity}.` Can't come up with bug examples:
```wl
In[]:= inputCountRange[a : {_Integer ..} :> {Total[a]}]
Out[]= {{1, 1}, \[Infinity]}
```
</blockquote></details>

`Min` still works btw:
```wl
In[]:= Min[{{1, 2}, 3, 4}]
Out[]= 1
```

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @daneelsan and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystem.m, line 276 at r2](https://reviewable.io/reviews/maxitg/setreplace/656#-MeDWkBu33VGDnWBiDqm:-MeKrPL0Ejs7gOivQeNL:b-tsxqi8) ([raw file](https://github.com/maxitg/setreplace/blob/e656dd40ce1a36293765645f701c8df8f5361384/Kernel/MultisetSubstitutionSystem.m#L276)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`Min` still works btw:
```wl
In[]:= Min[{{1, 2}, 3, 4}]
Out[]= 1
```
</blockquote></details>

It probably gets sorted out automatically, but yes, that was not intentional.

**Review by daneelsan — APPROVED** [review]
Looks good to me, can't seem to find weeds! :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656#-:-MeMhsWh1w3tfh_6AWzi:bil8ch9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystem.m, line 292 at r2](https://reviewable.io/reviews/maxitg/setreplace/656#-MeDcWTGEFivOZpEkOrC:-MeDcWTGEFivOZpEkOrD:b-dmf8om) ([raw file](https://github.com/maxitg/setreplace/blob/e656dd40ce1a36293765645f701c8df8f5361384/Kernel/MultisetSubstitutionSystem.m#L292)):*
> ```objc
> sequencePatternLengthRange[_Except] := {1, 1};
> 
> sequencePatternLengthRange[Verbatim[Longest][p_]] := sequencePatternLengthRange[p];
> ```

These are ignored because

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/656)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Kernel/MultisetSubstitutionSystem.m, line 292 at r2](https://reviewable.io/reviews/maxitg/setreplace/656#-MeDcWTGEFivOZpEkOrC:-MeMkKDy-Ea9idxji4a2:bplngtd) ([raw file](https://github.com/maxitg/setreplace/blob/e656dd40ce1a36293765645f701c8df8f5361384/Kernel/MultisetSubstitutionSystem.m#L292)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

These are ignored because
</blockquote></details>

They are not ignored:
```wl
In[] := #["ExpressionsEventsGraph", VertexLabels -> Placed[Automatic, After]] &@
   SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}]@
    GenerateMultihistory[
      MultisetSubstitutionSystem[#], {"MaxGeneration" -> 1, "MinEventInputs" -> 4, "MaxDestroyerEvents" -> 1}, None, 
      EventOrderingFunctions[MultisetSubstitutionSystem], {}]@{1, 2, 3, 4} & /@ {{a__, b__} :> {Plus[a], 
    Plus[b]}, {Longest[a__], b__} :> {Plus[a], Plus[b]}}
```


However, they cannot change the lengths as far as I understand.

**Pull request merged**
