### PR TITLE
Documentation for GenerateMultihistory and MultisetSubstitutionSystem

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Adds documentation for `GenerateMultihistory`, `MultisetSubstitutionSystem` and the directory structure around them (Generators, Properties, Systems, and Types).

## Comments

* Some of this documentation is running slightly ahead by referencing non-existing functions. The links to them can be added once the functions are implemented.
* Most code blocks are overly long because (1) they use `GenerateMultihistory` instead of more compact generators that are not yet implemented and (2) they have to convert to `WolframModelEvolutionObject` to make token-event graphs. The code should look much nicer once these are implemented.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)

### CODE REVIEW

**Review by daneelsan — COMMENTED** [review]
I don't remember if we discussed this but is there a reason we use `SetReplace*` instead of `Multihistory*`?
E.g. `SetReplaceTypeConvert` or `$SetReplaceProperties` instead of `MultihistoryTypeConvert` and `$MultihistoryProperties`, respectively.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636#-:-MXF1rak9K3NQhHNcu2M:bmeaxox)* status: 0 of 31 files reviewed, 4 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 41 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEgX6t2OIgl_ueDra8:-MXEgX6t2OIgl_ueDra9:b-lqnqwb) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L41)):*
> ```Markdown
> 
> The importance of that order depends on the system, the rules, and the parameters of the evaluation. For example, in the
> example below, full multihistory is generated up to generation 1. In this case, the same multihistory is generated
> ```

"...in the example `above`", I think.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 43 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEhmnb6Teso1Cdnk8f:-MXEhmnb6Teso1Cdnk8g:bxkoj25) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L43)):*
> ```Markdown
> example below, full multihistory is generated up to generation 1. In this case, the same multihistory is generated
> regardless of the event ordering, so, the event ordering does not matter all that much. For this reason, there is no
> argument for the event ordering `GenerateFullMultihistory`.
> ```

What do you mean by "no argument for the event ordering"?
Also, should it be `GenerateMultihistory` instead of `GenerateFullMultihistory`?
___
*[Documentation/Generators/EventOrderingFunctions.md, line 107 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEnwCDB-aPh8XtVB-Z:-MXEnwCDB-aPh8XtVB-_:bx0ywve) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L107)):*
> ```Markdown
> ambiguity).
> 
> In other words, this ordering function attempts to match the oldest token possible. And if multiple matches remain after
> ```

I like this explanation.
___
*[Documentation/Generators/README.md, line 18 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXF1QI-2NzO452czf5S:-MXF1QI00e8xIHWmf83Z:bfcipy) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/README.md#L18)):*
> ```Markdown
> `system` specifies the [computational system](/Documentation/Systems/README.md) to evaluate.
> 
> `eventSelectionSpec`
> ```

Is this planned to be filled, or not yet?

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 0 of 29 files reviewed, 4 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Documentation/Generators/README.md, line 18 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXF1QI-2NzO452czf5S:-MXF9QBo5_hjckJ5dbY4:bb9pihc) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/README.md#L18)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Is this planned to be filled, or not yet?
</blockquote></details>

Ignore this, I just realized this is a draft.

**Review by taliesinb — COMMENTED** [review]
I think this documentation is a good start!

> Reviewed 29 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636#-:-MXgcWAm2fLLfW6WeFPN:b-h1zf1x)* status: all files reviewed, 4 unresolved discussions (waiting on @maxitg)

**Review by taliesinb — COMMENTED** [review]
> Reviewed 2 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: all files reviewed, 4 unresolved discussions (waiting on @maxitg)

**Review by maxitg — COMMENTED** [review]
@daneelsan, because the type system is now more general than just `Multihistory`. I.e., it might be used for other things in the future, and it already supports arbitrary heads.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636#-:-MYH54rvAIlOHtz1hLcy:b-6g1g81)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 41 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEgX6t2OIgl_ueDra8:-MYMGagN8BdDeZboO-uV:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L41)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"...in the example `above`", I think.
</blockquote></details>

Done.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 43 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEhmnb6Teso1Cdnk8f:-MYH5SbOB90iG3RapSz6:b-slxq3w) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L43)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

What do you mean by "no argument for the event ordering"?
Also, should it be `GenerateMultihistory` instead of `GenerateFullMultihistory`?
</blockquote></details>

No, `GenerateFullMultihistory` will be the one that accepts only the number of generations and produces the full multihistory, so there is no way to limit the number of events, and no need to specify the ordering functions.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 43 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEhmnb6Teso1Cdnk8f:-MYMI45a7ZAFGyaD8Qog:b360n12) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L43)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

No, `GenerateFullMultihistory` will be the one that accepts only the number of generations and produces the full multihistory, so there is no way to limit the number of events, and no need to specify the ordering functions.
</blockquote></details>

I meant that I don't see `GenerateFullMultihistory` being used anywhere in this page.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 43 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEhmnb6Teso1Cdnk8f:-MYMIQ8LBMfMecxK7zqb:bvkumyh) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L43)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I meant that I don't see `GenerateFullMultihistory` being used anywhere in this page.
</blockquote></details>

That's because it's not implemented yet. `GenerateFullMultihistory` will link to its page once it exists.

**Comment by maxitg** [comment]
This is now ready for review.

**Review by daneelsan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 37 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 13 of 48 files reviewed, 12 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 107 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEnwCDB-aPh8XtVB-Z:-MZt1WFS6iYdCr6XkRHL:b4sw3nh) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L107)):*
> ```
> And if multiple matches remain after that it attempts to match the oldest of the remaining tokens, etc.
> ```
"And if multiple matches remain, it attempts to match the oldest of the remaining tokens, etc." might be simpler.

On a related note: Is "match" the correct term here? As I understood it, the matches have already happened, what is missing is converting does matches into events and deleting them (the matches) from the matcher.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsx9Em9HDB_puR5YJa:-MZsx9Em9HDB_puR5YJb:bahukro) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L3)):*
> ```Markdown
> # Event Ordering Functions
> 
> Multiple matches are sometimes possible to the same state of a computational system. For example, in the system below
> ```

"Multiple matches to the same state of a computational system are sometimes possible." sounds better.

Also: "For example, the system below can match any pair of numbers, ..."
___
*[Documentation/Generators/EventOrderingFunctions.md, line 4 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsxJ1sEyqZ8gI16ZjX:-MZsxJ1sEyqZ8gI16ZjY:b-u8mckh) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L4)):*
> ```Markdown
> 
> Multiple matches are sometimes possible to the same state of a computational system. For example, in the system below
> one can match any pair of numbers, many of which overlapping:
> ```

"...many of which...":
   1) "overlap:"
   2) "are overlapping:" (which sounds right, but I'm unsure if it's correct)
___
*[Documentation/Generators/EventOrderingFunctions.md, line 27 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsymNq5XPFH3x8ohrN:-MZsymNq5XPFH3x8ohrO:b-w94zdw) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L27)):*
> ```Markdown
> 
> However, if we evaluate a single history instead, we can get different histories for different orders (different orders
> are made here by rearranging the order of the init as
> ```

"... by rearranging the order of the initial state, as..."
___
*[Documentation/Generators/EventOrderingFunctions.md, line 44 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszHLU0XEystGMz32o:-MZszHLU0XEystGMz32p:bguj82j) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L44)):*
> ```Markdown
> 
> 
> This system, however, is [confluent](https://en.wikipedia.org/wiki/Confluence_(abstract_rewriting)). So, the final state
> ```

Maybe link to the research note here?
___
*[Documentation/Generators/EventOrderingFunctions.md, line 47 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszWyN57rltWbppSxW:-MZszWyN57rltWbppSxX:bg979vj) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L47)):*
> ```Markdown
> will always be the same even if the histories are different, assuming the system is evaluated to completion.
> 
> However, it is not the case for all systems. For example, see what happens if we change `+` to `-`:
> ```

"However, this is not the case for all systems".
___
*[Documentation/Generators/EventOrderingFunctions.md, line 77 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszyduDA0fGFvowDDr:-MZszyduDA0fGFvowDDs:b228yug) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L77)):*
> ```Markdown
> the second criterion is used, etc.
> 
> Note that in some cases, systems can impose additional restrictions on which combinations of ordering functions can be
> ```

What does this mean?
___
*[Documentation/Generators/EventOrderingFunctions.md, line 84 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt-CP99QuLHbzdLEUr:-MZt-CP99QuLHbzdLEUs:b-vbonmi) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L84)):*
> ```Markdown
> As few tokens as possible will be matched. This is particularly useful for systems such as
> [`MultisetSubstitutionSystem`](/Documentation/Systems/MultisetSubstitutionSystem.md) where a single rule can match
> different token counts.
> ```

"... where a single rule can match multiple states with different token counts." might be clearer as the rule doesn't match "token counts".
I'm unsure if "state" is the correct term, though.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 97 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt0yEgDorUeLlZlkIn:-MZt0yEgDorUeLlZlkIo:b-ne8mp4) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L97)):*
> ```
> If one of the sorted index lists is a prefix of another, they are considered equal by this ordering function.
> ```
So `{3, 2, 1}` and `{3, 2, 1, 4}` would need to be disambiguated with "InputCount", as `{1, 2, 3}` is a "prefix" of the second list, right?
___
*[Documentation/Generators/EventOrderingFunctions.md, line 121 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt4XjW1XPDJ1mGCZB_:-MZt4XjW1XPDJ1mGCZBa:b-e6l9kr) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L121)):*
> ```Markdown
> ## RuleIndex
> 
> This function attempts to use a rule with the smallest index for multi-rule systems. Only if there are no matches for
> ```

Where index corresponds to its position in `{rule1_, rule2_, rule3_}`?
___
*[Documentation/Generators/EventOrderingFunctions.md, line 136 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt5HP6-RdggjBOn64E:-MZt5HP7CFuAvxcQ8Vlz:b-f3tn0o) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L136)):*
> ```Markdown
> order is the same as in [`ReplaceList`](https://reference.wolfram.com/language/ref/ReplaceList.html).
> 
> If this ordering is used first, the system only does a single instantiation for each sequence of tokens unless there are
> ```

First as in `{"InstantiationIndex", "TokenCount"}`?
Why would it do a single instantiation for each sequence of tokens in that case?

**Review by daneelsan — CHANGES_REQUESTED** [review]
> Reviewed 22 of 37 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 35 of 48 files reviewed, 15 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Documentation/Generators/EventSelectionParameters.md, line 57 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtB9eEA3I5y2bTS6ef:-MZtB9eF63EJCoiifSne:be6jtwn) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventSelectionParameters.md#L57)):*
> ```Markdown
> Since `"MaxGeneration"` is a selection parameter rather than a [stopping condition](StoppingConditionParameters.md), it
> will continue evaluation even after encountering matches exceeding the generations constraint, which might also result
> in a different [event ordering](EventOrderingFunctions.md) than if using, e.g.,
> ```

I don't get "... might also result in a different event ordering than if using ... "MaxEvents""
___
*[Documentation/Generators/GenerateMultihistory.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtCXIZ4PqHHFP3CNX_:-MZtCXI_AwfWNV_o9IHJ:b-kq4chq) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/GenerateMultihistory.md#L3)):*
> ```
> **`GenerateMultihistory`** is the most verbose and configurable generator.
> ```
Haha
___
*[Documentation/Generators/README.md, line 12 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtDBgt5KGjKP2MdmcM:-MZtDBgt5KGjKP2MdmcN:b2bfmqo) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/README.md#L12)):*
> ```Markdown
> same tokens and keeping events and tokens instead of states in
> [`Multihistory`](/Documentation/Types/Multihistory/README.md) objects. We can reconstruct the states from that
> information afterwords.
> ```

afterwards

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636)* status: 33 of 48 files reviewed, 15 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 107 at r1](https://reviewable.io/reviews/maxitg/setreplace/636#-MXEnwCDB-aPh8XtVB-Z:-MZtbhFX85oKo2cSXwXg:b-4onyu1) ([raw file](https://github.com/maxitg/setreplace/blob/fa09132e1b99561a8697ab398eb53f0478b578ec/Documentation/Generators/EventOrderingFunctions.md#L107)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

> ```
> And if multiple matches remain after that it attempts to match the oldest of the remaining tokens, etc.
> ```
"And if multiple matches remain, it attempts to match the oldest of the remaining tokens, etc." might be simpler.

On a related note: Is "match" the correct term here? As I understood it, the matches have already happened, what is missing is converting does matches into events and deleting them (the matches) from the matcher.
</blockquote></details>

Fair point. I changed `match` to `use`.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsx9Em9HDB_puR5YJa:-MZt8waN2KLZtZytq_Tz:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L3)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"Multiple matches to the same state of a computational system are sometimes possible." sounds better.

Also: "For example, the system below can match any pair of numbers, ..."
</blockquote></details>

Done.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 4 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsxJ1sEyqZ8gI16ZjX:-MZt8x9v6x1mKsllpwjG:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L4)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"...many of which...":
   1) "overlap:"
   2) "are overlapping:" (which sounds right, but I'm unsure if it's correct)
</blockquote></details>

Done.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 27 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZsymNq5XPFH3x8ohrN:-MZtZjwKAZxzuuuRw1Am:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L27)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"... by rearranging the order of the initial state, as..."
</blockquote></details>

Done.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 44 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszHLU0XEystGMz32o:-MZtZre30u6ow2cbmBMF:bl5uh77) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L44)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Maybe link to the research note here?
</blockquote></details>

I'm not sure it's relevant here. The research note compares it to causal invariance, and causal invariance has nothing to do with this. I think Wikipedia is more useful for someone who does not know what confluence is.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 47 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszWyN57rltWbppSxW:-MZt_XSu5WWDc-qZQxhv:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L47)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"However, this is not the case for all systems".
</blockquote></details>

Done.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 77 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZszyduDA0fGFvowDDr:-MZta55kDoOlSJgKa0PM:b-7lmi1h) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L77)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

What does this mean?
</blockquote></details>

This is a reference to, e.g., `MultisetSubstitutionSystem` not supporting arbitrary orders of ordering functions at the moment. But I just removed this since it's going to be fixed by release.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 84 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt-CP99QuLHbzdLEUr:-MZtab4UDTGITGmv9VMA:b-ccgvlt) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L84)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

"... where a single rule can match multiple states with different token counts." might be clearer as the rule doesn't match "token counts".
I'm unsure if "state" is the correct term, though.
</blockquote></details>

No, I don't think "state" is the correct term, as it implies complete states. I think "input" is better.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 97 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt0yEgDorUeLlZlkIn:-MZtb7xvBzzNrHHugeRX:b-l2l2eg) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L97)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

> ```
> If one of the sorted index lists is a prefix of another, they are considered equal by this ordering function.
> ```
So `{3, 2, 1}` and `{3, 2, 1, 4}` would need to be disambiguated with "InputCount", as `{1, 2, 3}` is a "prefix" of the second list, right?
</blockquote></details>

Yes. I think it's a good idea as it gives more power to users. I added your example to the text.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 121 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt4XjW1XPDJ1mGCZB_:-MZtcVFC6vju4mUIzcgM:b-vjbi69) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L121)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Where index corresponds to its position in `{rule1_, rule2_, rule3_}`?
</blockquote></details>

Yes. I changed the description to refer to the "rule" argument. Let me know if it needs further clarification.
___
*[Documentation/Generators/EventOrderingFunctions.md, line 136 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt5HP6-RdggjBOn64E:-MZtcmiCC3u8ho2bMqbM:bir3ukw) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L136)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

First as in `{"InstantiationIndex", "TokenCount"}`?
Why would it do a single instantiation for each sequence of tokens in that case?
</blockquote></details>

Because it would sort by the `"InstantiationIndex"` first, so it will only get to 2 after all 1's are instantiated.
___
*[Documentation/Generators/EventSelectionParameters.md, line 57 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtB9eEA3I5y2bTS6ef:-MZtfmV0BEOH1UMCF1P2:biftbte) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventSelectionParameters.md#L57)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I don't get "... might also result in a different event ordering than if using ... "MaxEvents""
</blockquote></details>

Well, in the two examples below, the first event is the same, but the next one is different based on whether `"MaxGeneration"` is set or not.
___
*[Documentation/Generators/GenerateMultihistory.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtCXIZ4PqHHFP3CNX_:-MZtd9W6BU1P-Wbfi8GL:bcpxn47) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/GenerateMultihistory.md#L3)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

> ```
> **`GenerateMultihistory`** is the most verbose and configurable generator.
> ```
Haha
</blockquote></details>

Yes, verbosity is a bit of a problem, as it's a bit annoying to use `GenerateMultihistory` for interactive stuff in the front end. Hopefully, other generators and the `"Random"` ordering function will make things better.
___
*[Documentation/Generators/README.md, line 12 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZtDBgt5KGjKP2MdmcM:-MZtd2nr9QcGMVVQBfCe:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/README.md#L12)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

afterwards
</blockquote></details>

Done.

**Review by daneelsan — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/636#-:-MZx6gmN2UMZFflUfd2D:b-uwkowd)* status: 33 of 48 files reviewed, 1 unresolved discussion (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[Documentation/Generators/EventOrderingFunctions.md, line 121 at r5](https://reviewable.io/reviews/maxitg/setreplace/636#-MZt4XjW1XPDJ1mGCZB_:-MZx6ESWAqN_m20HTod_:b9j9n43) ([raw file](https://github.com/maxitg/setreplace/blob/e761d4c20427629ff8eb94e02f14312f3b4ef94e/Documentation/Generators/EventOrderingFunctions.md#L121)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Yes. I changed the description to refer to the "rule" argument. Let me know if it needs further clarification.
</blockquote></details>

Looks good to me.

**Pull request merged**
