### PR TITLE
C++ tests in CI

### LINKED ISSUE #430: Add C++ tests to CI
### The problem
Is your feature request related to a problem? Please describe. Ex. I'm always frustrated when [...]

### PR DESCRIPTION
**Pull request by maxitg**
## Changes
* Closes #430.
* Splits CI workflow into two parallel jobs: one for *libSetReplace*, one for the Wolfram Language.
* The previous workflow is now in the `wolfram-language` job. In addition, that job now builds *libSetReplace* using CMake with LibraryLink support.
* Linter is moved to the `cpp` job since it only currently covers C++ code.

## Comments
* The new job (`cpp`) is based on a much simpler [image](https://hub.docker.com/repository/docker/maxitg/set-replace-cpp-ci) which is only 200 MB compared to > 2 GB of the Wolfram Language image:
```dockerfile
# maxitg/set-replace-cpp-ci
FROM ubuntu

LABEL version = "1.0"
LABEL description = "Docker image for SetReplace C++ CI."

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update -yq && \
    apt-get install -yq g++ git cmake clang-format python3-pip && \
    apt-get clean -yq && \
    apt-get autoremove -yq

RUN pip3 install cpplint
```
* `wolfram-language` is updated as well (the first time it's built the last line should be commented out, one then needs to run the image, activate Mathematica, obtain the mathpass file, and then rebuild the image using that new mathpass file):
```dockerfile
# maxitg/set-replace-wl-ci:12.1.1
FROM ubuntu

LABEL version = "1.3"
LABEL description = "Docker image for SetReplace Wolfram Language CI."

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# avahi-daemon causes MathID to be stable across different hosts
# libncurses5 sudo xz-utils libfontconfig1 libgl1-mesa-glx libasound2 are needed for Mathematica
# uuid-dev is needed for FindMathematica (and the CMake build)
RUN apt-get update -yq && \
    apt-get install -yq g++ git cmake wget \
                        avahi-daemon \
                        libncurses5 sudo xz-utils libfontconfig1 libgl1-mesa-glx libasound2 \
                        uuid-dev && \
    apt-get clean -yq && \
    apt-get autoremove -yq

RUN wget http://path-to-mathematica/M-LINUX-L-12.1.1.sh -O WD.sh && \
    sudo bash WD.sh -- -auto -verbose && \
    rm WD.sh && \
    rm -rf /usr/local/Wolfram/Mathematica/12.1/Documentation

COPY mathpass /root/.Mathematica/Licensing/mathpass

RUN wolframscript -configure WOLFRAMSCRIPT_KERNELPATH=/usr/local/Wolfram/Mathematica/12.1/Executables/WolframKernel
```

## Examples
* Check the new CI running for this branch.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/446)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/446)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[.circleci/config.yml, line 62 at r1](https://reviewable.io/reviews/maxitg/setreplace/446#-MJN1X1W4y9OmzKcntBT:-MJN1X1W4y9OmzKcntBU:b-m4acra) ([raw file](https://github.com/maxitg/setreplace/blob/e4646c3aee3c35b8fc7641b1c6bb56a7a1744ccb/.circleci/config.yml#L62)):*
> ```YAML
>           name: Test
>           command: |
>             for testBinary in $(find libSetReplace/test -type f -executable -print)
> ```

This should probably be put in a separate shell script so that all cpp tests can be run automatically by developers.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/446)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @taliesinb)

___
*[.circleci/config.yml, line 62 at r1](https://reviewable.io/reviews/maxitg/setreplace/446#-MJN1X1W4y9OmzKcntBT:-MJNsuhq7DAUIs07hjhY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/36083fb74ee4956a2c9dd1da5836112ab39f6d1d/.circleci/config.yml#L62)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

This should probably be put in a separate shell script so that all cpp tests can be run automatically by developers.
</blockquote></details>

Done.

**Comment by maxitg** [comment]
I'm still working on the WL Docker image by the way, which is why the `wolfram-language` job is failing.

**Comment by taliesinb** [comment]
I can verify that all tests pass on my machine.

**Review by taliesinb — APPROVED** [review]

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/446)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[libSetReplaceTest.sh, line 1 at r4](https://reviewable.io/reviews/maxitg/setreplace/446#-MJY8YKT5yGG11YZ6h8L:-MJY8YKT5yGG11YZ6h8M:bno2bs4) ([raw file](https://github.com/maxitg/setreplace/blob/04ba80a14b6f8cccc027bff69f701835e6b62613/libSetReplaceTest.sh#L1)):*
> ```Shell
> if [ $(uname) = "Darwin" ]
> ```

Add shebang

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/446)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[libSetReplaceTest.sh, line 1 at r4](https://reviewable.io/reviews/maxitg/setreplace/446#-MJY8YKT5yGG11YZ6h8L:-MJ_UVB30TYO697t4T_7:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/04ba80a14b6f8cccc027bff69f701835e6b62613/libSetReplaceTest.sh#L1)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Add shebang
</blockquote></details>

Done.

**Comment by maxitg** [comment]
Finally, it works! Both jobs are now operational.

**Pull request merged**
