### PR TITLE
Bash Formatter/Linter

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Adds bash formatter (shfmt)
* Adds bash linter (shellcheck)

## Examples
```
$ ./lint.sh 

In ./lint.sh line 47:
    shfmt -w -i 2 $file
                  ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    shfmt -w -i 2 "$file"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566)

### CODE REVIEW

**Comment by maxitg** [comment]
Note the Lint step here: https://app.circleci.com/pipelines/github/maxitg/SetReplace/1451/workflows/70ffad70-8856-49aa-9894-b9c0e4b2b341/jobs/2113

**Comment by maxitg** [comment]
Also, see #567.

**Review by maxitg — CHANGES_REQUESTED** [review]
Very nice!

> Reviewed 2 of 8 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566#-:-MOHkM_97QZrAfrbpHDX:b-j7qk9t)* status: all files reviewed, 5 unresolved discussions (waiting on @aokellermann)

___
*[libSetReplaceTest.sh, line 36 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHlb20AQqrpiEnK6_L:-MOHlb20AQqrpiEnK6_M:bc5k4ln) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/libSetReplaceTest.sh#L36)):*
> ```Shell
>   testBasename=$(basename "$testBinary")
>   echo "$testBasename..."
>   if ! eval "$testBinary" --gtest_output=xml:$libSetReplaceTestsDir/"$testBasename".xml; then
> ```

I'm wondering why it did not suggest to quote `$libSetReplaceTestsDir` as well? Is it because it can see its value? In any case, it seems safer to quote it anyway.
___
*[lint.sh, line 6 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHhZTD6vgmSeMKrGpG:-MOHhZTD6vgmSeMKrGpH:bmy07tg) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/lint.sh#L6)):*
> ```Shell
> sourceFiles=$(find libSetReplace -type f -name "*pp")
> # Some bash files don't use .sh extension, so find by shebang
> bashFiles=$(grep -rIzl '^#![[:blank:]]*/usr/bin/env bash' --exclude-dir=*build* .)
> ```

Why do we need `-z`? BSD grep (which is the default one on macOS) does not have a `-z` option, and it does seem to work without it.
___
*[lint.sh, line 6 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHhfBgABPU6Zt3o8u4:-MOHhfBgABPU6Zt3o8u5:b-wd1zyy) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/lint.sh#L6)):*
> ```Shell
> sourceFiles=$(find libSetReplace -type f -name "*pp")
> # Some bash files don't use .sh extension, so find by shebang
> bashFiles=$(grep -rIzl '^#![[:blank:]]*/usr/bin/env bash' --exclude-dir=*build* .)
> ```

Also, `--exclude-dir=*.git*`, as it contains the installed git hooks.
___
*[.circleci/config.yml, line 65 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHoV1W5SXh7MpM53by:-MOHoV1W5SXh7MpM53bz:b-gdduif) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/.circleci/config.yml#L65)):*
> ```YAML
>             apk update
>             apk add bash git g++ make cmake clang py-pip shellcheck shfmt
>             apk add --upgrade grep
> ```

I don't believe `grep` package is installed there at all. The one you get by default is part of BusyBox:

```
$ grep --help
BusyBox v1.31.1 () multi-call binary.
```
___
*[scripts/buildLibraryResources.sh, line 13 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHupDtBYu_z10x1_03:-MOHupDtBYu_z10x1_04:bvlflyj) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/scripts/buildLibraryResources.sh#L13)):*
> ```Shell
> if command -v shasum &>/dev/null; then
>   echo "Using SHA tool: $(which shasum)"
>   sha="$(
> ```

Can you explain what's wrong with the previous version?

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @maxitg)

___
*[libSetReplaceTest.sh, line 36 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHlb20AQqrpiEnK6_L:-MOI-nfZAlbNch98c7qG:brqmz5g) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/libSetReplaceTest.sh#L36)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm wondering why it did not suggest to quote `$libSetReplaceTestsDir` as well? Is it because it can see its value? In any case, it seems safer to quote it anyway.
</blockquote></details>

I have no idea.
___
*[lint.sh, line 6 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHhZTD6vgmSeMKrGpG:-MOI0PZXAAzCgOuJK8A7:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/lint.sh#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Why do we need `-z`? BSD grep (which is the default one on macOS) does not have a `-z` option, and it does seem to work without it.
</blockquote></details>

Done.
___
*[lint.sh, line 6 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHhfBgABPU6Zt3o8u4:-MOI0Q996V5_k9YeHGKA:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/lint.sh#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Also, `--exclude-dir=*.git*`, as it contains the installed git hooks.
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 65 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHoV1W5SXh7MpM53by:-MOI0TiJ6xhROyeBj8q8:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/.circleci/config.yml#L65)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't believe `grep` package is installed there at all. The one you get by default is part of BusyBox:

```
$ grep --help
BusyBox v1.31.1 () multi-call binary.
```
</blockquote></details>

Done.
___
*[scripts/buildLibraryResources.sh, line 13 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHupDtBYu_z10x1_03:-MOI5OYU-iXLEydvmnwq:b-fj2iax) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/scripts/buildLibraryResources.sh#L13)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Can you explain what's wrong with the previous version?
</blockquote></details>

Shellcheck really doesn't like [globbing and word splitting](https://github.com/koalaman/shellcheck/wiki/SC2086). They recommend using loops instead.

**Review by maxitg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @aokellermann and @maxitg)

___
*[.circleci/config.yml, line 65 at r2](https://reviewable.io/reviews/maxitg/setreplace/566#-MOHoV1W5SXh7MpM53by:-MOI69nO7FOSDjkFiLAX:boaeby4) ([raw file](https://github.com/maxitg/setreplace/blob/5e6ec23181836603d1aab2deeee6a7995d9d127a/.circleci/config.yml#L65)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You do need to install grep though. The one in BusyBox is quite limited.

**Review by maxitg — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/566#-:-MOI6k8pBaKjrOjhMuww:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
