### PR TITLE
New flags and QoL improvements in test script

### PR DESCRIPTION
**Pull request by taliesinb**
This change introduces the following improvements to the `test.wls` script:

* `--load-installed-paclet` / `-lip` flag to load the installed paclet rather than loading the local `Kernel/init.m`, the latter now being the default behavior.
* `--disable-parallelization` / `-dp` flag to disable parallelization for short-lived tests, which can speed things up quite a bit.
* Report syntax errors in `.wlt` files where they occur.
* Add a "Parallel" test group option that can be used to explicitly disallow parallel evaluation of a particular group.
* Automatically call `UsingFrontEnd[...]` for tests in which the frontend is used. 
* Introduce a 'cleanup' property that contains code to run to e.g. delete files that tests might have created.
* Print the source file that is being loaded to load SetReplace.
* Add exit_status.txt to .gitignore.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526)

### CODE REVIEW

**Comment by taliesinb** [comment]
@maxitg , I've made sure that if the RequiresFrontEnd option is *not* explicitly set, then the default will be True for existing test files that use the frontend through graphicsQ etc (it is a no-op to nest UsingFrontEnd, of course).

Also, this PR switches the default for ./test.wls from loading the installed paclet (e.g. requiring you to call ./install.wls first), to loading "Kernel/init.m", e.g. the local developer's codebase. This PR therefore depends on another PR which will switch to "in-place builds" that remove the need for the "/Build" subdirectory, so please don't evaluate this PR until that PR has landed! 

Also, if desired I can add the functionality that will automatically fail the test suite if the C++ code doesn't match the built hash.

Now, this change in which file is loaded *will* break the CI testing system, we can discuss what to do about that. I see three options:
1. make ./test.wls use the behavior that is most natural and convenient for developers, which is to have "./test.wls" load the local tree, and change the CI testing system so that it calls ./test.wls with the special "--load-installed-paclet" flag to have it load the built paclet.
2. keep the current behavior, and have developers have to call "./test.wls --load-local-codebase" explicitly to load the local tree instead of the built paclet.
3. check some AntProperty to figure out if we are being run on the CI servers, and pick the right default behavior that way.

I prefer 1, since it the behavior that will be most common by far.

**Comment by maxitg** [comment]
@taliesinb, I agree with 1, however, `./build.wls && ./install.wls && ./test.wls` (and even `./build.wls && ./test.wls`) should still cause the tests to pass (it would not be user friendly otherwise), which means CI should not fail (although we do want to change it to use `-lip` to make sure the paclet is built correctly).

It's actually very easy to modify what the CI does by changing [this file](https://github.com/maxitg/SetReplace/blob/master/.circleci/config.yml) and the scripts used therein (it has nothing to do with Ants, it's just using ordinary build/install/test scripts).

**Review by maxitg — CHANGES_REQUESTED** [review]
Very nice! Would be nice to have some examples in the PR description by the way. Maybe also describe the new flags in `CONTRIBUTING.md`, otherwise, they are undiscoverable without looking at the code.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526#-:-MMs77WnET4an1qc5OJY:bqo4s53)* status: all files reviewed, 4 unresolved discussions (waiting on @taliesinb)

___
*[test.wls, line 29 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs53jm9vbpQw6NloL9:-MMs53jm9vbpQw6NloLA:b-v7t56e) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L29)):*
> ```
> 
> Print["Loading SetReplace from ", $yellowColor, FindFile[$localSetReplaceEntryPoint], $endColor];
> Get[$localSetReplaceEntryPoint];
> ```

Should we `Exit[1]` here as well if there are syntax errors/messages here as well as we do for syntax errors in tests?
___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMs4KPXD1h15k3bw38_:bd5txcf) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
> ```
>   If[FailureQ[exprs], 
>     WriteString["stdout", $redColor <> "There were syntax errors in \"" <> file <> "\"" <> $endColor <> "\n"];
>     Scan[printFileLineError, FindSyntaxErrors[file]]; 
> ```

It produces weird results for me. I added a random dot into `HypergraphToGraph.wlt`, and I'm getting this, which is not very helpful after the first `ToExpression::sntx` message:

```
✗ ./test.wls HypergraphToGraph
Loading SetReplace from /private/var/folders/f_/klrm3n7d4_989wy4dxx9_l9c0000gn/T/SetReplace/Build/Kernel/init.m

Syntax::com: Warning: comma encountered with no adjacent expression. The expression will be treated as Null. .

There were syntax errors in "/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt"

ToExpression::sntx: Invalid syntax in or before "getVertexEdgeList @ HypergraphToGraph[{{x, x, y, z}, {z,. w}}, "StructurePreserving"],".
                                                                                                          ^
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:3	MismatchedParenthesis
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:8	MismatchedParenthesis
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:17	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:22	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:27	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:33	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:39	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:45	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:51	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:56	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:61	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:66	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:71	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:76	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:81	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:86	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:92	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:97	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:102	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:107	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:112	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:117	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:125	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:133	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:139	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:144	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:151	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:161	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:177	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:194	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:197	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:234	SyntaxError
```
___
*[test.wls, line 100 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs5hsxB7mHksSxxANL:-MMs5hsxB7mHksSxxANM:blvgdvm) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L100)):*
> ```
> 
> $results = Association[KeyValueMap[Function[{testGroupName, testGroup}, Module[{
>     testList, testResults, testReport, options, parallelQ, requiresFrontEnd, probablyRequiresFrontEnd, runInit, failedTests},
> ```

Nit: Keep lines below 120 characters.
___
*[test.wls, line 117 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs6VOo41Rt8uXmSnC-:-MMs6VOo41Rt8uXmSnC0:b-z8ezqm) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L117)):*
> ```
>   test *)
>   If[requiresFrontEnd, UsingFrontEnd, Identity][
> ```

I don't think we should be doing non-standard indentation here. I understand that this is in a way similar to `namespace { ... }`, but I think this case is too rare and it just makes code harder to understand.

**Review by taliesinb — COMMENTED** [review]
@maxitg I've added a paragraph about the new options (and the existing ability to run a single test file).

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526#-:-MMsUbMD0_xhP1o_4ywA:bj1t7xm)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[test.wls, line 29 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs53jm9vbpQw6NloL9:-MMsNdBi3kiGwahoZMH5:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L29)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Should we `Exit[1]` here as well if there are syntax errors/messages here as well as we do for syntax errors in tests?
</blockquote></details>

Done.
___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMsN9Io5X17fdTehqn_:bhqsi4m) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It produces weird results for me. I added a random dot into `HypergraphToGraph.wlt`, and I'm getting this, which is not very helpful after the first `ToExpression::sntx` message:

```
✗ ./test.wls HypergraphToGraph
Loading SetReplace from /private/var/folders/f_/klrm3n7d4_989wy4dxx9_l9c0000gn/T/SetReplace/Build/Kernel/init.m

Syntax::com: Warning: comma encountered with no adjacent expression. The expression will be treated as Null. .

There were syntax errors in "/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt"

ToExpression::sntx: Invalid syntax in or before "getVertexEdgeList @ HypergraphToGraph[{{x, x, y, z}, {z,. w}}, "StructurePreserving"],".
                                                                                                          ^
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:3	MismatchedParenthesis
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:8	MismatchedParenthesis
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:17	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:22	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:27	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:33	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:39	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:45	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:51	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:56	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:61	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:66	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:71	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:76	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:81	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:86	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:92	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:97	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:102	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:107	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:112	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:117	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:125	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:133	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:139	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:144	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:151	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:161	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:177	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:194	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:197	SyntaxError
/Users/maxitg/git/SetReplace/Tests/HypergraphToGraph.wlt:234	SyntaxError
```
</blockquote></details>

I've capped it to the first 10 things found by FindSyntaxErrors. 
___
*[test.wls, line 117 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs6VOo41Rt8uXmSnC-:-MMsNPklDiWygQdb2hET:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L117)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think we should be doing non-standard indentation here. I understand that this is in a way similar to `namespace { ... }`, but I think this case is too rare and it just makes code harder to understand.
</blockquote></details>

Done.

**Comment by taliesinb** [comment]
Oh, I should also mention that I've included a hack to fixed the nasty InputForm spew that used to happen if a subkernel prints anything or issues a message. It is now much more readable (and even colored orange to draw attention!).

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526)* status: all files reviewed, 4 unresolved discussions (waiting on @taliesinb)

___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMuzPxG2JMSQku6FaZn:bwmsn80) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

I've capped it to the first 10 things found by FindSyntaxErrors. 
</blockquote></details>

The bigger problem is that the result it produces does not make any sense. In fact, it seems to be always the same no matter what I break in the file (I tried adding random dots/slashes and removing braces/string quotes in various places in the file).
___
*[test.wls, line 117 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs6VOo41Rt8uXmSnC-:-MMuzxCC-pjgYJ7F32xC:b-h6oxz8) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L117)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We also don't need empty lines at the start and the end of the block (consistent with the Google style).
___
*[.github/CONTRIBUTING.md, line 107 at r3](https://reviewable.io/reviews/maxitg/setreplace/526#-MMv-HAs7ix3UHuPWT_E:-MMv-HAs7ix3UHuPWT_F:bw11klc) ([raw file](https://github.com/maxitg/setreplace/blob/d57794019dade67cf913e87a28bcc97e046c0ccc/.github/CONTRIBUTING.md#L107)):*
> ```Markdown
> ### Automated tests
> 
> To run the tests, `cd` to the repository root, and run `./build.wls && ./install.wls && ./test.wls` from the command line. If everything is ok, you will see `[ok]` next to each group of tests, and "Tests passed." message at the end. Otherwise, you will see error messages telling you which test inputs failed and for what reason.
> ```

It should now be `./build.wls && ./test.wls` since it tests from the build directory.
___
*[.github/CONTRIBUTING.md, line 109 at r3](https://reviewable.io/reviews/maxitg/setreplace/526#-MMv-tPi0pAOTLfj-b5o:-MMv-tPi0pAOTLfj-b5p:bv98c8h) ([raw file](https://github.com/maxitg/setreplace/blob/d57794019dade67cf913e87a28bcc97e046c0ccc/.github/CONTRIBUTING.md#L109)):*
> ```Markdown
> To run the tests, `cd` to the repository root, and run `./build.wls && ./install.wls && ./test.wls` from the command line. If everything is ok, you will see `[ok]` next to each group of tests, and "Tests passed." message at the end. Otherwise, you will see error messages telling you which test inputs failed and for what reason.
> 
> The `test.wls` script accepts various arguments. Running `./test.wls testfile`, where `testfile` is the name (without trailing `.wlt`) of a test file under the `Tests` directory, will limit the test run to only that file. With the `--load-installed-paclet` flag, the script will load the *installed paclet* instead of the local codebase. With the `--disable-parallelization` flag, you can disable the use of parallel sub-kernels to perform tests. Using parallel sub-kernels will accelerate running the entire test suite, so it is the default behavior, but if you are running only a single test file with a small number of tests, the startup time of the sub-kernels can outweight any speedup they give, and so `--disable-parallelization` will improve performance.
> ```

Mention short flags (`-lip` and `-dp`) as well.

**Review by taliesinb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @maxitg)

___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMvD0Ou7cF0affjOQxY:b8on2ib) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The bigger problem is that the result it produces does not make any sense. In fact, it seems to be always the same no matter what I break in the file (I tried adding random dots/slashes and removing braces/string quotes in various places in the file).
</blockquote></details>

You're right. I've found another way that produces exactly the syntax messages that Get would produce (which are accurate and include line numbers), but without evaluating anything.
___
*[.github/CONTRIBUTING.md, line 107 at r3](https://reviewable.io/reviews/maxitg/setreplace/526#-MMv-HAs7ix3UHuPWT_E:-MMvDB_J7FfCq4mQX2Yc:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/d57794019dade67cf913e87a28bcc97e046c0ccc/.github/CONTRIBUTING.md#L107)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It should now be `./build.wls && ./test.wls` since it tests from the build directory.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 109 at r3](https://reviewable.io/reviews/maxitg/setreplace/526#-MMv-tPi0pAOTLfj-b5o:-MMvDBtPDB5hLazSkZoP:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/d57794019dade67cf913e87a28bcc97e046c0ccc/.github/CONTRIBUTING.md#L109)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Mention short flags (`-lip` and `-dp`) as well.
</blockquote></details>

Done.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526)* status: all files reviewed, 1 unresolved discussion (waiting on @taliesinb)

___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMvEnvE4CZVkDm5xn_z:b-mykvne) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

You're right. I've found another way that produces exactly the syntax messages that Get would produce (which are accurate and include line numbers), but without evaluating anything.
</blockquote></details>

Ok, but it should load `file`, not always `meta.wlt`.

**Review by taliesinb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMvFuokEWcHTPf3-rXu:boalloc) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Ok, but it should load `file`, not always `meta.wlt`.
</blockquote></details>

Oops... Typo. 

Done.

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/526#-:-MMvJVRf9kU-6UD3fp0t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[test.wls, line 72 at r1](https://reviewable.io/reviews/maxitg/setreplace/526#-MMs4KPXD1h15k3bw38Z:-MMvJQM671b7kErNTDLt:b2gt6lm) ([raw file](https://github.com/maxitg/setreplace/blob/e0e080d26618a1419bfd9d5008cdd1bcfd3b1d1f/test.wls#L72)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Oops... Typo. 

Done.
</blockquote></details>

It works now. Nice!

**Pull request merged**
