### PR TITLE
Linter: whitespace formatter

### LINKED ISSUE #522: Linter: spacing issues
### The problem
This is a part of the linter to check the following:
- [x] Enforce line width;
- [ ] Check there are no tabs;
- [ ] No spaces at the end of files;
- [ ] No more than 2 spaces in between characters (unless followed by a comment);
- [ ] No more than 2 empty lines at a time;
- [ ] Empty lines present at the end of files.

This should be checked in all files except C++ (which already has a separate linter). Including WL, Markdown, bash, etc.

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Closes #522.
* Adds `./scripts/whitespaceFormat.sh` that automatically fixes four issues:
   * Replaces tabs with 2 spaces.
   * Removes spaces from ends of lines.
   * Removes repeated empty lines (so that there is at most one at a time).
   * Adds a new line at the end of the file if missing.
* `./lint.sh` now splits the files into different categories and uses one and only one formatter on each of them. The new formatter is used on files not matched elsewhere (including Wolfram Language files).

## Comments

* Removing multiple spaces in the middle of lines is intentionally not implemented because it requires parsing the code (which would depend on the file type). For example, the following is valid formatting even though there are repeated spaces:

https://github.com/maxitg/SetReplace/blob/ec585417e68d819b213d6966024ab33f2072f08f/lint.sh#L29-L32

* Requires #584 to be merged first to fix the existing formatting errors.

## Examples

* [Formatter output](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1523/workflows/70ec7606-47bd-4c1a-8d43-e81bfb9ac3aa/jobs/2471)

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @aokellermann and @maxitg)

*[a discussion](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsDUAG85AGMC_TyHnF:-MOsDUAG85AGMC_TyHnG:b-agnc3g) (no related file):*
We should consider standardizing newline characters as well. IIRC Unix uses `\n` and Windows uses `\r\n`. In the past, I've seen some strange issues where if files were edited on Windows, `\r`s were inserted before all `\n`s to be consistent with the OS. However, both newline schemes are compatible with both OS's so it's not actually an issue which scheme is chosen -- it just may create huge diffs by accident if linting doesn't take care of this. 

---
___
*[lint.sh, line 80 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsOtN50WRPfVOHxkix:-MOsOtN50WRPfVOHxkiy:b-lzpho0) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L80)):*
> ```Shell
> for file in "${bashFiles[@]}"; do
>   if [ $formatInPlace -eq 1 ]; then
>     shfmt -w -i 2 "$file"
> ```

Why not use `formatWithCommand`?
___
*[lint.sh, line 88 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsOw_iEf7VJ07G9q99:-MOsOw_j1z5CkujcnXFL:brhumzt) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L88)):*
> ```Shell
> for file in "${markdownFiles[@]}"; do
>   if [ $formatInPlace -eq 1 ]; then
>     markdownlint -f "$file" || :
> ```

Same here.
___
*[lint.sh, line 95 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsPJ0z5mR2-IS6pH4D:-MOsPJ0z5mR2-IS6pH4E:b-xu9ry3) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L95)):*
> ```Shell
> 
> for file in "${remainingFiles[@]}"; do
>   formatWithCommand ./scripts/whitespaceFormat.sh "$file"
> ```

Why not run this on all files?
___
*[lint.sh, line 115 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsQ-NG4nrYK5h99C4E:-MOsQ-NG4nrYK5h99C4F:b-73cpds) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L115)):*
> ```Shell
> checkLineWidthOutput=$(
>   for file in "${remainingFiles[@]}"; do
>     ./scripts/checkLineWidth.sh "$file" "$widthLimit"
> ```

Neither `shfmt` nor `shellcheck` enforce line width, so you should run this on bash files as well.
___
*[scripts/whitespaceFormat.sh, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsCpbb422ivUXS02Hc:-MOsCpbc033hM1dSa9Bc:b-tnvdkm) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/scripts/whitespaceFormat.sh#L27)):*
> ```Shell
> formatted=$(
>   expand -t 2 "$filename" |                # Tabs to spaces
>     sed -E "s/ +$//" |                     # Remove trailing spaces
> ```

Perhaps use `\s` to catch any trailing whitespace characters?
___
*[scripts/whitespaceFormat.sh, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsEgXMD1efC9x3PT4L:-MOsEgXMD1efC9x3PT4M:b-grk3m0) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/scripts/whitespaceFormat.sh#L28)):*
> ```Shell
>   expand -t 2 "$filename" |                # Tabs to spaces
>     sed -E "s/ +$//" |                     # Remove trailing spaces
>     awk '/./ {e = 0} /^$/ {e += 1} e <= 1' # Remove repeated empty lines
> ```

This looks a little weird to me. Would it not be easier to do something like `sed -E "s/\n{2,}/\n/"`

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @aokellermann)

*[a discussion](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsDUAG85AGMC_TyHnF:-MOsj-lr-x4Uh1W2vIQJ:b-896fix) (no related file):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

We should consider standardizing newline characters as well. IIRC Unix uses `\n` and Windows uses `\r\n`. In the past, I've seen some strange issues where if files were edited on Windows, `\r`s were inserted before all `\n`s to be consistent with the OS. However, both newline schemes are compatible with both OS's so it's not actually an issue which scheme is chosen -- it just may create huge diffs by accident if linting doesn't take care of this. 
</blockquote></details>

Done.

---
___
*[lint.sh, line 80 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsOtN50WRPfVOHxkix:-MOsl4WE4T0NhcIsDOSx:bh0fsey) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L80)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Why not use `formatWithCommand`?
</blockquote></details>

Because the arguments are different. We would have to pass the options for formatting in place etc., at which point it seems to only make this more complicated.
___
*[lint.sh, line 88 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsOw_iEf7VJ07G9q99:-MOslPDKDACmXKSKjZ5T:b-i8x49w) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L88)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Same here, except in this case, there are errors that cannot be automatically fixed, so always printing a diff won't work.
___
*[lint.sh, line 95 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsPJ0z5mR2-IS6pH4D:-MOslh0i3D7nB0XmkOKa:bm8edlm) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L95)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Why not run this on all files?
</blockquote></details>

Surely other formatters take care of these already? If I run it on all files, there will sometimes be duplicate diffs.
___
*[lint.sh, line 115 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsQ-NG4nrYK5h99C4E:-MPdzpBo67HhaOKUC_J_:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/lint.sh#L115)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Neither `shfmt` nor `shellcheck` enforce line width, so you should run this on bash files as well.
</blockquote></details>

Done.
___
*[scripts/whitespaceFormat.sh, line 27 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsCpbb422ivUXS02Hc:-MPe-ziqAjAH19IKq-9V:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/scripts/whitespaceFormat.sh#L27)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Perhaps use `\s` to catch any trailing whitespace characters?
</blockquote></details>

Done.
___
*[scripts/whitespaceFormat.sh, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/583#-MOsEgXMD1efC9x3PT4L:-MPe0-Iz5Az_kMnG-DeZ:b-phve0a) ([raw file](https://github.com/maxitg/setreplace/blob/2df317410d9cbba66718e6df8f4953e7caff0f7a/scripts/whitespaceFormat.sh#L28)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

This looks a little weird to me. Would it not be easier to do something like `sed -E "s/\n{2,}/\n/"`
</blockquote></details>

`sed` reads the input line by line. So, `\n` never appears, and it's not possible to match multiple lines simultaneously (at least not in the simple way you describe).

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[lint.sh, line 115 at r2](https://reviewable.io/reviews/maxitg/setreplace/583#-MQ3QSmJ9BoDIpCG2Q8J:-MQ3QSmK2E4oOV_Wi5Do:bejvcxa) ([raw file](https://github.com/maxitg/setreplace/blob/78c7e3fbbacce4101ff9598e68187c197dbed209/lint.sh#L115)):*
> ```Shell
> widthLimit=120
> checkLineWidthOutput=$(
>   for file in "${remainingFiles[@]}"; do
> ```

It's simpler to just do:
```bash
for file in "${remainingFiles[@]}" "${bashFiles[@]}"; do
```

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[lint.sh, line 115 at r2](https://reviewable.io/reviews/maxitg/setreplace/583#-MQ3QSmJ9BoDIpCG2Q8J:-MQ3YMif5n5QR6rySPLj:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/78c7e3fbbacce4101ff9598e68187c197dbed209/lint.sh#L115)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

It's simpler to just do:
```bash
for file in "${remainingFiles[@]}" "${bashFiles[@]}"; do
```
</blockquote></details>

Done.

**Review by aokellermann — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/583)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
