### PR TITLE
Correct replacement of rule symbols inside ToPatternRules

### LINKED ISSUE #149: ToPatternRules incorrect handling of same lists appearing at different levels
The following makes an incorrect left-hand side and produces a collision of variables between the left-hand side of the rule, and the `Module` variables
```wl
In[] := ToPatternRules[{{1, 2}, {2, 3}, {3, 
    1}} -> {{{1, 2}, {2, 3}, {3, 1}, {1, 4}, {2, 4}, {3, 4}}}]
```
```wl
Out[] = {v4_, v6_, v8_} :> 
 Module[{v4, v5, v6, v7, v8, v9}, {{v4, v6, v8, v5, v7, v9}}]
```

Notice that there is an extra level of `List` on the right-hand side, so, e.g., `{1, 2}` should be interpreted as a single atom.

This appears to be the case of `ReplaceAll` used instead of `Replace` or something like that.

**Expected behavior**
The left-hand side should not be replaced with variables from the right-hand side:
```wl
Out[] = {{v1_, v2_}, {v2_, v3_}, {v3_, v1_}} :> 
 Module[{v4, v5, v6, v7, v8, v9}, {{v4, v6, v8, v5, v7, v9}}]
```

**Version (please complete the following information):**
 - OS: 10.15.1 (19B88)
 - Wolfram Language Version: 12.1.0 for Mac OS X x86 (64-bit) (December 2, 2019)
 - SetReplace git sha: d870ad8322c5fc4100b606de4f9311f3384db6d9

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes
* Closes #149.
* Replacing `ReplaceAll` with `Replace` at the correct levels.

## Examples
```wl
In[]:= ToPatternRules[{{1, 2}, {2, 3}, {3, 1}} -> {{{1, 2}, {2, 3}, {3, 1}, {1, 4}, {2, 4}, {3, 4}}}]
Out[]= {{v1_, v2_}, {v2_, v3_}, {v3_, v1_}} :> Module[{v4, v5, v6, v7, v8, v9}, {{v4, v6, v8, v5, v7, v9}}]

In[]:= ToPatternRules[{{1, 2}, {2, 3}, {3, 1}} -> {{{1, 4}, {1, 4}}}]
Out[]= {{v1_, v2_}, {v2_, v3_}, {v3_, v1_}} :> Module[{v4}, {{v4, v4}}]

In[]:= ToPatternRules[{} -> {{{1, 2}}, {1, 2}}]
Out[]= {} :> Module[{v1, v2, v3}, {{v3}, {v1, v2}}]

In[]:= ToPatternRules[{{1, 2}} -> {{{1, 4}}, {1, 4}, {1, 2}, {{1, 2}}}]
Out[]= {{v1_, v2_}} :> Module[{v3, v4, v5}, {{v5}, {v1, v3}, {v1, v2}, {v4}}]

In[]:= ToPatternRules[{{{1, 2}}, {1, 2}} -> {}]
Out[]= {{v3_}, {v1_, v2_}} :> {}
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442)

### CODE REVIEW

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/ToPatternRules.m, line 45 at r1](https://reviewable.io/reviews/maxitg/setreplace/442#-MJIOuUV08mLAzmK-S5n:-MJIOuUV08mLAzmK-S5o:bug6ygj) ([raw file](https://github.com/maxitg/setreplace/blob/0ca0d5478a1266be5c24dba24dd6602406a7acfd/Kernel/ToPatternRules.m#L45)):*
> ```objc
>     ToHeldExpression /@ StringTemplate["v``"] /@ Range @ Length @ symbols;
>   vertexPatterns = Pattern[#, Blank[]] & /@ newVertexNames;
>   newLeft = (rule[[1]] /. FilterRules[Thread[symbols -> vertexPatterns], leftSymbols]);
> ```

But what about this?
```wl
In[] := ToPatternRules[{} -> {{{1, 2}}, {1, 2}}]
Out[] = {} :> Module[{v1, v2, v3}, {{v3}, v3}]
```
I would just change `ReplaceAll` to `Replace[.., .., {1}]` on the next line.

**Comment by daneelsan** [comment]
It works now:
```wl
In[]:= ToPatternRules[{} -> {{{1, 2}}, {1, 2}}]
Out[]= {} :> Module[{v1, v2, v3}, {{v3}, {v1, v2}}]
```

**Comment by daneelsan** [comment]
```wl
In[]:= ToPatternRules[{{1, 2}} -> {{{1, 4}}, {1, 4}, {1, 2}, {{1, 2}}}]
Out[]= {{v1_, v2_}} :> Module[{v3, v4, v5}, {{v5}, {v1, v3}, {v1, v2}, {v4}}]
```

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan)

___
*[Kernel/ToPatternRules.m, line 46 at r3](https://reviewable.io/reviews/maxitg/setreplace/442#-MJJ2X5i0XPvl-kf5UPO:-MJJ2X5i0XPvl-kf5UPP:bkwx6b) ([raw file](https://github.com/maxitg/setreplace/blob/248f6786aac6547b34acebbecb0a3654199f8d75/Kernel/ToPatternRules.m#L46)):*
> ```objc
>   vertexPatterns = Pattern[#, Blank[]] & /@ newVertexNames;
>   newLeft = (rule[[1]] /. FilterRules[Thread[symbols -> vertexPatterns], leftSymbols]);
>   leftVertices = (leftSymbols /. FilterRules[Thread[symbols -> newVertexNames], leftSymbols]);
> ```

I'm not sure how does `FilterRules` help. We can just as much have differently-nested repeats on each of the sides separately, as have them on the different sides of the rule.
___
*[Kernel/ToPatternRules.m, line 51 at r3](https://reviewable.io/reviews/maxitg/setreplace/442#-MJIyWxw2Khbl4lg7jlq:-MJIyWxw2Khbl4lg7jlr:bt22vsy) ([raw file](https://github.com/maxitg/setreplace/blob/248f6786aac6547b34acebbecb0a3654199f8d75/Kernel/ToPatternRules.m#L51)):*
> ```objc
>   With[
>       {moduleVariables = rightOnlyVertices,
>       moduleExpression = Replace[rule[[2]], Thread[symbols -> newVertexNames], {0, 2}]},
> ```

Ok, but that does not fix the left-hand side:
```wl
In[] := ToPatternRules[{{{1, 2}}, {1, 2}} -> {}]
Out[] = {{{v1_, v2_}}, {v1_, v2_}} :> {}
```

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/ToPatternRules.m, line 46 at r3](https://reviewable.io/reviews/maxitg/setreplace/442#-MJJ2X5i0XPvl-kf5UPO:-MJNHi7DDtk9mmDDeVyC:bs43zey) ([raw file](https://github.com/maxitg/setreplace/blob/248f6786aac6547b34acebbecb0a3654199f8d75/Kernel/ToPatternRules.m#L46)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm not sure how does `FilterRules` help. We can just as much have differently-nested repeats on each of the sides separately, as have them on the different sides of the rule.
</blockquote></details>

There is no way that the symbols in the left are affected by the symbols in the right, right? I mean
`{1, 2, 3}` is always `{v1_, v2_, v3_}`, `{{1, 2}, {2, 3}}` is `{{v1_, v2_}, {v2_, v3_}}`, `{{{1, 2}}, {2}}}` is `{{v1_}, {v2_}}`; without depending on what is on RHS

**Comment by daneelsan** [comment]
You were right about not needing `FilterRules`:
```wl
In[]:= ToPatternRules[{{{1, 2}}, {1, 2}, 2} -> {{1, 2}, 1, 2, {{1, 2}}, {1, 3}}]
Out[]= {{v3_}, {v1_, v2_}, v2_} :> Module[{v4}, {{v1, v2}, v1, v2, {v3}, {v1, v4}}]
```

**Review by maxitg — CHANGES_REQUESTED** [review]
It works! I just have a few test suggestions.

PS. I like just how obscure the rule above is, but I think it works correctly.

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442#-:-MJNRhV99pSUFnh-Acsu:b-apc5ro)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan)

___
*[Kernel/ToPatternRules.m, line 46 at r3](https://reviewable.io/reviews/maxitg/setreplace/442#-MJJ2X5i0XPvl-kf5UPO:-MJNUpXo5KmO--KAB98l:b-q1kpqh) ([raw file](https://github.com/maxitg/setreplace/blob/248f6786aac6547b34acebbecb0a3654199f8d75/Kernel/ToPatternRules.m#L46)):*
<details><summary><i>Previously, daneelsan wrote…</i></summary><blockquote>

There is no way that the symbols in the left are affected by the symbols in the right, right? I mean
`{1, 2, 3}` is always `{v1_, v2_, v3_}`, `{{1, 2}, {2, 3}}` is `{{v1_, v2_}, {v2_, v3_}}`, `{{{1, 2}}, {2}}}` is `{{v1_}, {v2_}}`; without depending on what is on RHS
</blockquote></details>

Yes, I think so.
___
*[Kernel/ToPatternRules.m, line 45 at r5](https://reviewable.io/reviews/maxitg/setreplace/442#-MJNUsJm4GPsKC5RYer2:-MJNUsJm4GPsKC5RYer3:bo2166d) ([raw file](https://github.com/maxitg/setreplace/blob/fc9eeaff505890d4823ea82ae1875b767fd0e949/Kernel/ToPatternRules.m#L45)):*
> ```objc
>     ToHeldExpression /@ StringTemplate["v``"] /@ Range @ Length @ symbols;
>   vertexPatterns = Pattern[#, Blank[]] & /@ newVertexNames;
>   newLeft = Replace[rule[[1]], Thread[symbols -> vertexPatterns], {0, 2}];
> ```

Would be helpful to add a comment saying `Replace` replaces deeper levels first (it was not obvious to me, since `ReplaceAll` doesn't). And if it didn't, a case like this one would break:
```wl
In[] := ToPatternRules[{1, 2} -> {{{1, 2}}}]
Out[] = {v1_, v2_} :> Module[{v3}, {{v3}}]
```
___
*[Tests/ToPatternRules.wlt, line 153 at r5](https://reviewable.io/reviews/maxitg/setreplace/442#-MJNWOUG0AOdxyDv7hev:-MJNWOUG0AOdxyDv7hew:b-iqk00k) ([raw file](https://github.com/maxitg/setreplace/blob/fc9eeaff505890d4823ea82ae1875b767fd0e949/Tests/ToPatternRules.wlt#L153)):*
> ```Mathematica
>         ToPatternRules[{{{1, 2}}, {1, 2}, 2} -> {{1, 2}, 1, 2, {{1, 2}}, {1, 3}}],
>         {{v3_}, {v1_, v2_}, v2_} :> Module[{v4}, {{v1, v2}, v1, v2, {v3}, {v1, v4}}]
>       ]
> ```

I think it would also help to add these (just in case):
```wl
In[] := ToPatternRules[{1, 2} -> {{{1, 2}}}]
Out[] = {v1_, v2_} :> Module[{v3}, {{v3}}]

In[] := ToPatternRules[{{1, 2}} -> {{{1, 2}}}]
Out[] = {{v1_, v2_}} :> Module[{v3}, {{v3}}]
```
and the reverses:
```wl
In[] := ToPatternRules[{{{1, 2}}} -> {1, 2}]
Out[] = {{v1_}} :> Module[{v2, v3}, {v2, v3}]

In[] := ToPatternRules[{{{1, 2}}} -> {{1, 2}}]
Out[] = {{v1_}} :> Module[{v2, v3}, {{v2, v3}}]
```

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/ToPatternRules.m, line 45 at r5](https://reviewable.io/reviews/maxitg/setreplace/442#-MJNUsJm4GPsKC5RYer2:-MJNm7Wf1JzCGHroxf3Y:bi1vk5u) ([raw file](https://github.com/maxitg/setreplace/blob/fc9eeaff505890d4823ea82ae1875b767fd0e949/Kernel/ToPatternRules.m#L45)):*
Ha, I didn't think about that.
```wl
In[]:= {{1, 2}, {{1, 2}}} /. {1 -> "v1", 2 -> "v2", {1, 2} -> "v3"}
Out[]= {"v3", {"v3"}}

In[]:= Replace[{{1, 2}, {{1, 2}}}, {1 -> "v1", 2 -> "v2", {1, 2} -> "v3"}, {0, 2}]
Out[]= {{"v1", "v2"}, {"v3"}}
```
The documentation about `Replace` says:
> If `levelspec` includes multiple levels, expressions at deeper levels in a given `subexpression` are matched first.
Interesting.

**Review by maxitg — APPROVED** [review]
Looks good! You can now merge it yourself, but don't forget to copy the PR message into the commit message. :rocket:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/442#-:-MJNtZpX7K0y9J-G0QGD:b-xlusln)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
