### PR TITLE
Throw exceptions in argumentsChecking, HypergraphPlot, WolframModel and GeneralizedGridGraph

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Functions in `argumentsChecking.m` now throw exceptions instead of printing messages.
* `HypergraphPlot`, `RulePlot`, `WolframModel`, `WolframModelEvolutionObject` and `GeneralizedGridGraph` were updated to use `messages.m` and exceptions.

## Comments

* The main goal here is to change `knownOptionsQ` and `supportedOptionQ` to throw exceptions, as they are useful for implementing properties.

## Examples

* The only change to functionality is that `WolframModelEvolutionObject` plotting functions now correctly print messages from `WolframModelEvolutonObject` instead of `HypergraphPlot`:

image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666)

### CODE REVIEW

**Review by daneelsan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Kernel/argumentsChecking.m, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghFbmm5_vg0cuBpDDC:-MghFbmm5_vg0cuBpDDD:b8qo41c) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/argumentsChecking.m#L8)):*
> ```objc
> PackageScope["checkIfKnownOptions"]
> 
> declareMessage[General::invalidFiniteOption, "Value `value` of option `opt` should be one of `choices` in `expr`."];
> ```

`invalidOptionChoice`? or `invalidEnumOption`
And perhaps ```"Option value `opt` -> `value` in `expr` should be one of `choices`."```
Also, why not "option" instead of "opt"? You use "value" and not "val" (as well as "choices").
___
*[Kernel/argumentsChecking.m, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghHQb-9Q6LF1SLzMTV:-MghHQb-9Q6LF1SLzMTW:b-p9rg7f) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/argumentsChecking.m#L9)):*
> ```objc
> 
> declareMessage[General::invalidFiniteOption, "Value `value` of option `opt` should be one of `choices` in `expr`."];
> checkEnumOptionValue[func_, optionToCheck_, validValues_, opts_] := ModuleScope[
> ```

This could be just `With[{value = ...}, If[!MemberQ[validValues, value], ...]]`
___
*[Kernel/GeneralizedGridGraph.m, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghGhvAAbOBYXE20OKn:-MghGhvAAbOBYXE20OKo:byqbwu3) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/GeneralizedGridGraph.m#L28)):*
> ```objc
> (* Implementation *)
> 
> expr : GeneralizedGridGraph[args___] /; Developer`CheckArgumentCount[expr, 1, 1] := ModuleScope[
> ```

http://reference.wolfram.com/language/ref/CheckArguments.html is available

**Review by daneelsan — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666#-:-MhJt99g6TbsJ8FHX0hB:bnfp4nl)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @maxitg)

**Review by daneelsan — COMMENTED** [review]
Btw, tests are failing because of the migration to CheckArguments:


> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666#-:-MhJvMTx2D6x5xKZ54EN:b-6gtokl)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @maxitg)

**Review by maxitg — COMMENTED** [review]
Right, I just did not get a chance to fix them yet.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666#-:-MhJvpfu53uW_AjkaYba:b7g215p)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/argumentsChecking.m, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghFbmm5_vg0cuBpDDC:-MhFEldj4bxi0CFfz0KS:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/argumentsChecking.m#L8)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

`invalidOptionChoice`? or `invalidEnumOption`
And perhaps ```"Option value `opt` -> `value` in `expr` should be one of `choices`."```
Also, why not "option" instead of "opt"? You use "value" and not "val" (as well as "choices").
</blockquote></details>

Done.
___
*[Kernel/argumentsChecking.m, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghHQb-9Q6LF1SLzMTV:-MhFExucAFMqJCf26UC8:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/argumentsChecking.m#L9)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

This could be just `With[{value = ...}, If[!MemberQ[validValues, value], ...]]`
</blockquote></details>

Done.
___
*[Kernel/GeneralizedGridGraph.m, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/666#-MghGhvAAbOBYXE20OKn:-MhFF8eF0tnqtwUcEf1U:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c7f12484186a31acfa7c7c2c55192642a0c02c92/Kernel/GeneralizedGridGraph.m#L28)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

http://reference.wolfram.com/language/ref/CheckArguments.html is available
</blockquote></details>

Done.

**Review by maxitg — COMMENTED** [review]
The failing tests are now fixed.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666#-:-Miw0_5J3ZkjGBpUFc85:b-k5rx8h)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @daneelsan and @maxitg)

**Review by daneelsan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Kernel/WolframModelEvolutionObject.m, line 288 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFpriWB7hR2ZtL4ocx:-MjFpriWB7hR2ZtL4ocy:blsgztd) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L288)):*
> ```objc
>   "optx", <|"opt" -> First[Last[Complement[{o}, FilterRules[{o}, Options[$propertyOptions[property]]]]]]|>]];
> 
> declareMessage[General::nonopt, StringTemplate[General::nonopt]["`arg`", "`nonoptArgCount`", "`expr`"]];
> ```

That is clever! I always thought it was a shame we could not reuse existing error messages.
___
*[Kernel/WolframModelEvolutionObject.m, line 818 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFpDoz98K3n4hMt5bb:-MjFpDoz98K3n4hMt5bc:bkdjneg) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L818)):*
> ```objc
>                "Feature specification `featureSpec` should be one of `choices`, a list of them, or All."];
> 
> declareMessage[General::unknownFeatureGroup, "Feature group `featureGroup` should be one of `choices`"];
> ```

I think this is missing a dot: `choices`.
___
*[Kernel/WolframModelEvolutionObject.m, line 878 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFo4cm5TZcjiFloca7:-MjFo4cm5TZcjiFloca8:b-2nqh22) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L878)):*
> ```objc
> };
> 
> expr : WolframModelEvolutionObject[data_ ? evolutionDataQ][args__] := ModuleScope[
> ```

Unrelated, but I started to prefer `Module` over `ModuleScope` lately because of the VS extension that highlights local variables inside `Module`.

**Review by daneelsan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @maxitg)

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/666)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/WolframModelEvolutionObject.m, line 288 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFpriWB7hR2ZtL4ocx:-MjFvQvS5TZ-mFI0K6iL:b-tprtjg) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L288)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

That is clever! I always thought it was a shame we could not reuse existing error messages.
</blockquote></details>

Yeah, this should be pretty safe because `declareMessage` redeclares that message the same way as the original one.
___
*[Kernel/WolframModelEvolutionObject.m, line 818 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFpDoz98K3n4hMt5bb:-MjFvnIj9JfTzh3IequH:b8cnrgc) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L818)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I think this is missing a dot: `choices`.
</blockquote></details>

Indeed. Thanks!
___
*[Kernel/WolframModelEvolutionObject.m, line 878 at r4](https://reviewable.io/reviews/maxitg/setreplace/666#-MjFo4cm5TZcjiFloca7:-MjFw9Jk0g7MGGRKUsDp:b237w4p) ([raw file](https://github.com/maxitg/setreplace/blob/18848a31d30be64afee3efb8fe5dcc11b6216633/Kernel/WolframModelEvolutionObject.m#L878)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Unrelated, but I started to prefer `Module` over `ModuleScope` lately because of the VS extension that highlights local variables inside `Module`.
</blockquote></details>

Surely, a better solution would be fixing the VS extension to support `ModuleScope`.

**Pull request merged**
