### PR TITLE
Adding Subhypergraph & WeakSubhypergraph utilities

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes
* Closes https://github.com/maxitg/SetReplace/issues/412.
* Adding `Subhypergraph[h_, vertices_]` utility function that selects hyperedges from `h` that are subsets of `vertices`.
* Adding the weak version of the previous function: `WeakSubhypergraph[h_, vertices_]` that selects any hyperedge from `h` whose elements are contained in `vertices`.

## Comments
* The second argument of these functions should probably support a `pattern`.

## Examples
* Simple examples:
```wl
In[]:= Subhypergraph[{{1, 2, 3}, {2, 3, 4}, {3, 4, 5}}, {1, 2, 3, 4}]

Out[]= {{1, 2, 3}, {2, 3, 4}}
```
```wl
In[]:= WeakSubhypergraph[{{1, 2, 3}, {2, 3, 4}, {3, 4, 5}}, {1, 2, 3, 4}]

Out[]= {{1, 2, 3}, {2, 3, 4}, {3, 4, 5}}
```

* Small table comparing the functions:
```wl
With[{h = {{1, 1, 2, 3}, {2, 3, 4}, {2, 3, 4}, {4}}},
 {allV = Subsets[Union@Catenate[h]]},
 TableForm[
  {Function[v, Select[h, AllTrue[#, MemberQ[v, #] &] &]][#], 
     Subhypergraph[h, #], WeakSubhypergraph[h, #]} & /@ allV,
  TableHeadings -> {allV, None}, TableDepth -> 2
  ]
 ]
```
image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431)

### CODE REVIEW

**Review by maxitg — CHANGES_REQUESTED** [review]
This is a great start! However, in order to close #412, we need a bit more than that. Specifically,

1. The new functions currently cannot be called publicly (see the comment below).
2. It needs to [verify](https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#wolfram-language-code) that the arguments' format is correct. In this case, it amounts to checking if `h` is indeed a hypergraph (a list of lists). If not, it should produce an error message and return unevaluated.
3. We need a few [tests](https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#automated-tests) (even though the functions are simple, we need to make sure they don't get broken in the future).
4. We need [documentation](https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#documentation) for the new functions.

I also suggest putting these functions to a new file to distinguish from the other utilities which are for internal use within the package only.

So, we have two choices:
1. We can rename `Subhypergraph -> subhypergraph` and merge it so that the functions can be used internally only (for now).
2. If you'd like to do a bit more work, it would be best if you could address the comments above so that we can make the functions public and close #412.

Thanks for contributing! If you have any questions, please don't hesitate to ask here or on our Discord server: https://discord.gg/QqjKHA9.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431#-:-MIt9v_f33YAlcZidYbM:b-vq1ja6)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/utilities.m, line 14 at r1](https://reviewable.io/reviews/maxitg/setreplace/431#-MItBlgS9xoDHKW_lTS2:-MItBlgS9xoDHKW_lTS3:b-e2hy8e) ([raw file](https://github.com/maxitg/setreplace/blob/7a11f9a299e7b5497b53276b77986a1b89f543bb/Kernel/utilities.m#L14)):*
> ```objc
> PackageScope["mapHold"]
> PackageScope["heldPart"]
> PackageScope["Subhypergraph"]
> ```

`PackageScope` means the symbols are only available within the package. Use `PackageExport` to make them public (but only if they are tested and documented).
___
*[Kernel/utilities.m, line 56 at r1](https://reviewable.io/reviews/maxitg/setreplace/431#-MItBveSCr2WNJkK2scI:-MItBveSCr2WNJkK2scJ:b-x052k3) ([raw file](https://github.com/maxitg/setreplace/blob/7a11f9a299e7b5497b53276b77986a1b89f543bb/Kernel/utilities.m#L56)):*
> ```objc
> heldPart[expr_, part__Integer] := Extract[Unevaluated[expr], {part}, Hold]
> 
> Subhypergraph[h_, vertices_List] := Select[h, SubsetQ[vertices, #] &]
> ```

Private functions should have lowercase names, i.e., `subhypergraph`.
___
*[Kernel/utilities.m, line 58 at r1](https://reviewable.io/reviews/maxitg/setreplace/431#-MItC0Ke733Dtm_VI5Rg:-MItC0Ke733Dtm_VI5Rh:b-ot49xk) ([raw file](https://github.com/maxitg/setreplace/blob/7a11f9a299e7b5497b53276b77986a1b89f543bb/Kernel/utilities.m#L58)):*
> ```objc
> Subhypergraph[h_, vertices_List] := Select[h, SubsetQ[vertices, #] &]
> 
> weakSubhypergraph[h_, vertices_List] := Select[h, ContainsAny[#, vertices] &]
> ```

If we are going to turn this into a public function, it will need to have an uppercase name, i.e., `WeakSubhypergraph`.

**Comment by daneelsan** [comment]
Yes, I'll expose the functions and add tests/documentation. 
I wasn't sure from the issue that it should've been a public function.

**Review by maxitg — CHANGES_REQUESTED** [review]
Excellent work! I just have a few comments, mostly about code style and invalid-argument messages, otherwise, it's ready to go!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431#-:-MJ4KODr7SkA_QthGMbw:b-s8k8he)* status: all files reviewed, 15 unresolved discussions (waiting on @daneelsan)

___
*[README.md, line 2016 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4G0Ie1g1jp4lxetUk:-MJ4G0Ie1g1jp4lxetUl:b-lukjyk) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/README.md#L2016)):*
> ```Markdown
> ## Utility Functions
> 
> [WolframModelRuleValue](#wolframmodelrulevalue) | [GeneralizedGridGraph](#generalizedgridgraph) | [HypergraphAutomorphismGroup](#hypergraphautomorphismgroup) | [HypergraphUnifications](#hypergraphunifications) | [WolframPhysicsProjectStyleData](#wolframphysicsprojectstyledata) | [Build Data](#build-data) | [Subhypergraph](#subhypergraph)
> ```

I think we should move it to the beginning actually. I think it's going to be the most useful (or at least the least obscure) one.
___
*[README.md, line 2295 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4OB-W-6V_sZ3gSil5:-MJ4OB-W-6V_sZ3gSil6:b-r13cul) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/README.md#L2295)):*
> ```Markdown
> These constants are particularly useful for reporting issues with the code.
> 
> ### Subhypergraph
> ```

If you move it in the index, also move the section itself above from here.
___
*[Kernel/Subhypergraph.m, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4H94hAkjz8d3YSIbm:-MJ4H94hAkjz8d3YSIbn:bnv9ynt) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L1)):*
> ```objc
> (* ::Package:: *)
> ```

Please use the simplified format consistent with the other files (like https://github.com/maxitg/SetReplace/blob/master/Kernel/HypergraphUnificationsPlot.m). Specifically,
1. Don't use front-end generated comments like `(* ::Package:: *)`, etc. They make the files unnecessarily long (see, e.g., how much shorted some files became after #422).
2. Keep at most a single empty line at a time.
3. Use spaces instead of tabs.
___
*[Kernel/Subhypergraph.m, line 29 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4IF9aAHZwef0ygKGp:-MJ4IF9aAHZwef0ygKGq:b-dcy2bz) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L29)):*
> ```objc
> 
> WeakSubhypergraph::usage = usageString[
> 	"WeakSubhypergraph[`h`, `vertices`] that selects any hyperedge from `h` whose elements are contained in `vertices`.",
> ```

I think the word "that" should not be here.
___
*[Kernel/Subhypergraph.m, line 54 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4IQJ5C-PQNdLS7czW:-MJ4IQJ5C-PQNdLS7czX:b-6k5rr3) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L54)):*
> ```objc
> 
> 
> hypergraphQ = MatchQ[#, {___List}]&;
> ```

Nit: space before `&`.
___
*[Kernel/Subhypergraph.m, line 115 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4NdM_AlmSCvYNikvj:-MJ4NdM_AlmSCvYNikvk:b-hc482u) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L115)):*
> ```objc
> 
> 
> expr: Subhypergraph[h_ ? (Not @* hypergraphQ), _] := 0 /;
> ```

We also need messages for the operator forms of both functions.
___
*[Kernel/Subhypergraph.m, line 116 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4KHRGBgy6NyBBnnpe:-MJ4KHRGBgy6NyBBnnpf:bwlax2o) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L116)):*
> ```objc
> 
> expr: Subhypergraph[h_ ? (Not @* hypergraphQ), _] := 0 /;
> 	Message[Subhypergraph::invalidHypergraph, 1, HoldForm@expr]
> ```

Nit: Change `HoldForm@expr` -> `HoldForm @ expr` consistent with the rest of the codebase.
___
*[Kernel/Subhypergraph.m, line 120 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4KMId1w1D0LH-nt7E:-MJ4KMId1w1D0LH-nt7F:b5c0gam) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L120)):*
> ```objc
> 
> expr: WeakSubhypergraph[h_ ? (Not @* hypergraphQ), _] := 0 /;
> 	Message[WeakSubhypergraph::invalidHypergraph, 1, HoldForm@expr]
> ```

Nit: same here.
___
*[Kernel/Subhypergraph.m, line 127 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4J-Vk7HqrhIB1a8_W:-MJ4J-Vl6b5rQ2Di_huV:b-871agd) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L127)):*
> ```objc
> 
> 
> Subhypergraph[h_ , v : Except[_List]] := 0 /; False
> ```

Shouldn't this print a message as well?
___
*[Kernel/Subhypergraph.m, line 130 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4J3qM1IBtOAouh1WB:-MJ4J3qM1IBtOAouh1WC:brhumzt) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Kernel/Subhypergraph.m#L130)):*
> ```objc
> 
> 
> WeakSubhypergraph[h_ , v : Except[_List]] := 0 /; False
> ```

Same here.
___
*[Tests/Subhypergraph.wlt, line 11 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4J9TDDXABfwKF3zas:-MJ4J9TDDXABfwKF3zat:bezz7jm) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Tests/Subhypergraph.wlt#L11)):*
> ```Mathematica
> 
>       VerificationTest[
>         Subhypergraph[{},{}],
> ```

Add spaces after commas, the same everywhere else in this file.
___
*[Tests/Subhypergraph.wlt, line 42 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4JgTf1HhW8V2ib5UN:-MJ4JgTf1HhW8V2ib5UO:b-kzk8zo) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Tests/Subhypergraph.wlt#L42)):*
> ```Mathematica
>       testUnevaluated[
>         Subhypergraph[1,{2,3,4}],
>         {Subhypergraph::invalidHypergraph}
> ```

Check other kinds of invalid hypergraphs as well, namely, e.g., `{1, 2}`, i.e., depth 1 list instead of depth 2.
___
*[Tests/Subhypergraph.wlt, line 44 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4Nk1v2LURJTkLUW1i:-MJ4Nk1v2LURJTkLUW1j:b-a98rsv) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Tests/Subhypergraph.wlt#L44)):*
> ```Mathematica
>         {Subhypergraph::invalidHypergraph}
>       ],
> ```

Also, test the not-yet implemented messages for the vertices, and the operator forms (both for the invalid hypergraph and the invalid vertex list).
___
*[Tests/Subhypergraph.wlt, line 88 at r3](https://reviewable.io/reviews/maxitg/setreplace/431#-MJ4K6vt110Id1vixDij:-MJ4K6vt110Id1vixDik:b-v60148) ([raw file](https://github.com/maxitg/setreplace/blob/918341a65198d4df86c79ae5994f04f7046b55bc/Tests/Subhypergraph.wlt#L88)):*
> ```Mathematica
> 
>       testUnevaluated[
>         WeakSubhypergraph[1,{2,3,4}],
> ```

Same here, test depth-1 list as the first argument.

**Comment by daneelsan** [comment]
I'll work on the changes.

I think https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#code-structure mislead me, as the example in:
> Further, public symbols must include SyntaxInformation, see an example for WolframModel.

Was before files were WL code refactored (I'm talking about the notebook headers).

**Review by maxitg — CHANGES_REQUESTED** [review]
Good point. I updated the contributing guidelines just now (#440), including the links to the code with outdated formatting. Thanks for pointing that out!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431#-:-MJEqYEb8i6RrZ1s3zkg:bz960t3)* status: all files reviewed, 12 unresolved discussions (waiting on @daneelsan)

___
*[Kernel/Subhypergraph.m, line 1 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEraQt6cDCUCwjLXKj:-MJEraQt6cDCUCwjLXKk:b-i6chb8) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L1)):*
> ```objc
> (* ::Package:: *)
> ```

Remove this `(* ::Package:: *)` line as well.
___
*[Kernel/Subhypergraph.m, line 37 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEsFAH4HmA8caQT0Z3:-MJEsFAH4HmA8caQT0Z4:b1moelk) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L37)):*
> ```objc
> 
> (* main *)
> expr : Subhypergraph[arg1_, arg2_] := With[{res = Catch[iSubhypergraph[HoldForm @ expr, arg1, arg2]]},
> ```

What does `i` mean in `iSubhypergraph`? Either expand to the full name or use the lowercase `subhypergraph` instead (which is what is done in the rest of the codebase).
___
*[Kernel/Subhypergraph.m, line 38 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEruPJ31sIe2WZo6qh:-MJEruPJ31sIe2WZo6qi:biej3df) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L38)):*
> ```objc
> (* main *)
> expr : Subhypergraph[arg1_, arg2_] := With[{res = Catch[iSubhypergraph[HoldForm @ expr, arg1, arg2]]},
> 	res /; res =!= $Failed
> ```

Change tabs to spaces.
___
*[Kernel/Subhypergraph.m, line 41 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEslR0EC002tAx1yFf:-MJEslR0EC002tAx1yFg:bixowa5) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L41)):*
> ```objc
> ]
> 
> expr : WeakSubhypergraph[arg1_, arg2_] := With[{res = Catch[iWeakSubhypergraph[HoldForm @ expr, arg1, arg2]]},
> ```

Same about `i` here.
___
*[Kernel/Subhypergraph.m, line 42 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEspRV35iYazK3PNzR:-MJEspRWBX--hw9zCIHa:bckqmhb) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L42)):*
> ```objc
> 
> expr : WeakSubhypergraph[arg1_, arg2_] := With[{res = Catch[iWeakSubhypergraph[HoldForm @ expr, arg1, arg2]]},
> 	res /; res =!= $Failed
> ```

Tabs -> spaces.
___
*[Kernel/Subhypergraph.m, line 47 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEsr7B2n_00T6MLqox:-MJEsr7B2n_00T6MLqoy:bckqmhb) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L47)):*
> ```objc
> (* operator form *)
> expr : Subhypergraph[args0___][args1___] := With[{res = Catch[iSubhypergraph[HoldForm @ expr][args0][args1]]},
> 	res /; res =!= $Failed
> ```

Tabs -> spaces.
___
*[Kernel/Subhypergraph.m, line 51 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEwBrkBuWehl2HoN3f:-MJEwBrkBuWehl2HoN3g:bgg0m2n) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L51)):*
> ```objc
> 
> expr : WeakSubhypergraph[args0___][args1___] := With[{res = Catch[iWeakSubhypergraph[HoldForm @ expr][args0][args1]]},
> 	res /; res =!= $Failed
> ```

Tabs -> spaces
___
*[Kernel/Subhypergraph.m, line 78 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEu3Za154pBYa49ZCE:-MJEu3Za154pBYa49ZCF:bczy8u5) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L78)):*
> ```objc
> (** vertices **)
> General::invalidVertexList =
>   "The argument at position `1` in `2` is not a valid hypergraph.";
> ```

This message is never used.
___
*[Kernel/Subhypergraph.m, line 81 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEwFtNCaO1L7U2gpAr:-MJEwFtNCaO1L7U2gpAs:bgg0m2n) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L81)):*
> ```objc
> 
> iSubhypergraph[_, _ , v : Except[_List]] :=
> 	(Message[Subhypergraph::invl, 2];
> ```

Tabs -> spaces
___
*[Kernel/Subhypergraph.m, line 89 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJF25Hz4g3m5CboRTKK:-MJF25Hz4g3m5CboRTKL:bklx5u6) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L89)):*
> ```objc
> 
> (* operator form *)
> iSubhypergraph[_][vertices_List][h_ ? hypergraphQ] := iSubhypergraph[None, h, vertices]
> ```

Why not just pass it as is (without checking) to the normal form? It's going to argument check everything except for the arguments count anyway.
___
*[Kernel/Subhypergraph.m, line 93 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEx4TnE0uGc9b0fed0:-MJEx4TnE0uGc9b0fed1:bi2aeif) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L93)):*
> ```objc
> iWeakSubhypergraph[_][vertices_List][h_ ? hypergraphQ] := iWeakSubhypergraph[None, h, vertices]
> 
> (* The operator form of Select does not check that the zeroth argument is valid, it just returns {} *)
> ```

Is it the same thing here though? `Select` returns an empty list even in a normal form:
```wl
In[] := Select[{1, 5, 3}, 5]
Out[] = {}
```
I'm not sure why it does that, but it does not seem to have anything to do with its form. I think we should print the message because someone might accidentally use `WeakSubhypergraph[3]` assuming it will select all hyperedges containing vertex 3, and it would instead fail silently, which is dangerous.

**Comment by daneelsan** [comment]
Tabs just keep getting through :(
I'll forgot the convention was to use `subhypergraph` instead of `iSubhypergraph`. :+1:

**Comment by daneelsan** [comment]
The message is `General::invalidVertexList` is used in, but with other heads: `WeakSubhypergraph`, `Subhypergraph`. Unless I'm mistaken, that is how you reuse error messages.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431)* status: all files reviewed, 12 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/Subhypergraph.m, line 1 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEraQt6cDCUCwjLXKj:-MJFAvoD7YZHutuKbl-z:bksdvu1) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove this `(* ::Package:: *)` line as well.
</blockquote></details>

I didn't notice it because I was using Mathematica :-)

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431)* status: all files reviewed, 12 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/Subhypergraph.m, line 1 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEraQt6cDCUCwjLXKj:-MJFBHTS5W7mdZfeKNMY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L1)):*
<details><summary><i>Previously, daneelsan wrote…</i></summary><blockquote>

I didn't notice it because I was using Mathematica :-)
</blockquote></details>

Done.
___
*[Kernel/Subhypergraph.m, line 89 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJF25Hz4g3m5CboRTKK:-MJFBStjDoQ3MMhQlVsb:bo244bp) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L89)):*
> ```
> iWeakSubhyperg
> ```
I guess because if the check failed during the call to `weaksubhypergraph`, then the error message would show the incorrect "caller".

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431)* status: all files reviewed, 12 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Kernel/Subhypergraph.m, line 78 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEu3Za154pBYa49ZCE:-MJFDImH236o1BjzZkJi:b4yq785) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L78)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This message is never used.
</blockquote></details>

Found the mistake!

**Review by maxitg — CHANGES_REQUESTED** [review]
Just one little thing left, and we are good to go!

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431#-:-MJFS_6L6V6s7Gv0mRgF:bx3oz5c)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/Subhypergraph.m, line 41 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJEslR0EC002tAx1yFf:-MJFLHCr-ndqagMoSNc7:bsb0jp4) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L41)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same about `i` here.
</blockquote></details>

The convention is lower camel, not everything lowercase. So, it would be `weakSubhypergraph`.
___
*[Kernel/Subhypergraph.m, line 81 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJFLh877WGX7yFFEqk6:-MJFLh877WGX7yFFEqk7:b5xzc85) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L81)):*
> ```objc
> 
> iSubhypergraph[_, _ , v : Except[_List]] :=
> 	(Message[Subhypergraph::invl, 2];
> ```

I don't see a problem using the build-in message (`General::invl`), but this works as well, I don't really have a preference. I think your message is better than the built-in one.
___
*[Kernel/Subhypergraph.m, line 89 at r4](https://reviewable.io/reviews/maxitg/setreplace/431#-MJF25Hz4g3m5CboRTKK:-MJFR-I79lcoNq1aSGi2:b5to7z3) ([raw file](https://github.com/maxitg/setreplace/blob/f6c633cc3e3b158732222878f82fcb08755767bf/Kernel/Subhypergraph.m#L89)):*
<details><summary><i>Previously, daneelsan wrote…</i></summary><blockquote>

> ```
> iWeakSubhyperg
> ```
I guess because if the check failed during the call to `weaksubhypergraph`, then the error message would show the incorrect "caller".
</blockquote></details>

I see, the position would be incorrect, makes sense.

**Review by maxitg — APPROVED** [review]
Awesome work! Thanks for contributing! :rocket:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/431#-:-MJFWkARET59LvtjhwCe:b-ojbezz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
