### PR TITLE
Change names in C++ to be Yellowstone consistent

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Changes names in the C++ code to be Yellowstone consistent and allow generalization to other systems, e.g., expression -> token, Set -> HypergraphSubstitutionSystem, etc.
* Renames Expression.* and Event.* to AtomsIndex.* and TokenEventGraph.*, as they better describe what's in those files.
* Moves some definitions from hypergraph-specific files to IDTypes.hpp and TokenEventGraph.hpp.

## Comments

* There are no functionality/logic changes, just renaming and reorganizing.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/640)

### CODE REVIEW

**Review by daneelsan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/640)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[libSetReplace/HypergraphMatcher.hpp, line 32 at r1](https://reviewable.io/reviews/maxitg/setreplace/640#-M_3Ujq55gf0jHMdHKBY:-M_3Ujq6AaQRp_54xxql:b-mxbmyw) ([raw file](https://github.com/maxitg/setreplace/blob/dea96a84f1577165946d327113f70359557b7f14/libSetReplace/HypergraphMatcher.hpp#L32)):*
> ```cpp
>     First = 0,
>     SortedInputTokenIndices = First,
>     ReverseSortedInputTokenIndices = 1,
> ```

I assume "indices" in "TokenIndices" is the same as "IDs", right?

**Review by daneelsan — COMMENTED** [review]
Yellowstone approved

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/640#-:-M_3c2_h2Kllh-1lJVSd:b2n7gh7)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/640)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @daneelsan and @taliesinb)

___
*[libSetReplace/HypergraphMatcher.hpp, line 32 at r1](https://reviewable.io/reviews/maxitg/setreplace/640#-M_3Ujq55gf0jHMdHKBY:-M_avlmG1Vc1N4WlC4Uy:b1faiyr) ([raw file](https://github.com/maxitg/setreplace/blob/dea96a84f1577165946d327113f70359557b7f14/libSetReplace/HypergraphMatcher.hpp#L32)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I assume "indices" in "TokenIndices" is the same as "IDs", right?
</blockquote></details>

Yes, they are. I like to keep the name 'ID' because 'index' is used in a different meaning for the atoms index. Do you have a better name in mind to refer to the creation order instead of 'index'?

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/640)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[libSetReplace/HypergraphMatcher.hpp, line 32 at r1](https://reviewable.io/reviews/maxitg/setreplace/640#-M_3Ujq55gf0jHMdHKBY:-M_cYVkR-byMYoHcHH7e:b-vqngeo) ([raw file](https://github.com/maxitg/setreplace/blob/dea96a84f1577165946d327113f70359557b7f14/libSetReplace/HypergraphMatcher.hpp#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Yes, they are. I like to keep the name 'ID' because 'index' is used in a different meaning for the atoms index. Do you have a better name in mind to refer to the creation order instead of 'index'?
</blockquote></details>

Not really, "tokenCreationIndex" is too verbose, I think.

**Pull request merged**
