### PR TITLE
Separate parts of `If`, `Catch`, `Check`, `Quiet` statements

### LINKED ISSUE #541: Code style: separate parts of `If` statement
### The problem
The issue with `If` in Wolfram Language is that it's very easy to miss the difference between a compound expression and an "else". That is, compare

```wl
If[x > 0,
  a = 4;
  b = a + 1
]
```

to

```wl
If[x > 0,
  b = 4,
  b = a + 1
]
```

### Possible solution
To make these cases more readable, the following style is suggested:

```wl
If[x > 0,
  b = 4
,
  b = a + 1
]
```

The idea behind this indentation is that the comma takes the part of an `else if` in a language like C++:

```wl
If[x > 0,
  b = 4
,  (* else *)
  b = a + 1
]
```

A similar style should be used in other functions where compound expressions are expected. For example, `Catch`:

```wl
Catch[
  Message[abc::def];
  x = 5;
,
  Exit[1]
]
```

### Additional context
This should eventually make its way into linter #247. In the meantime, we need to update the existing code itself and the contributing guidelines.

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes

* Closes #541.
* Format code style of `If`, `Catch`, `Check`, `Quiet` functions.
* Contributing guidelines updated.

## Comments

* If any other functions that expect compound expressions come to mind, let me know.

* Expressions that fit in a single line remain unchanged:
```wl
  If[!FileExistsQ[tempBuildInfoFile], ReturnFailed["nobuildinfo", tempBuildInfoFile]];
```

## Examples

```wl
  outputWithMetadata = Catch[
    Reap[
      setReplace$wl[initWithMetadata, rulesWithMetadata, stepSpec, vertexIndex, returnOnAbortQ, timeConstraint],
      {$$deletedExpressions, $$events}]
  ,
    $$nonListExpression
  ,
    (Message[caller::nonListExpressions, #]; Return[$Failed]) &
  ];
```

```wl
    result = Catch @ Check[
      If[modifiedEvolution =!= $Failed,
        If[ListQ[property],
          Catch[
            Check[propertyEvaluateWithOptions[#], Throw[$Failed, $propertyMessages]] & /@ property
          ,
            $propertyMessages
          ,
            $Failed &
          ]
        ,
          propertyEvaluateWithOptions @ property
        ] /.
          HoldPattern[WolframModelEvolutionObject[data_Association]] :>
            WolframModelEvolutionObject[Join[data, <|$rules -> rulesSpec|>]]
      ,
        $Failed
      ]
    ,
      $Failed
    ];
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/596)

### CODE REVIEW

**Comment by daneelsan** [comment]
I get this when running `./lint.sh`:
image

Changing `which` to `command -v` fixes the issue.

**Comment by maxitg** [comment]
@daneelsan, we need to fix that, however, the error in CI is different. I guess you are using a different version.

**Comment by daneelsan** [comment]
@maxitg A different version of what?

**Comment by maxitg** [comment]
> @maxitg A different version of what?

Of [markdownlint](https://github.com/DavidAnson/markdownlint).

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/596)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann, @daneelsan, and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 721 at r2](https://reviewable.io/reviews/maxitg/setreplace/596#-MRW9woNEr_DNZ1Rcke2:-MRW9woNEr_DNZ1Rcke3:brzndvl) ([raw file](https://github.com/maxitg/setreplace/blob/970d728e7667f6708fac49d10bd850188d614ac5/.github/CONTRIBUTING.md#L721)):*
> ```Markdown
>   If[DuplicateFreeQ[destroyedExpressions],
>     Sort[Complement[createdExpressions, destroyedExpressions]]
>   , (* else *)
> ```

I think that might be confused for the requirement of actually putting an `(* else *)` comment in the every `If` statement (which I've seen happen in other codebases).

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/596)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @aokellermann, @maxitg, and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 721 at r2](https://reviewable.io/reviews/maxitg/setreplace/596#-MRW9woNEr_DNZ1Rcke2:-MS0q_hf2nvOgbbcI1xt:bis0m37) ([raw file](https://github.com/maxitg/setreplace/blob/6265b43715e6072bd176eac07126df14c2726177/.github/CONTRIBUTING.md#L721)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think that might be confused for the requirement of actually putting an `(* else *)` comment in the every `If` statement (which I've seen happen in other codebases).
</blockquote></details>

Agree. Done.

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/596#-:-MS2toDkC61AkTm8pdHx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aokellermann and @taliesinb)

**Pull request merged**
