### PR TITLE
Apple ARM support

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Compiles the Mac library for both arm64 and x86_64 to enable Apple Silicon support.

## Comments

- [x] Works on x86_64
- [x] Works on ARM

## Tests

To check an architecture and mark the checkbox, evaluate:

```wl
PacletUninstall["SetReplace"];
Quit;
PacletInstall["path_to_built_paclet_in_CI"];
<< SetReplace`;
WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}, 4, "FinalStatePlot", Method -> "LowLevel"]
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)

### CODE REVIEW

**Review by daneelsan — APPROVED** [review]
Works for me:


> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651#-:-Ma_qDO0EUf9qQPAqyOm:buifvt8)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @maxitg)

___
*[scripts/buildLibraryResources.sh, line 25 at r2](https://reviewable.io/reviews/maxitg/setreplace/651#-Ma_pagD2TKgeN5yJkLs:-Ma_pagD2TKgeN5yJkLt:bbafbkg) ([raw file](https://github.com/maxitg/setreplace/blob/c9d0dc4b61a6b7458fe8d38f91a097e92de03f6e/scripts/buildLibraryResources.sh#L25)):*
> ```Shell
>   libraryResourcesDirName=MacOSX-x86-64
>   libraryExtension=dylib
>   macOSBuildArm64="OFF"
> ```

NIT: move `macOSBuildArm64` and `macOSBuildX86_64` above `libraryResourcesDirName` like you do with the other ifs.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aokellermann)

___
*[scripts/buildLibraryResources.sh, line 25 at r2](https://reviewable.io/reviews/maxitg/setreplace/651#-Ma_pagD2TKgeN5yJkLs:-Ma_rRPuBPqwNBJmOCoZ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9d0dc4b61a6b7458fe8d38f91a097e92de03f6e/scripts/buildLibraryResources.sh#L25)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

NIT: move `macOSBuildArm64` and `macOSBuildX86_64` above `libraryResourcesDirName` like you do with the other ifs.
</blockquote></details>

Done.

**Review by daneelsan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aokellermann)

**Review by daneelsan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651#-:-Maa1GnM0hw0GpivBI6K:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aokellermann)

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: all files reviewed, 2 unresolved discussions (waiting on @maxitg)

___
*[CMakeLists.txt, line 11 at r3](https://reviewable.io/reviews/maxitg/setreplace/651#-Maa8xM67BataUULCW94:-Maa8xM7DVYRl1WbrkFh:b-rrmqt0) ([raw file](https://github.com/maxitg/setreplace/blob/3fc4c9bf5b5eedc3be9c501988b9d7e6cd2c1a10/CMakeLists.txt#L11)):*
> ```CMake
> 
> if(SET_REPLACE_BUILD_OSX_ARM64)
>   list(APPEND CMAKE_OSX_ARCHITECTURES arm64)
> ```

According to [documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) this should be set prior to `project()` call and should be set in `CACHE`.
___
*[scripts/buildLibraryResources.sh, line 80 at r3](https://reviewable.io/reviews/maxitg/setreplace/651#-Maa7b7l89CziqeGhhpN:-Maa7b7m5Z_N5rs4-frK:b-rksthc) ([raw file](https://github.com/maxitg/setreplace/blob/3fc4c9bf5b5eedc3be9c501988b9d7e6cd2c1a10/scripts/buildLibraryResources.sh#L80)):*
> ```Shell
> cd build
> cmake .. -DSET_REPLACE_ENABLE_ALLWARNINGS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release \
>   -DSET_REPLACE_BUILD_OSX_ARM64="$macOSBuildArm64" -DSET_REPLACE_BUILD_OSX_X86_64="$macOSBuildX86_64"
> ```

If kernel is not `Darwin`, these variables will not be set and therefore not provide `ON` or `OFF`. I tested it on Linux, and it seems to work fine, but it looks a little dodgy. A default value would make it look a lot cleaner.

**Review by maxitg — COMMENTED** [review]
@daneelsan, can you try this version as well? https://4575-151987734-gh.circle-artifacts.com/0/BuiltPaclets/SetReplace-0.3.183.paclet

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651#-:-Maoj-GRCT5JLE8dEhnC:b-g69ssi)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @aokellermann)

___
*[CMakeLists.txt, line 11 at r3](https://reviewable.io/reviews/maxitg/setreplace/651#-Maa8xM67BataUULCW94:-Maocnfh3ohLMCH2CcKP:b-hpa5ht) ([raw file](https://github.com/maxitg/setreplace/blob/3fc4c9bf5b5eedc3be9c501988b9d7e6cd2c1a10/CMakeLists.txt#L11)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

According to [documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) this should be set prior to `project()` call and should be set in `CACHE`.
</blockquote></details>

Indeed, I made things a lot more complicated than necessary.
___
*[scripts/buildLibraryResources.sh, line 80 at r3](https://reviewable.io/reviews/maxitg/setreplace/651#-Maa7b7l89CziqeGhhpN:-Maoirxx4tstbnPHs-Zz:b-ae1m9h) ([raw file](https://github.com/maxitg/setreplace/blob/3fc4c9bf5b5eedc3be9c501988b9d7e6cd2c1a10/scripts/buildLibraryResources.sh#L80)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

If kernel is not `Darwin`, these variables will not be set and therefore not provide `ON` or `OFF`. I tested it on Linux, and it seems to work fine, but it looks a little dodgy. A default value would make it look a lot cleaner.
</blockquote></details>

I now check if the variable is unset.

**Review by aokellermann — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: all files reviewed, 2 unresolved discussions (waiting on @aokellermann)

**Review by daneelsan — APPROVED** [review]
Still works:


> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651#-:-Map8pbp-fh5sw7Ql1SL:by84p2c)* status: all files reviewed, 2 unresolved discussions (waiting on @aokellermann)

**Review by aokellermann — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

**Review by aokellermann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maxitg)

**Pull request merged**
