### PR TITLE
$SetReplaceTypeGraph

### PR DESCRIPTION
**Pull request by maxitg**
## Changes

* Adds a `$SetReplaceTypeGraph` constant.
* The constant contains the nicely formatted type graph.

## Examples

* Examples below do not work directly because they use fake types. To try them out, do something like
   ```wl
   AppendTo[$ContextPath, "SetReplace`PackageScope`"];
   ```
   and then evaluate the definitions (line 15 to 81) from `typeSystem.wlt`.

* Now, check `$SetReplaceTypeGraph`:
   ```wl
   In[] := $SetReplaceTypeGraph
   ```

   image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/621)

### CODE REVIEW

**Comment by maxitg** [comment]
I'm just going to add a table of contents to the type system README, and then this will be ready for review.

**Comment by maxitg** [comment]
@taliesinb, @daneelsan, this is ready for review now.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/621)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypeGraph.md, line 13 at r2](https://reviewable.io/reviews/maxitg/setreplace/621#-MVSTEwlA-MHZYGnXxbE:-MVSTEwlA-MHZYGnXxbF:b-fq040l) ([raw file](https://github.com/maxitg/setreplace/blob/05520d9ddc1f22c4e6f2406950c712bf0d4c64c0/Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypeGraph.md#L13)):*
> ```Markdown
> ```
> 
> 
> ```

Not a very informative image hehe. Was this intended because we have yet to define some types?

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/621)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @daneelsan and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypeGraph.md, line 13 at r2](https://reviewable.io/reviews/maxitg/setreplace/621#-MVSTEwlA-MHZYGnXxbE:-MVTfPwY-N-1sGKZNruB:b-dsumad) ([raw file](https://github.com/maxitg/setreplace/blob/05520d9ddc1f22c4e6f2406950c712bf0d4c64c0/Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypeGraph.md#L13)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Not a very informative image hehe. Was this intended because we have yet to define some types?



</blockquote></details>

Yes, that's very much intended. We need to add some types to it (in another PR).

**Review by daneelsan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/621#-:-MVThapHAtSM38Zjdtra:bnfp4nl)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @daneelsan and @taliesinb)

**Pull request merged**
