### PR TITLE
CMake: Fix name of test file

### PR DESCRIPTION
**Pull request by phcerdan**
The file is named `Set_test.cpp`, changed from `SetTest.cpp`

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/366)

### CODE REVIEW

**Comment by aokellermann** [comment]
Fixed in #364.

**Comment by phcerdan** [comment]
So, a simple fix is now dependent on a bigger PR like #364 ?

Why don't merge this, and rebase #364 on top of the new master?

In fact #364 has a lot of things that seems unrelated to the purpose of its title:
```
    Rename Set_test.cpp to SetTest.cpp to follow same pattern as the rest of the files (it also wouldn't compile due to discrepency with CMake file.
    Fix all files' #includes.
    Add -build/c++11 and -build/c++14, since SetReplace is a C++17 library.
    Add CPPLINT.cfg file in root to manage cpplint options easier.
    Add extensions option to cpplint to include .hpp files as well.
```

I understand that is hard to work in interdependent parallel branches, but shoving things into one big PR makes things harder to review, and slows down development.

**Comment by maxitg** [comment]
I agree we should merge this separately. Our general policy is to [keep PRs as small as possible](https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#opening-a-pull-request) (although I have to admit, I sometimes struggle with that rule myself).

**Comment by phcerdan** [comment]
> Looks good (I assume you tried to compile it to make sure it works).

It does work. Thanks

#364 renames the file `Set_test.cpp` to `SetTest.cpp`, instead of modifying the `CMakeLists.txt`. I think we changed the name because of constraints in `cpplint`.

**Pull request merged**
