### PR TITLE
Cpp optimizations

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Increased usage of STL functions for efficiency.
* Reduced instances of pass-by-value to reduce amount of copying, particularly vectors. 
* Reduced amount of hash lookups (sets/maps). Although complexity is constant, lookups are quite expensive.
* Increased usage of foreach loops
* Some other misc. optimizations

Overall performance is increased by up to 37% in one test I ran of WolframModel.

## Comments
* No functionality changes.
* As a bonus, these commits include auto code formatting. This partially addresses #319. You may see a lot of erasures on blank lines. Many IDEs including mine erase white space to reduce file size.

## Examples
Testing setup functions:
```wl
Attributes[meanAroundTiming] = {HoldAll};
meanAroundTiming[expr_, measurementsCount_ : 5] := 
 MeanAround@Table[First@AbsoluteTiming[expr], measurementsCount]
```
```wl
speedupDelta[old_, new_] := UnitConvert[(old - new)/old, "Percent"]
```
```wl
run := meanAroundTiming[WolframModel[#1, Automatic, #2]] & @@@ {
   {{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, 10},
   {{{1, 2, 3}, {4, 3, 5}, {3, 6}} -> {{6, 7, 8}, {6, 9, 10}, {11, 8, 
       10}, {5, 2, 9}, {9, 9}, {1, 9}, {7, 5}, {8, 5}}, 13},
   {{{1, 2, 2}, {3, 2, 4}} -> {{5, 4, 4}, {4, 3, 5}, {3, 5, 1}}, 
    10000},
   {{{1, 2}, {2, 1}, {1, 3}, {2, 3}, {3, 1}, {3, 2}} -> {{1, 2}, {2, 
       1}, {1, 3}, {2, 3}, {3, 1}, {3, 2}, {1, 4}, {2, 4}, {3, 4}, {4,
        1}, {4, 2}, {4, 3}}, 4},
   {{{1}, {1}, {1}} -> {{1}, {1}, {1}, {1}}, 10}
   }
```
Running from master, 
```wl
master = run
```
yields
2020-04-22-203022_1920x1080_scrot
Running from this branch,
```wl
this = run
```
yields
2020-04-22-203908_1920x1080_scrot
To compare the two, running
```wl
speedupDelta[master, this]
```
yields
2020-04-22-180159_1920x1080_scrot

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/328)

### CODE REVIEW

**Comment by maxitg** [comment]
I'll take a look once #330 is merged.

**Comment by maxitg** [comment]
Fantastic work! Thanks! I just have a few questions/comments, mostly about style.

**Comment by maxitg** [comment]
This is what I'm getting, more than twice worse performance in some cases: [CPP_Optimizations_Test.nb.zip](https://github.com/maxitg/SetReplace/files/4612891/CPP_Optimizations_Test.nb.zip). There must be something we are not understanding about these changes. It's also interesting to note that my results are consistently slower, even on master.

**Comment by maxitg** [comment]
Looks like this is going to be more complicated than we thought. I'm going to write a performance-testing script soon (maybe tomorrow), which would just take two branches as an argument, and return the performance difference. Then, I will run it with gcc on Gentoo to see if I can reproduce your results. It is possible that these changes cause performance regressions with clang (Apple clang version 11.0.3), but not with gcc.

**Comment by aokellermann** [comment]
I re-ran testing on master, CPP_Optimizations (before merge from master), and CPP_Optimizations (after merge from master). I'm not able to reproduce your performance loss:
[CPP_Optimizations.nb.gz](https://github.com/maxitg/SetReplace/files/4612960/CPP_Optimizations.nb.gz)

**Comment by aokellermann** [comment]
Running same test on Windows 10 using latest version of MSVC, I get the same results as on Linux: 
[CPP_Optimizations.nb.gz](https://github.com/maxitg/SetReplace/files/4615879/CPP_Optimizations.nb.gz)

**Comment by maxitg** [comment]
Using [performanceTest.wlt script](https://github.com/maxitg/SetReplace/blob/performanceTest/performanceTest.wls) on [performanceTest branch](https://github.com/maxitg/SetReplace/tree/performanceTest), I can reproduce your results on Linux (gcc 9.3.0), more or less. The large error bars are probably due to the fact that it's a VPS on a shared hardware:
```
Single-input rule                       10. ± 7. %
Medium rule                             0. ± 7. %
Sequential rule                         12. ± 7. %
Large rule                              18. ± 7. %
Exponential-match-count rule            26. ± 5. %
```

but not on Mac (clang-1103.0.32.59):
```
Single-input rule                       -276. ± 14. %
Medium rule                             -117.4 ± 1.0 %
Sequential rule                         -31.7 ± 0.9 %
Large rule                              7.3 ± 0.6 %
Exponential-match-count rule            22.31 ± 0.16 %
```

So, something is going on with clang. I guess I'll have to split your commits and see which part causes the regression.

**Comment by phcerdan** [comment]
Test it without the changes on passing  `std::function` by reference. 

https://stackoverflow.com/questions/47167673/passing-stdfunction-as-parameter-with-const-void

**Comment by maxitg** [comment]
> Test it without the changes on passing `std::function` by reference.

That did not help:
```
> ./performanceTest.wls master removeFunctionReference

Single-input rule                       -361. ± 25. %
Medium rule                             -120. ± 9. %
Sequential rule                         -34. ± 5. %
Large rule                              8.7 ± 1.5 %
Exponential-match-count rule            29.4 ± 3.1 %
```

**Comment by maxitg** [comment]
Results on a Mac after removing the aforementioned `reserve`:
```
> ./performanceTest.wls master removeReserve

Single-input rule                       12.8 ± 0.6 %
Medium rule                             4.7 ± 0.5 %
Sequential rule                         2.8 ± 0.9 %
Large rule                              7.59 ± 0.31 %
Exponential-match-count rule            21.8 ± 0.7 %
```

**Comment by aokellermann** [comment]
Great catch! I got better results on gcc compared to before removing the `reserve`: 
2020-05-12-191339_1920x1080_scrot

**Pull request merged**
