### PR TITLE
Style and grammar fixes to Local Multiway System

### LINKED ISSUE #456: LocalMultiwaySystem Editing
### The problem
Internal Wolfram DQA team has suggested edits to the [Local Multiway System](/Research/LocalMultiwaySystem/LocalMultiwaySystem.md) research note. These edits need to be addressed and ported from the notebook to the original document.

### Possible solution
The document with comments: [MaxP-LocalMultiwaySystems-02_DQAedits-2.nb](https://github.com/maxitg/SetReplace/files/5368509/MaxP-LocalMultiwaySystems-02_DQAedits-2.nb.zip)

### PR DESCRIPTION
**Pull request by maxitg**
## Changes
* Closes #456.
* Address review comments from the internal Wolfram DQA team.
* Many thanks to *Taylor Birch* for spotting these!

## Comments
* Some comments were only applied to the bulletin for https://www.wolframphysics.org/bulletins/, but not backported here:
  * Left title here to be "Local Multiway System" (singular)
  * Kept commas after "e.g." and "i.e.". I've been doing it everywhere else, so if we change it here, we'll have to change it in the documentation as well, and I don't see a particular reason to do it given that both are acceptable, and the version with the commas seems to be preferred in American English.
  * Left `3` as a number instead of spelling it out.
* Let me know if you think I should port any of these here as well.
* Here is the notebook that will go to the bulletins website (except the commit up top will be updated to the merge commit of this PR): [MaxP-LocalMultiwaySystems-03.nb.zip](https://github.com/maxitg/SetReplace/files/5382654/MaxP-LocalMultiwaySystems-03.nb.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/474)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/474)* status: all files reviewed, 5 unresolved discussions (waiting on @maxitg)

___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 137 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgf0tn4JeTibiNdJyA:-MJgf0tn4JeTibiNdJyB:baaw564) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L137)):*
> ```Markdown
> especially given that both states are canonicalized.
> 
> To illustrate the point, here is an example of a branchlike and a spacelike separated pair of events, respectively:
> ```

Spacelike-separated
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 156 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJg_54-DCLRDSmmiKSc:-MJg_54-DCLRDSmmiKSd:b-wiou85) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L156)):*
> ```Markdown
> Suppose we have a system with overlapping pairs of rule matches.
> We still want to include all of those events in the multiway system.
> But instead of duplicating the entire state, we will do that locally, i.e., we will have multiple branches growing from
> ```

Comma splice after "locally". Use a semicolon.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 375 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgaeqN2Le-sVOCb8nB:-MJgaeqN2Le-sVOCb8nC:b-hcviqe) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L375)):*
> ```Markdown
> So, if the expressions are immediate neighbors in the causal graph, as in the examples above, the separation is not hard
> to determine.
> However, what if the expressions are further down in history?
> ```

I think further *back* in history makes more sense.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 484 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgfnBv-jI9_xQRzSkB:-MJgfnBv-jI9_xQRzSkC:baaw564) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L484)):*
> ```Markdown
> 
> If we look closely at the events near the merge points, we can see that some redundancy remains.
> However, it is no longer due to the spacelike separated events, but rather due to the "background" expressions being
> ```

Spacelike-separated
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 566 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgbQYZ6QQer53mvhxx:-MJgbQYZ6QQer53mvhxy:bf0xkq1) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L566)):*
> ```Markdown
> 
> 
> However, looking at even this simple example, we can determine that the algorithm described above is not quite right,
> ```

Comma splice after "right". Replace with semicolon.

**Comment by aokellermann** [comment]
To be consistent with hyphens, we should go through the README as well.

* When used before a noun, *like-separated should include a hyphen.
* In other cases, *like separated should not include a hyphen.

**Review by maxitg — COMMENTED** [review]
Tracked in #476.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/474#-:-MJhMiiz8tS-iHBow37H:b-bt44ea)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @aokellermann)

___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 137 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgf0tn4JeTibiNdJyA:-MJhJAUd9bavO_CcNWbW:bc3bno1) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L137)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Spacelike-separated
</blockquote></details>

With a dash after "branchlike-" as well?
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 156 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJg_54-DCLRDSmmiKSc:-MJhJL-t1pzcCdzG_nLU:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L156)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Comma splice after "locally". Use a semicolon.
</blockquote></details>

Done.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 375 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgaeqN2Le-sVOCb8nB:-MJhJPKZDMmcSNodJ6pJ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L375)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

I think further *back* in history makes more sense.
</blockquote></details>

Done.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 484 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgfnBv-jI9_xQRzSkB:-MJhJUar1QTqwqrkJV71:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L484)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Spacelike-separated
</blockquote></details>

Done.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 566 at r2](https://reviewable.io/reviews/maxitg/setreplace/474#-MJgbQYZ6QQer53mvhxx:-MJhJbYuEuYnsem_wyzJ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ca9fa6803dd11d56fe0e155d3d97084411f463a8/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L566)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Comma splice after "right". Replace with semicolon.
</blockquote></details>

Done.

**Review by aokellermann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/474)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aokellermann)

**Pull request merged**
