### PR TITLE
Add options for WolframModel properties

### PR DESCRIPTION
**Pull request by sw1sh**
## Changes
* Now it's possible to specify options for WolframModel properties in its arguments
* Options for multiple properties `{{"FinalStatePlot", VertexLabels -> Automatic}, "CausalGraph"}`
* Master options apply to all properties `{"FinalStatePlot", "CausalGraph"}, VertexLabels -> Automatic`
* Options as property arguments have higher priority than master options `{{"FinalStatePlot", VertexLabels -> None}, "CausalGraph"}, VertexLabels -> Automatic`
* `WolframModelEvolutionObject` has "Caller" option to propagate messages (only used in WolframModel)
* WolframModel properties outsourced to WolframModelEvolutionObject

## Examples
* Add labels to a graph like this: 
```
WolframModel[{{1, 2}} -> {{1, 2}}, {{1, 1}}, 4, {"CausalGraph", VertexLabels -> Automatic}]
```
instead of operating on `WolframModelEvolutionObject`:
```
WolframModel[{{1, 2}} -> {{1, 2}}, {{1, 1}}, 4]["CausalGraph", VertexLabels -> Automatic]
```
* Fails with unknown property message: `WolframModel[1 -> 2, {1}, 2, "CausalGraph", WorkingPrecision -> 10]`
* Ignores inapplicable known property: `WolframModel[1 -> 2, {1}, 2, "FinalState", ImageSize -> 256]`

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/358)

### CODE REVIEW

**Comment by sw1sh** [comment]
Tests are on its way

**Comment by maxitg** [comment]
Great work! It looks like it's working correctly for the cases I tried. And it's quite useful that options can be specified both globally for all properties, and for each property individually (which is an improvement compared to #238).

I will look at the code more closely tomorrow morning (EDT), but a quick comment, the code is generating messages on `Get` (which is also why CI is failing):
image

**Comment by sw1sh** [comment]
@maxitg Damn, that was the last commit that broke it, was thinking it was a typo or something. Never doubt yourself in the past.

**Comment by sw1sh** [comment]
___
*[Kernel/WolframModel.m, line 199 at r3](https://reviewable.io/reviews/maxitg/setreplace/358#-M7eecyUEfWAN8HBnrFF:-M7i353l6k51P5V9ElGS:b-y8qlq7) ([raw file](https://github.com/maxitg/setreplace/blob/6bdcf6c062b17a225015d4efbb7be2f46fccb9f7/Kernel/WolframModel.m#L199)):*
<details><summary><i>Previously, sw1sh (Nikolay Murzin) wrote…</i></summary><blockquote>

Maybe loosen this restriction to a function scope at least?
</blockquote></details>

I couldn't figure out how to setup reviewable to ignore whitespace changes. But github has a checkbox for that.

**Comment by maxitg** [comment]
I'm sorry, but this got way too complicated. There are too many API/behavior changes, and they are extremely hard to keep track of.

And there are new changes in the recent commit, i.e.,
```wl
In[] := WolframModel[1 -> 2, {1}, 2.2]
```
now returns two error messages, which is not ok, and is not mentioned in #238, or any other issue.

Plus, the original comments (i.e., inconsistent indentation) are still not addressed.

Please, create issues for any separate change in functionality (including different error message behavior, etc.), and once we agree to the changes, create separate PRs for *one issue at a time*. Feel free to create a PR that will change indentation to spaces, but please change that for *entire files* (better yet, create one PR that will change that, and only that, everywhere), not single functions.

I will have to close this PR now due to the issues described above, sorry.

**Comment by maxitg** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
