### PR TITLE
Matching Optimizations

### LINKED ISSUE #428: Profile C++ code
### The problem
We need to understand where are the bottlenecks in the C++ implementation of the evolution.

### Possible solution
The best approach would probably be just to comment the findings in this issue. If some pieces of the code are surprisingly slow, it would be helpful to create separate issues for fixing that, and reference them here.

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Reduce `std::map` operations
* Reduce `std::vector` copying

## Comments
* Resolves #428
* Requires #437 

## Examples
Performance increase:
```
[antony@arch ~/repos/SetReplace]$ ./performanceTest.wls
Testing master
Build done.
Uninstalling previous SetReplace at /home/antony/.Mathematica/Paclets/Repository/SetReplace-0.3.48
Installed to /home/antony/.Mathematica/Paclets/Repository/SetReplace-0.3.48
Restart running kernels to complete installation.

Testing 72b91c2ff602c7cf27da0388f166aafe38ea977c
Build done.
Uninstalling previous SetReplace at /home/antony/.Mathematica/Paclets/Repository/SetReplace-0.3.48
Installed to /home/antony/.Mathematica/Paclets/Repository/SetReplace-0.3.48
Restart running kernels to complete installation.

Single-input rule                       3.1 ± 1.5 %
Medium rule                             0.5 ± 1.4 %
Sequential rule                         14.49 ± 0.35 %
Large rule                              25.5 ± 0.4 %
Exponential-match-count rule            32.0 ± 0.6 %
CA emulator                             3.9 ± 0.6 %
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/438)

### CODE REVIEW

**Review by maxitg — CHANGES_REQUESTED** [review]
Good stuff!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/438#-:-MJACHCU7f5R43pNpyLj:beuyiaz)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[CMakeLists.txt, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/438#-MJAAKGhBsT3sJ4CxlNA:-MJAAKGhBsT3sJ4CxlNB:baxc7dy) ([raw file](https://github.com/maxitg/setreplace/blob/933bde2e51cb05460945656dd9b143878b89bd16/CMakeLists.txt#L9)):*
> ```CMake
> option(SET_REPLACE_WITH_MATHEMATICA "Add the library definition for Wolfram LibraryLink" OFF)
> option(SET_REPLACE_BUILD_TESTING "Enable cpp testing." OFF)
> option(SET_REPLACE_PROFILE "Enable profile options")
> ```

Don't forget to remove the code from the other PR.

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/438)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[CMakeLists.txt, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/438#-MJAAKGhBsT3sJ4CxlNA:-MJAJKXI06z9nRmUOgzU:bpznutt) ([raw file](https://github.com/maxitg/setreplace/blob/933bde2e51cb05460945656dd9b143878b89bd16/CMakeLists.txt#L9)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Don't forget to remove the code from the other PR.
</blockquote></details>

Once the other PR is merged, this PR's diff will update.

**Review by maxitg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/438)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[CMakeLists.txt, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/438#-MJAAKGhBsT3sJ4CxlNA:-MJEq19y48TKdr8pcKj6:b-s8b522) ([raw file](https://github.com/maxitg/setreplace/blob/933bde2e51cb05460945656dd9b143878b89bd16/CMakeLists.txt#L9)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Once the other PR is merged, this PR's diff will update.
</blockquote></details>

Even though they now diverged? Plus, I don't see why should these optimizations require profiling tests (especially since you run the old tests in the examples anyway).

**Review by maxitg — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/438)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
