### PR TITLE
Update contributing guidelines

### PR DESCRIPTION
**Pull request by maxitg**
## Changes
* The contributing guidelines became quite outdated over the last half-year.
* This PR updates them to be in line with the current situation.
* The most significant change is that unlike the old guidelines (which explicitly said this repository is only for software), it now allows for contributing research notes. It adds some rules on how to do so.
* It also updates the labels guide.
* Adds instructions on how to run the CI for a pull request from a fork.
* Updates example links to the code that used old formatting style.
* Streamlines the CMake instructions.

## Comments
* I will wait for reviews from both @aokellermann and @taliesinb before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)

### CODE REVIEW

**Review by aokellermann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @aokellermann, @maxitg, and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJF5QOk929LIT_4U4bG:-MJF5QOk929LIT_4U4bH:b-6zz4gb) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L1)):*
> ```Markdown
> First, thanks for contributing! :thumbsup:
> ```

You should add a link to the discord somewhere in this doc, and give some info about it.
___
*[.github/CONTRIBUTING.md, line 13 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJEwcRBATtwujfX4CKO:-MJEwcRCCX7HyagTo4qs:bpb87ee) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L13)):*
> ```Markdown
> First off, while it's common to call problems with the code "bugs", we call them *weeds* here instead (kudos to [@aokellermann](https://github.com/aokellermann)). That's because using the word "bug" in a negative context implicitly sends a message that *bugs* (aka insects) are someone bad and should be squashed. We don't agree with that sentiment, as *bugs* :ant: :beetle: :spider: are living creatures who deserve moral consideration. Hence, let's leave "bugs" alone, and go *weed whacking*.
> 
> The issues in this repository are only related to *SetReplace*, not the entire Wolfram Physics Project. If you have found an issue with a Wolfram Physics [bulletin](https://www.wolframphysics.org/bulletins/), or with anything else on the Wolfram Physics [website](https://www.wolframphysics.org), please report it using the tools available there. The bulletins that also appear as [research notes](/Research) in this repository are the only exceptions. The issues with these should be reported here.
> ```

In the README, you consistently use **SetReplace** (bold) to refer to the library, whereas in this document you consistently use *SetReplace* (italics). You should pick one and sitck to it.
___
*[.github/CONTRIBUTING.md, line 275 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJF51_7-uAnE_W7iR2Y:-MJF51_81lAlcSQLiI7m:b1lm5er) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L275)):*
> ```Markdown
> 
> ```bash
> cmake .. -DSET_REPLACE_BUILD_TESTING=ON -DSET_REPLACE_PROFILE=ON
> ```

Remove profile option

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aokellermann and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJF5QOk929LIT_4U4bG:-MJFGugY22HHeOFQGFXh:bflubt6) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

You should add a link to the discord somewhere in this doc, and give some info about it.
</blockquote></details>

Done (in style).
___
*[.github/CONTRIBUTING.md, line 13 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJEwcRBATtwujfX4CKO:-MJFHwNT0w3frbNO2sOW:b-nrzb9x) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L13)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

In the README, you consistently use **SetReplace** (bold) to refer to the library, whereas in this document you consistently use *SetReplace* (italics). You should pick one and sitck to it.
</blockquote></details>

It's actually inconsistent in the README already. Fixed in #441.
___
*[.github/CONTRIBUTING.md, line 275 at r1](https://reviewable.io/reviews/maxitg/setreplace/440#-MJF51_7-uAnE_W7iR2Y:-MJFJtIX5GljlQ9D0nL3:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/6da8d5107ce612481666d51ae044bb71889f6374/.github/CONTRIBUTING.md#L275)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Remove profile option
</blockquote></details>

Done.

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: all files reviewed, 3 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[README.md, line 130 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHYKzUEcgFvg-kXqSk:-MJHYKzUEcgFvg-kXqSl:b9fcypl) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/README.md#L130)):*
> ```Markdown
> *SetReplace* is an open-source project, and everyone is welcome to contribute. Read our [contributing guidelines](/.github/CONTRIBUTING.md) to get started.
> 
> We have a [Discord server](discord.setreplace.org). If you would like to contribute but have questions or don't know where to start, this is the perfect place! In addition to helping new contributors, we discuss feature and research ideas, so, if you are interested, please join!
> ```

Link is broken (prefix with `https://` most likely)
___
*[README.md, line 130 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHYvOVC_MBUFff15A9:-MJHYvOVC_MBUFff15AA:bfknp6j) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/README.md#L130)):*
> ```Markdown
> *SetReplace* is an open-source project, and everyone is welcome to contribute. Read our [contributing guidelines](/.github/CONTRIBUTING.md) to get started.
> 
> We have a [Discord server](discord.setreplace.org). If you would like to contribute but have questions or don't know where to start, this is the perfect place! In addition to helping new contributors, we discuss feature and research ideas, so, if you are interested, please join!
> ```

Change comma after "ideas" to a period.
___
*[.github/CONTRIBUTING.md, line 283 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHZSNs02gDzB_43h-E:-MJHZSNs02gDzB_43h-F:b-kpl7qk) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/.github/CONTRIBUTING.md#L283)):*
> ```Markdown
> Then, after building, you can run the tests using the binaries in `libSetReplace/test/`.
> 
> #### Using SetReplace in third-party CMake projects
> ```

Consistently use "third-party" with dash, or without.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aokellermann and @taliesinb)

___
*[README.md, line 130 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHYKzUEcgFvg-kXqSk:-MJHaR8c4PiPeX0F4iOb:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/README.md#L130)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Link is broken (prefix with `https://` most likely)
</blockquote></details>

Done.
___
*[README.md, line 130 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHYvOVC_MBUFff15A9:-MJHaUho4omFyDzMYEvp:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/README.md#L130)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Change comma after "ideas" to a period.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 283 at r2](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHZSNs02gDzB_43h-E:-MJHawcX5Biz0VYAxQy4:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/78219d3ca17928f12caad71c49f9208495b3dba2/.github/CONTRIBUTING.md#L283)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Consistently use "third-party" with dash, or without.
</blockquote></details>

Done.

**Review by aokellermann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 270 at r3](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHdUUnESP1tZmCb-c5:-MJHdUUnESP1tZmCb-c6:b-abt7q0) ([raw file](https://github.com/maxitg/setreplace/blob/92d909a831340a667eea534a0af2911dd3dfdad4/.github/CONTRIBUTING.md#L270)):*
> ```Markdown
> 
> - `SET_REPLACE_WITH_MATHEMATICA`:
> Generates the target `SetReplaceMathematica` that provides an interface for using *SetReplace* in Wolfram Language.
> ```

Consistently use *libSetReplace* to refer to C++ library.

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 270 at r3](https://reviewable.io/reviews/maxitg/setreplace/440#-MJHdUUnESP1tZmCb-c5:-MJHetwg-Z3qk7YpJPjG:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92d909a831340a667eea534a0af2911dd3dfdad4/.github/CONTRIBUTING.md#L270)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Consistently use *libSetReplace* to refer to C++ library.
</blockquote></details>

Done.

**Review by aokellermann — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @taliesinb)

**Review by taliesinb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: all files reviewed, 8 unresolved discussions (waiting on @maxitg)

___
*[.github/CONTRIBUTING.md, line 13 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMEjqf6jLwGdS8WIi2:-MJMEjqf6jLwGdS8WIi3:bmihkja) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L13)):*
> ```Markdown
> ## Weed reports (something is not working)
> 
> First off, while it's common to call problems with the code "bugs", we call them *weeds* here instead (kudos to [@aokellermann](https://github.com/aokellermann)). That's because using the word "bug" in a negative context implicitly sends a message that *bugs* (aka insects) are someone bad and should be squashed. We don't agree with that sentiment, as *bugs* :ant: :beetle: :spider: are living creatures who deserve moral consideration. Hence, let's leave "bugs" alone, and go *weed whacking*.
> ```

Not part of the PR, but I also love the idea that we are tending a garden, and weeds *will* grow whenever you open up a new plot of land for development. 
___
*[.github/CONTRIBUTING.md, line 33 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMEZSk5BBeRdJJ6dXF:-MJMEZSk5BBeRdJJ6dXG:b-89e78w) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L33)):*
> ```Markdown
> 6. Your issue is now on the list, and a developer will look at it if/when they have a chance. But if it does not get any attention, the best you can do is to [fix it yourself](#code).
> 
> Also, please understand that mistakes happen and are unavoidable. We never blame people for unintentional mistakes in this project. Instead, we improve our development process to minimize the probability of mistakes in the future.
> ```

I very much approve of this sentiment. 
___
*[.github/CONTRIBUTING.md, line 61 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMFIgeAbBswLMdIe_9:-MJMFIgeAbBswLMdIe_A:b-v0izqk) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L61)):*
> ```Markdown
> * `visualization`: has to do with visualization code, such as `WolframModelPlot`.
> * `utilities`: implements a tool that does not fit in the above categories (e.g., [`Subhypergraph`](https://github.com/maxitg/SetReplace/pull/431)).
> * `infrastructure`: implements changes to the development process, e.g., build scripts, CI, testing utilities, etc.
> ```

How does the `research` type label interact with these component labels? None of them seem appropriate for research. Perhaps `research` should have a separate set of tags, to be decided in future as we have more examples to fit into a typology? 
___
*[.github/CONTRIBUTING.md, line 88 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMG3bV5bbYeGL1Wcyh:-MJMG3bV5bbYeGL1Wcyi:blxder4) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L88)):*
> ```Markdown
> The unit tests are particularly important if you are implementing a weed fix, as it is crucial to make sure the weed you are fixing is not going to return in the future. And if you are implementing a new function, unit tests should cover not only the functionality but also the behavior in case the function is called with invalid arguments. Each function should have at least some unit tests; there is a test in [meta.wlt](/Tests/meta.wlt) to enforce that.
> 
> If sharing variables among multiple tests, use [`With`](https://reference.wolfram.com/language/ref/With.html) instead of [`Module`](https://reference.wolfram.com/language/ref/Module.html) or global assignment, because otherwise, variables will not appear resolved in the command line error message if the test fails (which makes it harder to weed whack). Also, try to avoid large inputs and outputs for the tests, if at all possible (by, for example, replacing `VerificationTest[large1[], large2[]]` with `VerificationTest[large1[] === large2[]]`).
> ```

I believe we should modernize these guidelines to use Scope and ModuleScope where appropriate. I'm going to add this point to https://github.com/maxitg/SetReplace/issues/402 so that we remember to update these guidelines as part of that issue's PR.
___
*[.github/CONTRIBUTING.md, line 377 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMP0GY2d2iIdFiS-1w:-MJMP0GY2d2iIdFiS-1x:bzdzbpx) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L377)):*
> ```Markdown
> * Similar issue could happen with [`Thread`](https://reference.wolfram.com/language/ref/Thread.html), especially when used to thread a single element over multiple. For example, it is easy to assume naively that `Thread[x -> {1, 2, 3}]` would always yield `{x -> 1, x -> 2, x -> 3}`. Except, sometimes it might be called as `With[{x = {4, 5, 6}}, Thread[x -> {1, 2, 3}]]`.
> * Use uppercase camel for public symbols, lowercase camel for internal (including PackageScope) symbols.
> * Start global constants with `$`, whether internal or public, and tags (such as used in [`Throw`](https://reference.wolfram.com/language/ref/Throw.html) or [`Sow`](https://reference.wolfram.com/language/ref/Sow.html), or as generic enum labels) with `$$`. Global pure functions (defined as [`OwnValues`](https://reference.wolfram.com/language/ref/OwnValues.html)) should still be treated as ordinary (e.g., [`DownValues`](https://reference.wolfram.com/language/ref/DownValues.html)) functions and not start with `$`, unless they are public, in which case they should start with `$`.
> ```

By 'global' I imagine you are referring to functions that users (or developers experimenting with library internals) might want to overload. E.g. `$DefaultGraphInsetFunction` would be the *kind* of the name for a function like this (this name is nonsense of course). If this is what you intend, I suggest adding the requirement that such overridable functions end with the word `Function`.
___
*[.github/CONTRIBUTING.md, line 391 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMPoDL-Euqz_3-17Ix:-MJMPoDL-Euqz_3-17Iy:b-4sxirr) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L391)):*
> ```Markdown
> * If splitting function arguments into multiple lines, each argument should go on a separate line.
> * License, authors, and file descriptions should not be put at the top of files.
> * Doxygen is used for documentation.
> ```

Doxygen *format* is used for documentation? I thought there was no actual automated generation of doxygen HTML output, as of yet.
___
*[.github/CONTRIBUTING.md, line 407 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMPvjR3Ry_B8qAxLA-:-MJMPvjR3Ry_B8qAxLA0:bdoo59o) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L407)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> If there are no errors found, it will exit with no output.
> To edit the code in place with the fixed formatting use `./lint.sh -i`.
> If `cpplint` flags a portion of your code, please make sure it is adhering to the proper code style. If it is a false
> positive or if there is no reasonable way to avoid the flag, you may put `// NOLINT` at the end of the line if there is
> space, or `// NOLINTNEXTLINE` on a new line above if there is no space. For any usages of `// NOLINT` or
> `// NOLINTNEXTLINE`, please describe the reason for its inclusion both in a code comment and in your pull request's
> comments section.
> If you want to disable formatting, use `// clang-format off` and `// clang-format on` around the manually formatted
> ```
</details>

___
*[.github/CONTRIBUTING.md, line 423 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMQ6C-4joHDUjiwtjN:-MJMQ6C-4joHDUjiwtjO:bn4394d) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L423)):*
> ```Markdown
>   ```wl
>   Round[0.6 First @ Import["$RepoRoot/READMEImages/image.png", "ImageSize"]]
>   ```
> ```

This workflow works, but is suboptimal. Not saying there is anything to do about it in the PR, but I think we can improve this considerably with automated tooling. Here is an issue I have created to elaborate: https://github.com/maxitg/SetReplace/issues/449

**Review by taliesinb — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: all files reviewed, 8 unresolved discussions (waiting on @maxitg)

**Review by maxitg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @aokellermann and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 61 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMFIgeAbBswLMdIe_9:-MJNYecU5KGV-Wr-0bGT:bcycbc1) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L61)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

How does the `research` type label interact with these component labels? None of them seem appropriate for research. Perhaps `research` should have a separate set of tags, to be decided in future as we have more examples to fit into a typology? 
</blockquote></details>

I think they are appropriate for some research. [Local Multiway System](https://github.com/maxitg/SetReplace/blob/master/Research/LocalMultiwaySystem/LocalMultiwaySystem.md) is the `evolution` research (it explores a possible way to run evolutions). A note describing graph geometry would be an `analysis` research (it analyses the output of the evolution). It is true that we might need more tags in the future, notably, `physics` where we attempt to make a connection to physics.
___
*[.github/CONTRIBUTING.md, line 88 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMG3bV5bbYeGL1Wcyh:-MJNbVMO-jBDUKEJdX5h:b1t5cd8) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L88)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

I believe we should modernize these guidelines to use Scope and ModuleScope where appropriate. I'm going to add this point to https://github.com/maxitg/SetReplace/issues/402 so that we remember to update these guidelines as part of that issue's PR.
</blockquote></details>

Yes, but we should do it simultaneously with changing the existing code.
___
*[.github/CONTRIBUTING.md, line 377 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMP0GY2d2iIdFiS-1w:-MJNbl5l5CKRkTQ8QoQk:b3oko2n) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L377)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

By 'global' I imagine you are referring to functions that users (or developers experimenting with library internals) might want to overload. E.g. `$DefaultGraphInsetFunction` would be the *kind* of the name for a function like this (this name is nonsense of course). If this is what you intend, I suggest adding the requirement that such overridable functions end with the word `Function`.
</blockquote></details>

That's one possibility. Another possibility is to have read-only constants that are accessible to the user, e.g., some of the functions in `style.m` if they were standalone constants. But in either case, ending them with `Function` is a good idea.
___
*[.github/CONTRIBUTING.md, line 391 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMPoDL-Euqz_3-17Ix:-MJNcRqK-tgDj1bdhzz-:bw2t2wl) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L391)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Doxygen *format* is used for documentation? I thought there was no actual automated generation of doxygen HTML output, as of yet.
</blockquote></details>

Changed. This is true, we don't have an HTML output, however, tools like Xcode can automatically pickup that documentation and display it in the UI.
___
*[.github/CONTRIBUTING.md, line 407 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMPvjR3Ry_B8qAxLA-:-MJNclyuD7BdYp4PoIG9:b-3zerfp) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L407)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

> ```
> If there are no errors found, it will exit with no output.
> To edit the code in place with the fixed formatting use `./lint.sh -i`.
> If `cpplint` flags a portion of your code, please make sure it is adhering to the proper code style. If it is a false
> positive or if there is no reasonable way to avoid the flag, you may put `// NOLINT` at the end of the line if there is
> space, or `// NOLINTNEXTLINE` on a new line above if there is no space. For any usages of `// NOLINT` or
> `// NOLINTNEXTLINE`, please describe the reason for its inclusion both in a code comment and in your pull request's
> comments section.
> If you want to disable formatting, use `// clang-format off` and `// clang-format on` around the manually formatted
> ```

</blockquote></details>

Not sure what the comment is here.
___
*[.github/CONTRIBUTING.md, line 423 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMQ6C-4joHDUjiwtjN:-MJNcpv25l0w5F0JyKdW:bjhlzom) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L423)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

This workflow works, but is suboptimal. Not saying there is anything to do about it in the PR, but I think we can improve this considerably with automated tooling. Here is an issue I have created to elaborate: https://github.com/maxitg/SetReplace/issues/449
</blockquote></details>

Yes, we should, let's discuss there.

**Review by taliesinb — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: all files reviewed, 4 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 88 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMG3bV5bbYeGL1Wcyh:-MJSwPqc28TM23Bwrew_:b-pbdqzg) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L88)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Yes, but we should do it simultaneously with changing the existing code.
</blockquote></details>

Agreed!
___
*[.github/CONTRIBUTING.md, line 407 at r4](https://reviewable.io/reviews/maxitg/setreplace/440#-MJMPvjR3Ry_B8qAxLA-:-MJSw_uyE18QauoN42yC:b-o9wrss) ([raw file](https://github.com/maxitg/setreplace/blob/d6e949247726bad43ec90e43132fcbc2a6493740/.github/CONTRIBUTING.md#L407)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Not sure what the comment is here.
</blockquote></details>

Accidental, sorry.

**Review by taliesinb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/440)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @taliesinb)

**Pull request merged**
