### PR TITLE
Alpine Linux 64 CI

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Changes C++ CI image to use public alpine image rather than custom public one specifically for this repo.

## Comments
* For some reason, cpplint is broken on previous CI image and was not catching errors. I fixed them in this PR. See [this failed build](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1434/workflows/6db31200-a23a-44e3-8ace-b0fb28b7f2c5/jobs/2037).
* Using this image makes it easier to install new tools on CI image for instance. There is no longer a need to edit a Dockerfile, build the image, then push anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565)

### CODE REVIEW

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[.circleci/config.yml, line 56 at r1](https://reviewable.io/reviews/maxitg/setreplace/565#-MO9Hab6CmY4aj3X9brn:-MO9Hab6CmY4aj3X9bro:b-w2ul54) ([raw file](https://github.com/maxitg/setreplace/blob/3d644d9307537a97479a464343e15f94495f1069/.circleci/config.yml#L56)):*
> ```YAML
>           command: |
>             apk add --no-cache bash git g++ make cmake clang python2
>             wget https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
> ```

Are you sure this is a more recent version than the one you get by `pip3 install cpplint`?

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[.circleci/config.yml, line 56 at r1](https://reviewable.io/reviews/maxitg/setreplace/565#-MO9Hab6CmY4aj3X9brn:-MO9OpSUD3IIVeDlJ4IG:bw0wlb9) ([raw file](https://github.com/maxitg/setreplace/blob/3d644d9307537a97479a464343e15f94495f1069/.circleci/config.yml#L56)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Are you sure this is a more recent version than the one you get by `pip3 install cpplint`?
</blockquote></details>

Done. Interestingly, pip uses a popular unofficial fork of cpplint since google doesn't maintain it very well.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann)

___
*[.circleci/config.yml, line 56 at r1](https://reviewable.io/reviews/maxitg/setreplace/565#-MO9Hab6CmY4aj3X9brn:-MO9RTJ3BTDjLkxl-IYv:b-qbzz24) ([raw file](https://github.com/maxitg/setreplace/blob/3d644d9307537a97479a464343e15f94495f1069/.circleci/config.yml#L56)):*
<details><summary><i>Previously, aokellermann (Antony Kellermann) wrote…</i></summary><blockquote>

Done. Interestingly, pip uses a popular unofficial fork of cpplint since google doesn't maintain it very well.
</blockquote></details>

But wouldn't it be simpler to add `py-pip` on the line above, and then do `pip3 install cpplint` here instead of manually downloading from GitHub?

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[.circleci/config.yml, line 56 at r1](https://reviewable.io/reviews/maxitg/setreplace/565#-MO9Hab6CmY4aj3X9brn:-MO9TDA52AYPASzrB12W:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/3d644d9307537a97479a464343e15f94495f1069/.circleci/config.yml#L56)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

But wouldn't it be simpler to add `py-pip` on the line above, and then do `pip3 install cpplint` here instead of manually downloading from GitHub?
</blockquote></details>

Done.

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/565#-:-MO9TbWc8GmPgqY-nf8r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
