### PR TITLE
Remove asterisk from SetReplace*.md

### PR DESCRIPTION
**Pull request by maxitg**
## Changes
* It appears asterisks in filenames are not supported on Windows, thus even the checkout fails.
* This removes the asterisk from `SetReplace*.md`, which should resolve the issue.

## Comments
* Hopefully, it being in history is not going to cause issues.

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/512)

### CODE REVIEW

**Review by daneelsan — COMMENTED** [review]
What do you mean by "... it being in history is not going to cause issues."?
I guess there is no way for me to test this, so :lgtm: (?)

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/512#-:-MLB3Kw77y9PXLnkkv6g:b-53tdc)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @daneelsan)

**Comment by maxitg** [comment]
If someone tries to check out the commits with the asterisk on Windows, that won't work because files cannot contain asterisks there. I assume it should not be a problem if one does not try to check out such branches, but I'm not sure.

**Comment by maxitg** [comment]
I just checked this PR builds fine on Windows (and it contains the asterisk in the history), so I don't think rewriting history is justified.

**Review by daneelsan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/512#-:-MLB5w1W7UJQ_VlSAWp4:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @daneelsan)

**Pull request merged**
