### PR TITLE
Managed Expressions

### LINKED ISSUE #574: Use ManagedExpressions in low-level implementation
### The problem
https://reference.wolfram.com/language/LibraryLink/tutorial/InteractionWithWolframLanguage.html#353220453

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Implements [managed expressions](https://reference.wolfram.com/language/LibraryLink/tutorial/InteractionWithWolframLanguage.html#353220453)
* Closes #574 

## Examples
To verify release is actually working (and not just releasing at program exit):
```c++
void setManageInstance([[maybe_unused]] WolframLibraryData libData, mbool mode, mint id) {
  std::string time = std::to_string(std::time(nullptr));
  if (mode == 0) {
    sets_.emplace(id, nullptr);
    std::system((std::string("echo \"create ") + time + "\" >> /tmp/sr").c_str());
  } else {
    sets_.erase(id);
    std::system((std::string("echo \"delete ") + time + "\" >> /tmp/sr").c_str());
  }
}
```
```bash
$ ./test.wls eventDeduplication && cat /tmp/sr
create 1609878542
delete 1609878542
create 1609878542
delete 1609878542
create 1609878542
delete 1609878542
...
create 1609878566
delete 1609878566
create 1609878566
delete 1609878566
create 1609878566
delete 1609878566
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/588)

### CODE REVIEW

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/588)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[libSetReplace/SetReplace.cpp, line 29 at r1](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJNMDp0n0cWEc7PURR:-MQJNMDp0n0cWEc7PURS:b-rizwx5) ([raw file](https://github.com/maxitg/setreplace/blob/30924d06833181ba610d17c9054541d1ce4c3d2c/libSetReplace/SetReplace.cpp#L29)):*
> ```cpp
> // We use a pointer here because map key insertion (setManageInstance) is separate from map value insertion (setCreate).
> // Until the value is inserted, the set is nullptr.
> std::unordered_map<SetID, std::unique_ptr<Set>> sets_;
> ```

Ah `std::unique_ptr<Set>` is much simpler than the thing I tried :+1: 
___
*[libSetReplace/SetReplace.cpp, line 378 at r1](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJN1kfDEE2XpUwLa6Y:-MQJN1kfDEE2XpUwLa6Z:bi6v2jb) ([raw file](https://github.com/maxitg/setreplace/blob/30924d06833181ba610d17c9054541d1ce4c3d2c/libSetReplace/SetReplace.cpp#L378)):*
> ```cpp
> EXTERN_C mint WolframLibrary_getVersion() { return WolframLibraryVersion; }
> 
> EXTERN_C int WolframLibrary_initialize([[maybe_unused]] WolframLibraryData libData) {
> ```

Should `[[maybe_unused]]` be removed here?

**Comment by aokellermann** [comment]
@daneelsan I'm not sure why but your comments aren't showing up in reviewable for me...

> Should `[[maybe_unused]]` be removed here?
Done.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/588)* status: all files reviewed, 3 unresolved discussions (waiting on @aokellermann)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJWcmSA0gCEBeW2AYr:-MQJWcmSA0gCEBeW2AYs:b-5kmpkl) ([raw file](https://github.com/maxitg/setreplace/blob/3847f1e8774498a262b3dd88b361805074846658/Kernel/setSubstitutionSystem$cpp.m#L46)):*
> ```objc
>     $Failed],
> 
>   (* Expressions are automatically managed, so this is only here for optional manual resource release. *)
> ```

I don't think we need it at all anymore. If we want to release it, we can just unset the handle. Even if it's a value in the evolution object, we can still replace it with `Missing[]` to lose the reference.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 31 at r3](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJZRzxAva5ZhY1u2Vj:-MQJZRzxAva5ZhY1u2Vk:b12a90n) ([raw file](https://github.com/maxitg/setreplace/blob/cbd38c15bd8f8907e23e887bd75c1c2ae4cfc6a1/Kernel/setSubstitutionSystem$cpp.m#L31)):*
> ```objc
> (* Load libSetReplace functions *)
> $libraryFunctions = {
>   $cpp$setCreate = If[$libraryFile =!= $Failed,
> ```

Should we rename this function from `setCreate` to `setInitialize` given that it now takes the set ID as an argument and that we now have two separate "create" calls on the WL side?
___
*[Kernel/setSubstitutionSystem$cpp.m, line 42 at r3](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJZ_1RBzetpb0lJyHn:-MQJZ_1RBzetpb0lJyHo:bkft40x) ([raw file](https://github.com/maxitg/setreplace/blob/cbd38c15bd8f8907e23e887bd75c1c2ae4cfc6a1/Kernel/setSubstitutionSystem$cpp.m#L42)):*
> ```objc
>         Integer, (* event deduplication *)
>         Integer, (* random seed *)
>         Integer}, (* set ID *)
> ```

It seems it would make more sense to put the set ID as the first argument for consistency with the other functions.
___
*[libSetReplace/SetReplace.cpp, line 22 at r3](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJZohZ3h3iH6_VUXTo:-MQJZohZ3h3iH6_VUXTp:b-83v4r2) ([raw file](https://github.com/maxitg/setreplace/blob/cbd38c15bd8f8907e23e887bd75c1c2ae4cfc6a1/libSetReplace/SetReplace.cpp#L22)):*
> ```cpp
> // We use a pointer here because map key insertion (setManageInstance) is separate from map value insertion (setCreate).
> // Until the value is inserted, the set is nullptr.
> std::unordered_map<SetID, std::unique_ptr<Set>> sets_;
> ```

Neat!

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/588)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Kernel/setSubstitutionSystem$cpp.m, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJWcmSA0gCEBeW2AYr:-MQJbt4Y2B07Q8v2flqj:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/3847f1e8774498a262b3dd88b361805074846658/Kernel/setSubstitutionSystem$cpp.m#L46)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think we need it at all anymore. If we want to release it, we can just unset the handle. Even if it's a value in the evolution object, we can still replace it with `Missing[]` to lose the reference.
</blockquote></details>

Done.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 31 at r3](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJZRzxAva5ZhY1u2Vj:-MQJacAfEzryb-PF471F:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cbd38c15bd8f8907e23e887bd75c1c2ae4cfc6a1/Kernel/setSubstitutionSystem$cpp.m#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Should we rename this function from `setCreate` to `setInitialize` given that it now takes the set ID as an argument and that we now have two separate "create" calls on the WL side?
</blockquote></details>

Done.
___
*[Kernel/setSubstitutionSystem$cpp.m, line 42 at r3](https://reviewable.io/reviews/maxitg/setreplace/588#-MQJZ_1RBzetpb0lJyHn:-MQJbRN14ZWvuUcEB_y0:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cbd38c15bd8f8907e23e887bd75c1c2ae4cfc6a1/Kernel/setSubstitutionSystem$cpp.m#L42)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It seems it would make more sense to put the set ID as the first argument for consistency with the other functions.
</blockquote></details>

Done.

**Review by maxitg — APPROVED** [review]
Very nice! The code is even shorter now.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/588#-:-MQJerAeCthhj-HyxEIb:b-1bchq6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
