### PR TITLE
Add IndexHypergraph function

### LINKED ISSUE #80: IndexHypergraph
Similar to `IndexGraph` it is useful to have a function that would replace the names of the atoms by their indices in a given hypergraph.

That could be called `IndexHypergraph`, and is a simple utility function.

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes
* Closes #80.
* Expose `IndexHypergraph` utility function.
* Moving `hypergraphQ` and some `General` messages to `Kernel/utilities.m`

## Comments
* Better examples of the use of this function are appreciated.

## Examples
```wl
In[] := IndexHypergraph[{{x, y, z}, {y, z, {y}}}]
Out[] = {{1, 2, 3}, {2, 3, 4}}
```

```wl
In[] := IndexHypergraph[{{x, y, z}, {y, z, y}}, -5]
Out[] = {{-5, -4, -3}, {-4, -3, -4}}
```

```wl
In[] := IndexHypergraph[]

During evaluation of In[] := IndexHypergraph::argt: IndexHypergraph called with 0 arguments; 1 or 2 arguments are expected.

Out[] = IndexHypergraph[]
```

```wl
In[] := IndexHypergraph[{x, y, {z}}, 2]

During evaluation of In[] := IndexHypergraph::invalidHypergraph: The argument at position 1 in IndexHypergraph[{x,y,{z}},2] is not a valid hypergraph.

Out[] = IndexHypergraph[{x, y, {z}}, 2]
```

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473)

### CODE REVIEW

**Comment by daneelsan** [comment]
When extracting the vertex list with `vertexList`, do we want to sort the vertices or keep them as they come?
I.e. `Sort @ Union @ <vertex list>`, instead of `DeleteDuplicates @ <vertex list>`

In `IndexGraph`:
```wl
In[]:= IndexGraph[{x -> y, y -> z, w -> x}] // InputForm
Out[]//InputForm= Graph[{1, 2, 3, 4}, {DirectedEdge[1, 2], DirectedEdge[2, 3], DirectedEdge[4, 1]}]
```
vs `IndexHypergraph` (notice how `w` is `1` due to the `Sort`):
```wl
In[]:= IndexHypergraph[{{x, y}, {y, z}, {w, x}}]
Out[]= {{2, 3}, {3, 4}, {1, 2}}
```

**Review by maxitg — CHANGES_REQUESTED** [review]
I think sorting them makes more sense in our case. That is because unlike `Graph`, we don't have a vertex list built into the hypergraph. In addition, the order of expressions has a specific meaning (the most recently created expressions are at the end). And the atoms are typically named with increasing indices as they are created. Hence, if we sort the vertices, and, say, delete or rearrange some expressions (due to updating), the `IndexHypergraph` will still label the atoms in the order they were created, which, I think, is a nice bonus.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473#-:-MJjk3Sq18Q9tkViNL9q:bs786zb)* status: all files reviewed, 6 unresolved discussions (waiting on @daneelsan)

___
*[README.md, line 2040 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjlUfKCfl9jJLKjR1-:-MJjlUfKCfl9jJLKjR10:b-bg5r3e) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/README.md#L2040)):*
> ```Markdown
> ```
> 
> Replace the vertices with indices starting from -10:
> ```

They are not really indices if they start from -10. I suggest replacing "indices" -> "integers".
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjm9If9fHGptousET9:-MJjm9If9fHGptousETA:b-nf12es) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/IndexHypergraph.m#L22)):*
> ```objc
> 
> (* main *)
> expr : IndexHypergraph[hgraph_, r : _ : 1] := ModuleScope[
> ```

Use a more descriptive name than `r`.
___
*[Kernel/IndexHypergraph.m, line 28 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjmOoJEBQCLznoZqF0:-MJjmOoJEBQCLznoZqF1:b-4v5c1r) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/IndexHypergraph.m#L28)):*
> ```objc
> 
> (* Normal form *)
> indexHypergraph[_, hgraph_ ? hypergraphQ, r : _Integer?IntegerQ] := ModuleScope[
> ```

Nit: add spaces before and after `?`.
___
*[Kernel/utilities.m, line 57 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjohDi9A5c1DKZy46C:-MJjohDi9A5c1DKZy46D:brnhadf) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/utilities.m#L57)):*
> ```objc
>   "The argument at position `1` in `2` is not a valid hypergraph.";
> 
> General::invalidList =
> ```

I don't think this message belongs here in utilities. I think we should either move it to `makeMessage.m` (as a normal message, not using the format used there) or use `General::invl` instead.
___
*[Tests/IndexHypergraph.wlt, line 13 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjpFX9E-sGvMAV_1Lg:-MJjpFX9E-sGvMAV_1Lh:bga3wmd) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Tests/IndexHypergraph.wlt#L13)):*
> ```Mathematica
>         {}
>       ],
> ```

I would also add `IndexHypergraph[{{}}]` as a test case (a zero-arity hyperedge).
___
*[Tests/IndexHypergraph.wlt, line 23 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjpnt60tzyS-kclCD1:-MJjpnt60tzyS-kclCD2:b26e328) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Tests/IndexHypergraph.wlt#L23)):*
> ```Mathematica
>         {{-10, -9, -8, -7, -6}}
>       ],
> ```

I think we should be deliberate about sorting the atoms, so how about `IndexHypergraph[{Range[10, 6, -1], Range[-5, -1]}]`?

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @maxitg)

___
*[README.md, line 2040 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjlUfKCfl9jJLKjR1-:-MJnIMX64hUcYNImT-A6:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/README.md#L2040)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

They are not really indices if they start from -10. I suggest replacing "indices" -> "integers".
</blockquote></details>

Done.
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjm9If9fHGptousET9:-MJnINvj6IcB1p0-Wafp:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/IndexHypergraph.m#L22)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use a more descriptive name than `r`.
</blockquote></details>

Done.
___
*[Kernel/utilities.m, line 57 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjohDi9A5c1DKZy46C:-MJnIP5u52RkIIeD-D6j:b-30mdod) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/utilities.m#L57)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think this message belongs here in utilities. I think we should either move it to `makeMessage.m` (as a normal message, not using the format used there) or use `General::invl` instead.
</blockquote></details>

I opted to use `General::invl` and removed `invalidList`.
___
*[Tests/IndexHypergraph.wlt, line 13 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjpFX9E-sGvMAV_1Lg:-MJnIV9G2yBIt09VVna3:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Tests/IndexHypergraph.wlt#L13)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I would also add `IndexHypergraph[{{}}]` as a test case (a zero-arity hyperedge).
</blockquote></details>

Done.
___
*[Tests/IndexHypergraph.wlt, line 23 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjpnt60tzyS-kclCD1:-MJnIX1GDzwjrBQSO1vF:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Tests/IndexHypergraph.wlt#L23)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think we should be deliberate about sorting the atoms, so how about `IndexHypergraph[{Range[10, 6, -1], Range[-5, -1]}]`?
</blockquote></details>

Done.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan)

___
*[README.md, line 2040 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjlUfKCfl9jJLKjR1-:-MJneeD_2AapAu76JAvv:bf2c65w) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/README.md#L2040)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any changes here.
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjm9If9fHGptousET9:-MJnepGe1i_C8S4jbYkH:b-7la8o9) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/IndexHypergraph.m#L22)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is another `r` on this line, and one at the bottom.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @maxitg)

___
*[README.md, line 2040 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjlUfKCfl9jJLKjR1-:-MJngGpCD8QK7W61UdTA:b4my2uu) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/README.md#L2040)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't see any changes here.
</blockquote></details>

Oops, forgot to push it. It is done now.
___
*[Kernel/IndexHypergraph.m, line 22 at r5](https://reviewable.io/reviews/maxitg/setreplace/473#-MJjm9If9fHGptousET9:-MJngKPQCYjCzq-tqyba:bbvuoah) ([raw file](https://github.com/maxitg/setreplace/blob/952b2e043d19ed34a6b198680920226b8c89a5ee/Kernel/IndexHypergraph.m#L22)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There is another `r` on this line, and one at the bottom.
</blockquote></details>

Got them.

**Review by maxitg — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/473)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
