### PR TITLE
Adding "OptionNames" in SyntaxInformation to all exposed symbols

### LINKED ISSUE #218: SyntaxInformation about options
Currently, `SyntaxInformation` is not defined for options of most functions with the exception of `RulePlot`, i.e., the following
```
In[] := WolframModelPlot[{{1, 2, 3}}, "InvalidOption" -> 4]
```
should color `"InvalidOption"` in red, which does not currently do:
image

**Expected behavior**
It should do something similar to `RulePlot`:
image

**Version:**
 - OS: macOS 10.15.3 (19D76)
 - Wolfram Language Version: "12.1.0 for Mac OS X x86 (64-bit) (February 26, 2020)"
 - SetReplace git sha: 7fe0dc6dc9b94db2114bf2f26c2f8a39ade331bf

### PR DESCRIPTION
**Pull request by daneelsan**
## Changes

* Closes #218.
* Adds "OptionNames" of `SyntaxInformation` for all exposed symbols with `Options`.

## Comments:

* List of symbols that were missing "OptionNames":
```wl
{HypergraphUnificationsPlot, SetReplace, SetReplaceAll, SetReplaceFixedPoint, SetReplaceFixedPointList, SetReplaceList, WolframModel}
```

## Examples

```wl
In[] := SetReplace[{{1, 2, 3}}, {{{1, 2, 3}} -> {4}}, 1,  "InvalidOption" -> "test"]
```
image

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)

### CODE REVIEW

**Comment by daneelsan** [comment]
I added this code to the `hasNoSyntaxInformationQ` function in `meta.wlt`:
```wl
And[
            Options[Unevaluated @ symbol] =!= {},
            MissingQ[Lookup[SyntaxInformation[Unevaluated @ symbol], "OptionNames"]]]
```
to error if the exposed symbols has `Options` but no "OptionNames". However, it doesn't seem to work, it doesn't error out if I remove the "OptionNames" from a symbol...

**Comment by maxitg** [comment]
@daneelsan, are you sure it doesn't work? On current master (67113af57fb2d158e515221af7ffb9e7daa24c56):

```wl
In[] := MissingQ[Lookup[SyntaxInformation[#], "OptionNames"]] & /@ {WolframModel, HypergraphPlot}
Out[] = {True, False}
```

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann and @daneelsan)

___
*[Tests/meta.wlt, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmBtYD4Y6wqZ_g-FCF:-MQmBtYEDZ2ZHskL_GTw:b-dvacr5) ([raw file](https://github.com/maxitg/setreplace/blob/b99db18139fbf3fea359fa981629580e9bf7491e/Tests/meta.wlt#L28)):*
> ```Mathematica
>         Not[
>           StringStartsQ[SymbolName @ Unevaluated @ symbol, "$"] ||
>           SyntaxInformation[Unevaluated @ symbol] =!= {} ||
> ```

Shouldn't this be an `&&` instead of `||`? Currently, it says, either the symbol should start with `$`, OR it should have syntax information OR the syntax information should have `"OptionNames"`. I don't think the `And` below is correct either.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann and @maxitg)

___
*[Tests/meta.wlt, line 28 at r1](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmBtYD4Y6wqZ_g-FCF:-MQmFWFT6yL8e1a1Zh6o:b-5jjhby) ([raw file](https://github.com/maxitg/setreplace/blob/b99db18139fbf3fea359fa981629580e9bf7491e/Tests/meta.wlt#L28)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Shouldn't this be an `&&` instead of `||`? Currently, it says, either the symbol should start with `$`, OR it should have syntax information OR the syntax information should have `"OptionNames"`. I don't think the `And` below is correct either.
</blockquote></details>

Now that I think about it, you are right:
```wl
hasNoSyntaxInformationQ = Function[symbol,
  ! StringStartsQ[SymbolName @ Unevaluated @ symbol, "$"] &&
   (
    SyntaxInformation[Unevaluated @ symbol] === {} ||
     (Options[Unevaluated @ symbol] =!= {} && 
       MissingQ[Lookup[SyntaxInformation[Unevaluated @ symbol], "OptionNames"]])
    ),
  HoldFirst]
```

And in master:
```wl
In[] := Select[Lookup[Package`PackageInformation["SetReplace`"], "PackageExports"], hasNoSyntaxInformationQ]

Out[] = HoldComplete[HypergraphUnificationsPlot, SetReplaceAll, SetReplaceFixedPointList, SetReplaceFixedPoint, SetReplaceList, SetReplace, WolframModel]
```

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann and @daneelsan)

___
*[Tests/meta.wlt, line 24 at r2](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmLBVRAXuZWbhIAT8z:-MQmLBVRAXuZWbhIAT9-:b-sekagf) ([raw file](https://github.com/maxitg/setreplace/blob/c97812f13be2a99e4aa8567ea391575a46274f6e/Tests/meta.wlt#L24)):*
> ```Mathematica
>       (* Additionally, SyntaxInformation should specify "OptionNames" if the symbol has Options. *)
> 
>       hasNoSyntaxInformationQ = Function[
> ```

I think it would be better to rewrite this function as `hasSyntaxInformationQ`. Otherwise, double negatives make it somewhat difficult to understand.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @maxitg)

___
*[Tests/meta.wlt, line 24 at r2](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmLBVRAXuZWbhIAT8z:-MQmMzZ37R3oz8sWu-RI:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c97812f13be2a99e4aa8567ea391575a46274f6e/Tests/meta.wlt#L24)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it would be better to rewrite this function as `hasSyntaxInformationQ`. Otherwise, double negatives make it somewhat difficult to understand.
</blockquote></details>

Done.

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: all files reviewed, 1 unresolved discussion (waiting on @aokellermann and @daneelsan)

___
*[Tests/meta.wlt, line 24 at r2](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmLBVRAXuZWbhIAT8z:-MQmW4vJ1LYerv8h9Vah:bj6r5tb) ([raw file](https://github.com/maxitg/setreplace/blob/c97812f13be2a99e4aa8567ea391575a46274f6e/Tests/meta.wlt#L24)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, now it's not correct because it actually checks for `hasNoSyntaxInformationQ` right now. I'm suggesting to rewrite `And <-> Or` and `Not <-> Identity` in the body so that it's more readable, and use it in `VerificationTest` with a `Not` where it will be easier to understand.

**Review by daneelsan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @aokellermann and @maxitg)

___
*[Tests/meta.wlt, line 24 at r2](https://reviewable.io/reviews/maxitg/setreplace/592#-MQmLBVRAXuZWbhIAT8z:-MQmlW2q14F8X_7l3DFR:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c97812f13be2a99e4aa8567ea391575a46274f6e/Tests/meta.wlt#L24)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Well, now it's not correct because it actually checks for `hasNoSyntaxInformationQ` right now. I'm suggesting to rewrite `And <-> Or` and `Not <-> Identity` in the body so that it's more readable, and use it in `VerificationTest` with a `Not` where it will be easier to understand.
</blockquote></details>

Done.

**Review by maxitg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/592#-:-MQrrL3u28itz8pP4ki4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aokellermann)

**Pull request merged**
